module.exports = {
  "testPages": {
    "connectionTest": {
      "title": "صفحة اختبار الاتصال",
      "description": "هذه صفحة اختبار بسيطة للتحقق من الاتصال",
      "testing": "جاري اختبار الاتصال...",
      "error": "خطأ:",
      "refreshTest": "تحديث الاختبار",
      "connectionSuccess": "تم الاتصال بواجهة البرمجة بنجاح!"
    },
    "aiTest": {
      "title": "صفحة اختبار المساعد الذكي",
      "description": "توضح هذه الصفحة وظائف المساعد الذكي.",
      "platformTitle": "منصة ذكاء وسائل الإعلام",
      "featuresTitle": "الميزات",
      "features": {
        "monitoring": "مراقبة شاملة لوسائل التواصل الاجتماعي",
        "sentiment": "تحليل المشاعر للجهات الحكومية في الإمارات",
        "analytics": "تحليلات وتقارير متقدمة",
        "alerts": "تنبيهات فورية للكلمات المفتاحية والكيانات",
        "contentManagement": "إدارة المحتوى للأصول الإعلامية"
      }
    },
    "sentimentTest": {
      "title": "اختبار تحليل المشاعر OpenAI"
    }
  },
  "auth": {
    "login": "تسجيل الدخول",
    "logout": "تسجيل الخروج",
    "username": "اسم المستخدم",
    "password": "كلمة المرور",
    "forgotPassword": "نسيت كلمة المرور؟",
    "rememberMe": "تذكرني",
    "loginButton": "تسجيل الدخول",
    "loginTitle": "تسجيل الدخول إلى حسابك",
    "loginDescription": "مرحبًا بعودتك! أدخل بيانات الاعتماد الخاصة بك للوصول إلى النظام.",
    "loginError": "اسم المستخدم أو كلمة المرور غير صحيحة",
    "loginSuccess": "تم تسجيل الدخول بنجاح",
    "logoutSuccess": "تم تسجيل الخروج بنجاح"
  },
  "notifications": {
    "title": "الإشعارات",
    "count": "{{count}} إشعارات",
    "keywordAlert": "تم اكتشاف تنبيه كلمة مفتاحية جديدة",
    "negativeReaction": "رد فعل سلبي على منشور حديث",
    "newReport": "تقرير أسبوعي جديد متاح",
    "minutesAgo": "منذ {{minutes}} دقيقة",
    "hoursAgo": "منذ {{hours}} ساعة",
    "daysAgo": "منذ {{days}} يوم",
    "noNotifications": "لا توجد إشعارات",
    "markAllAsRead": "تحديد الكل كمقروء",
    "viewAll": "عرض الكل"
  },
  "app": {
    "title": "ذكاء الإعلام - شرطة عجمان",
    "description": "مراقبة الإعلام وتحليلات شاملة"
  },
  "cookieTest": {
    "title": "اختبار HTTPS وأمان ملفات تعريف الارتباط",
    "tabs": {
      "manageCookies": "إدارة ملفات تعريف الارتباط",
      "debugInfo": "معلومات التصحيح"
    },
    "setCookie": {
      "title": "تعيين ملف تعريف الارتباط",
      "description": "استخدم هذا النموذج لتعيين ملف تعريف ارتباط اختباري مع علامات آمنة",
      "cookieName": "اسم ملف تعريف الارتباط",
      "cookieValue": "قيمة ملف تعريف الارتباط",
      "setButton": "تعيين ملف تعريف الارتباط",
      "clearButton": "مسح ملف تعريف الارتباط"
    },
    "currentCookies": {
      "title": "ملفات تعريف الارتباط الحالية",
      "description": "هذه هي ملفات تعريف الارتباط المتاحة حاليًا للتطبيق",
      "noCookies": "لم يتم العثور على ملفات تعريف ارتباط",
      "refreshButton": "تحديث ملفات تعريف الارتباط"
    },
    "debug": {
      "title": "معلومات التصحيح",
      "description": "عرض تفاصيل HTTP/HTTPS لاتصالك الحالي",
      "loadButton": "تحميل معلومات التصحيح"
    },
    "status": {
      "success": "نجاح",
      "error": "خطأ"
    }
  },
  "dialog": {
    "demo": {
      "title": "عرض مكون الحوار",
      "subtitle": "عرض تطبيقات وأنماط الحوارات المختلفة",
      "basic": {
        "title": "حوار أساسي",
        "description": "حوار بسيط مع عنوان ووصف وإجراءات.",
        "buttonText": "فتح الحوار الأساسي",
        "dialogTitle": "مثال الحوار الأساسي",
        "dialogDescription": "هذا حوار بسيط مع عنوان ووصف وإجراءات.",
        "content": "محتوى الحوار يذهب هنا. يمكنك وضع أي محتوى داخل حوار.",
        "cancel": "إلغاء",
        "save": "حفظ التغييرات"
      },
      "form": {
        "title": "حوار النموذج",
        "description": "حوار يحتوي على نموذج مع التحقق من الصحة.",
        "buttonText": "فتح حوار النموذج",
        "dialogTitle": "تعديل الملف الشخصي",
        "dialogDescription": "قم بإجراء تغييرات على إعدادات ملفك الشخصي هنا.",
        "name": "الاسم",
        "namePlaceholder": "أدخل اسمك",
        "email": "البريد الإلكتروني",
        "emailPlaceholder": "أدخل بريدك الإلكتروني",
        "notifications": "تفعيل الإشعارات",
        "cancel": "إلغاء",
        "save": "حفظ التغييرات",
        "submitted": "تم إرسال النموذج"
      },
      "custom": {
        "title": "حوار مخصص",
        "description": "حوار بتنسيق ورسوم متحركة مخصصة.",
        "buttonText": "فتح الحوار المخصص",
        "dialogTitle": "مثال الحوار المخصص",
        "badge": "نمط مخصص",
        "content": "هذا الحوار له رأس وتذييل بنمط مخصص.",
        "note": "ملاحظة:",
        "noteContent": "يمكنك تخصيص أي جزء من الحوار باستخدام CSS العادي أو فئات Tailwind.",
        "cancel": "إلغاء",
        "apply": "تطبيق التغييرات"
      },
      "success": {
        "title": "حوار النجاح",
        "description": "حوار يعرض تأكيد النجاح.",
        "buttonText": "فتح حوار النجاح",
        "dialogTitle": "نجاح!",
        "dialogContent": "تم حفظ التغييرات الخاصة بك بنجاح.",
        "continue": "متابعة"
      },
      "implementation": {
        "title": "تفاصيل التنفيذ",
        "description": "تستخدم هذه الحوارات خطاف useDialog ومكون Dialog المعزز مع إدارة التركيز المناسبة وسمات إمكانية الوصول.",
        "code": {
          "trigger": "فتح الحوار",
          "title": "عنوان الحوار",
          "description": "هذا حوار.",
          "content": "المحتوى يذهب هنا",
          "cancel": "إلغاء",
          "submit": "إرسال"
        }
      }
    }
  },
  "common": {
    "cancel": "إلغاء",
    "creating": "جاري الإنشاء...",
    "create": "إنشاء",
    "loading": "جاري التحميل...",
    "actions": "إجراءات",
    "edit": "تعديل",
    "delete": "حذف",
    "deletingAction": "جاري الحذف...",
    "deleteAction": "حذف",
    "processingRequest": "جاري معالجة الطلب...",
    "deleting": "جاري الحذف...",
    "save": "حفظ",
    "saving": "جاري الحفظ...",
    "confirm": "تأكيد",
    "close": "إغلاق",
    "back": "رجوع",
    "next": "التالي",
    "submit": "إرسال",
    "search": "بحث",
    "filter": "تصفية",
    "refresh": "تحديث",
    "view": "عرض",
    "details": "تفاصيل",
    "more": "المزيد",
    "less": "أقل",
    "notFound": "غير موجود",
    "noData": "لا توجد بيانات متاحة",
    "error": "خطأ",
    "success": "نجاح",
    "warning": "تحذير",
    "info": "معلومات",
    "language": "اللغة",
    "english": "الإنجليزية",
    "arabic": "العربية",
    "theme": "السمة",
    "light": "فاتح",
    "dark": "داكن",
    "system": "النظام",
    "high": "مرتفع",
    "medium": "متوسط", 
    "low": "منخفض",
    "admin": "مسؤول",
    "user": "مستخدم",
    "editor": "محرر",
    "userMenu": "قائمة المستخدم",
    "logout": "تسجيل الخروج",
    "login": "تسجيل الدخول",
    "profile": "الملف الشخصي",
    "minutes_ago": "منذ {{count}} دقيقة",
    "minutes_ago_one": "منذ دقيقة واحدة",
    "hours_ago": "منذ {{count}} ساعة",
    "hours_ago_one": "منذ ساعة واحدة",
    "days_ago": "منذ {{count}} يوم",
    "days_ago_one": "منذ يوم واحد",
    "connection_status": {
      "connected": "متصل",
      "disconnected": "غير متصل"
    }
  },
  "calendar": {
    "title": "التقويم",
    "pickDate": "اختر تاريخًا",
    "today": "اليوم",
    "selected": "محدد",
    "previousMonth": "الشهر السابق",
    "nextMonth": "الشهر التالي",
    "eventsForDate": "الأحداث في {{date}}",
    "noEvents": "لا توجد أحداث لهذا التاريخ",
    "addEvent": "إضافة حدث",
    "eventTypes": {
      "default": "حدث",
      "important": "مهم",
      "reminder": "تذكير"
    }
  },
  "clock": {
    "title": "الساعة",
    "currentTime": "الوقت الحالي",
    "timeZone": "المنطقة الزمنية"
  },
  "entity": {
    "metrics": {
      "none": "لا شيء",
      "totalMentions": "إجمالي الإشارات",
      "activePlatform": "المنصة الأكثر نشاطاً",
      "ofAllMentions": "من جميع الإشارات",
      "avgSentiment": "متوسط المشاعر",
      "sentimentBreakdown": "تحليل المشاعر"
    },
    "sentiment": {
      "positive": "إيجابي",
      "negative": "سلبي"
    },
    "tabs": {
      "posts": "المنشورات",
      "trends": "الاتجاهات",
      "analytics": "التحليلات"
    },
    "posts": {
      "noMentions": "لم يتم العثور على إشارات"
    },
    "trends": {
      "sentimentTrend": "اتجاه المشاعر",
      "sentimentOverTime": "المشاعر عبر الزمن",
      "sentimentScore": "درجة المشاعر",
      "date": "التاريخ",
      "notEnoughData": "لا توجد بيانات كافية لعرض الاتجاهات",
      "mentionsByPlatform": "الإشارات حسب المنصة",
      "distributionAcrossPlatforms": "التوزيع عبر المنصات",
      "noPlatformData": "لا تتوفر بيانات المنصة"
    },
    "analytics": {
      "sentimentAnalysis": "تحليل المشاعر",
      "breakdownDescription": "تحليل المشاعر عبر المنصات",
      "numberOfMentions": "عدد الإشارات",
      "noSentimentData": "لا تتوفر بيانات المشاعر"
    },
    "error": {
      "invalidPost": "بيانات المنشور غير صالحة"
    },
    "post": {
      "author": "الكاتب",
      "unknownAuthor": "كاتب غير معروف",
      "unknownDate": "تاريخ غير معروف",
      "unknownPlatform": "منصة غير معروفة",
      "noContent": "لا يوجد محتوى متاح",
      "viewOriginal": "عرض الأصلي"
    },
    "normalView": "العرض العادي",
    "debugView": "عرض التصحيح",
    "monitoring": "مراقبة الكيانات الحكومية",
    "enableDebugMode": "تفعيل وضع التصحيح",
    "disableDebugMode": "تعطيل وضع التصحيح"
  },
  "reports": {
    "textExportDesc": "تم تصدير التقرير كنص بنجاح",
    "comingSoon": "قريباً",
    "formatNotSupported": "تنسيق التصدير هذا غير مدعوم حالياً",
    "exportReady": "التصدير جاهز",
    "preparingExport": "جاري تحضير التصدير",
    "exportFullReport": "تصدير التقرير الكامل",
    "preparingPrint": "تحضير نسخة للطباعة",
    "viewingDetailedReport": "عرض التقرير المفصل"
  },
  "media": {
    "type": {
      "image": "صورة",
      "video": "فيديو", 
      "document": "مستند"
    },
    "mediaCenter": {
      "title": "مركز الإعلام",
      "viewAll": "عرض الكل",
      "image": "صورة",
      "video": "فيديو",
      "document": "مستند",
      "projects": "مشاريع",
      "events": "فعاليات",
      "reports": "تقارير",
      "news": "أخبار",
      "weeks": "أسابيع",
      "days": "أيام",
      "upload": "رفع",
      "uaeNewsSources": "مصادر أخبار الإمارات",
      "integratedPlatforms": "منصات إخبارية متكاملة ومصادر حكومية رسمية",
      "sourcePlatforms": "منصات المصادر",
      "ajmanGovPressReleases": "البيانات الصحفية لحكومة عجمان",
      "ajmanPoliceNews": "أخبار شرطة عجمان",
      "wamNewsAgency": "وكالة أنباء الإمارات (وام)",
      "ajmanGovDescription": "الوصول إلى البيانات الصحفية والأخبار والإعلانات الرسمية من حكومة عجمان",
      "ajmanPoliceDescription": "الوصول إلى تحديثات الأمن وأخبار المجتمع ومعلومات السلامة من شرطة عجمان",
      "wamDescription": "الوصول إلى وكالة أنباء الإمارات (وام) للحصول على تغطية شاملة لأخبار الإمارات والتحديثات",
      "browse": "تصفح",
      "visitWebsite": "زيارة الموقع",
      "visitOfficialWebsite": "زيارة الموقع الرسمي",
      "mediaDirectory": "دليل وسائل الإعلام",
      "mediaDirectoryDesc": "دليل الصحفيين، مصادر الإعلام، والبيانات الصحفية",
      "journalists": "الصحفيون",
      "mediaSources": "مصادر الإعلام",
      "pressReleases": "البيانات الصحفية",
      "noDate": "لا يوجد تاريخ متاح"
    }
  },
  "excellence": {
    "title": "مؤشرات التميز المؤسسي",
    "description": "تتبع وتحليل مؤشرات الأداء الرئيسية للتميز المؤسسي عبر المحاور الاستراتيجية",
    "dateRange": "الفترة الزمنية",
    "pickDates": "اختر التواريخ",
    "strategicAxis": "المحور الاستراتيجي",
    "allAxes": "جميع المحاور",
    "communication": "التواصل",
    "innovation": "الابتكار", 
    "smartTransformation": "التحول الذكي",
    "dataManagement": "إدارة البيانات",
    "mainIndicators": "المؤشرات الرئيسية",
    "subIndicators": "المؤشرات الفرعية",
    "refresh": "تحديث البيانات",
    "exportCSV": "تصدير CSV",
    "exportPDF": "تصدير PDF",
    "exportExcel": "تصدير Excel",
    "exportFullReport": "تصدير التقرير الكامل",
    "exportOptions": "خيارات التصدير",
    "exportSuccess": "تم التصدير بنجاح",
    "exportError": "خطأ في التصدير",
    "noDataToExport": "لا توجد بيانات متاحة للتصدير",
    "reportExported": "تم تصدير التقرير بنجاح",
    "current": "القيمة الحالية",
    "target": "القيمة المستهدفة",
    "status": "الحالة",
    "progress": "التقدم",
    "metricDetails": "تفاصيل المقياس",
    "noData": "لا توجد بيانات متاحة للفترة المحددة",
    "loadingData": "جاري تحميل بيانات المؤشرات...",
    "filterResults": "تصفية النتائج",
    "applyFilters": "تطبيق الفلاتر",
    "resetFilters": "إعادة تعيين",
    "knowledgeScoreImproved": "تحسن درجة المعرفة بنسبة {{percent}}%",
    "innovationMetricsUpdated": "تم تحديث مقاييس الابتكار",
    "pillarComparison": "مقارنة المحاور",
    "digitalPillar": "المحور الرقمي",
    "yearlyTrends": "الاتجاهات السنوية",
    "subindicatorsDistribution": "توزيع المؤشرات الفرعية",
    "excellent": "ممتاز",
    "veryGood": "جيد جداً",
    "good": "جيد",
    "average": "متوسط",
    "needsImprovement": "يحتاج إلى تحسين",
    "subindicatorsCount": "عدد المؤشرات الفرعية",
    "pillarContribution": "مساهمة المحور",
    "indicatorsDescription": "نظرة شاملة على مؤشرات التميز المؤسسي عبر جميع المحاور",
    "reportDescription": "تنزيل تقرير مؤشرات التميز الكامل مع تحليل مفصل ورؤى",
    "coverageVolume": "حجم التغطية الإعلامية",
    "positiveCoverageRate": "معدل التغطية الإيجابية",
    "mediaSentimentIndex": "مؤشر المشاعر الإعلامية",
    "socialEngagementRate": "معدل التفاعل الاجتماعي",
    "responseTime": "وقت الاستجابة",
    "shareOfVoice": "حصة الصوت",
    "implementedInnovations": "الابتكارات المنفذة",
    "ideaImplementationRate": "معدل تنفيذ الأفكار",
    "employeeInnovationRate": "معدل ابتكار الموظفين",
    "innovationAwards": "جوائز الابتكار",
    "operationalEfficiency": "الكفاءة التشغيلية",
    "innovationMediaCoverage": "التغطية الإعلامية للابتكار",
    "digitalServicesPercent": "نسبة الخدمات الرقمية",
    "digitalServicesAdoptionRate": "معدل تبني الخدمات الرقمية",
    "smartServicesUserSatisfaction": "رضا المستخدم عن الخدمات الذكية",
    "internalProcessesAutomation": "أتمتة العمليات الداخلية",
    "smartInitiativesImplemented": "المبادرات الذكية المنفذة",
    "knowledgeSharingSessions": "جلسات مشاركة المعرفة",
    "avgTrainingHours": "متوسط ساعات التدريب",
    "coreDataAccuracyRate": "معدل دقة البيانات الأساسية",
    "statisticalReportsPublished": "التقارير الإحصائية المنشورة",
    "dataDrivenDecisionIndex": "مؤشر القرارات المستندة إلى البيانات"
  },
  "analysis": {
    "positive": "إيجابي",
    "neutral": "محايد",
    "negative": "سلبي",
    "positiveSentiment": "المشاعر الإيجابية",
    "negativeSentiment": "المشاعر السلبية",
    "sentimentImprovement": "تحسن المشاعر من الفترة السابقة",
    "sentimentDecrease": "انخفاض المشاعر من الفترة السابقة",
    "sentimentDistribution": "توزيع المشاعر",
    "sentimentBreakdown": "تفصيل المشاعر",
    "sentimentFilters": "فلاتر المشاعر",
    "filterDescription": "تصفية المحتوى حسب المنصة والمشاعر"
  },
  "monitoring": {
    "title": "مراقبة المحتوى",
    "mediaMonitoring": "مراقبة وسائل الإعلام",
    "keywords": "الكلمات المفتاحية",
    "keywordAlerts": "تنبيهات الكلمات المفتاحية",
    "alertSettings": "إعدادات التنبيه",
    "addKeyword": "إضافة كلمة مفتاحية",
    "viewAlerts": "عرض التنبيهات",
    "searchMentions": "البحث في الإشارات",
    "clearAll": "مسح الكل",
    "downloadReport": "تنزيل التقرير",
    "all": "الكل",
    "twitter": "تويتر",
    "facebook": "فيسبوك",
    "instagram": "انستجرام",
    "news": "الأخبار",
    "noResults": "لم يتم العثور على نتائج لبحثك",
    "noMentions": "لم يتم العثور على إشارات",
    "twitterContent": "سيظهر محتوى تويتر هنا",
    "facebookContent": "سيظهر محتوى فيسبوك هنا",
    "instagramContent": "سيظهر محتوى انستجرام هنا",
    "newsContent": "ستظهر الأخبار هنا",
    "hoursAgo": "منذ {{hours}} ساعة",
    "defaultUser": "مستخدم",
    "defaultUsername": "اسم_المستخدم",
    "defaultAvatar": "https://randomuser.me/api/portraits/women/68.jpg",
    "testEmailSent": "تم إرسال بريد إلكتروني تجريبي",
    "testEmailSentDesc": "تم إرسال البريد الإلكتروني التجريبي بنجاح.",
    "emailRequired": "عنوان البريد الإلكتروني مطلوب",
    "testEmailFailed": "فشل إرسال البريد الإلكتروني التجريبي",
    "activeAlerts": "التنبيهات النشطة",
    "negativeRise": "ارتفاع المشاعر السلبية لمحتوى شرطة عجمان",
    "keywordTrends": "الكلمات المفتاحية الرائجة المتعلقة بالجريمة",
    "threshold": "الحد",
    "mentions": "إشارات",
    "testEmailNotifications": "اختبار إشعارات البريد الإلكتروني",
    "testEmailDesc": "إرسال بريد إلكتروني تجريبي للتحقق من استلام الإشعارات",
    "enterEmail": "أدخل عنوان بريدك الإلكتروني",
    "sendTest": "إرسال اختبار",
    "sources": "المصادر",
    "newsWebsites": "مواقع الأخبار",
    "blogs": "المدونات",
    "manageSourcesButton": "إدارة المصادر والفلاتر"
  },
  "navigation": {
    "dashboard": "لوحة التحكم", 
    "personalizedDashboard": "لوحة التحكم المخصصة",
    "mediaCenter": "مركز الإعلام",
    "socialMediaManagement": "إدارة وسائل التواصل الاجتماعي",
    "socialMedia": "وسائل التواصل الاجتماعي",
    "socialPublishing": "نشر المحتوى الاجتماعي",
    "monitoring": "المراقبة",
    "entityMonitoring": "مراقبة الكيانات",
    "reports": "التقارير",
    "smartReports": "التقارير الذكية",
    "excellenceIndicators": "مؤشرات التميز",
    "reportingDashboard": "لوحة التقارير",
    "tutorials": "الدروس التعليمية",
    "settings": "الإعدادات",
    "users": "المستخدمين",
    "support": "الدعم",
    "help": "المساعدة والدعم",
    "sidebarLabel": "القائمة الرئيسية"
  },
  "dashboard": {
    "alertMessages": {
      "negativeSentimentSpike": "تم اكتشاف ارتفاع في المشاعر السلبية لمؤسستك",
      "vipMention": "تم اكتشاف ذكر شخصية مهمة في وسائل التواصل الاجتماعي",
      "trendingKeyword": "كلمة مفتاحية جديدة شائعة متعلقة بعلامتك التجارية",
      "unusualActivity": "تم اكتشاف نشاط غير عادي على حسابات وسائل التواصل الاجتماعي الخاصة بك"
    },
    "connection_status": {
      "tooltip": {
        "title": "حالة الاتصال",
        "description": "يشير إلى حالة الاتصال بخادم ذكاء الإعلام شرطة عجمان.",
        "polling": "يتم تحديث البيانات كل {{seconds}} ثانية."
      }
    },
    "today": "اليوم",
    "last7Days": "آخر 7 أيام",
    "last30Days": "آخر 30 يوم",
    "last90Days": "آخر 90 يوم",
    "custom": "مخصص",
    "downloadReport": "تنزيل التقرير",
    "saveSuccess": "تم حفظ لوحة المعلومات",
    "media_mentions": {
      "title": "إشارات وسائل الإعلام",
      "allSources": "جميع المصادر",
      "newsSources": "مصادر الأخبار",
      "socialMedia": "وسائل التواصل الاجتماعي",
      "blogs": "المدونات",
      "otherSources": "مصادر أخرى",
      "news": "أخبار",
      "social": "اجتماعي",
      "blog": "مدونة",
      "other": "أخرى",
      "noMentionsData": "لا توجد بيانات إشارات متاحة",
      "noMentionsFound": "لم يتم العثور على إشارات للمعايير المحددة",
      "showingMentions": "عرض {{shown}} من {{total}} إشارة إجمالية",
      "sentimentLabel": "المشاعر: {{sentiment}}"
    },
    "saveSuccessDescription": "تم حفظ تفضيلات لوحة المعلومات الخاصة بك بنجاح",
    "saveFailed": "فشل في حفظ لوحة المعلومات",
    "title": "لوحة المعلومات",
    "saveChanges": "حفظ التغييرات",
    "cancel": "إلغاء",
    "customizeDashboard": "تخصيص لوحة المعلومات",
    "loading": "جاري تحميل لوحة المعلومات...",
    "viewAllKPIs": "عرض جميع مؤشرات الأداء",
    "mentions": "الإشارات",
    "mentionsTotal": "إجمالي الإشارات",
    "comparedTo": "مقارنة بـ",
    "inPreviousPeriod": "في الفترة السابقة",
    "marketShareIncrease": "زيادة الحصة السوقية على المنافسين",
    "analyticsOverview": "نظرة عامة على التحليلات",
    "realtimeSentimentTrends": "اتجاهات المشاعر في الوقت الفعلي",
    "trackSentimentChanges": "تتبع تغيرات المشاعر عبر المنصات على مر الزمن",
    "sentimentTrend": "اتجاه المشاعر",
    "sentimentTrendVisualization": "تصور اتجاهات المشاعر",
    "sentimentChartDescription": "رسم بياني يوضح نسب المشاعر الإيجابية والمحايدة والسلبية بمرور الوقت",
    "timePeriod": "الفترة الزمنية",
    "sentimentPercentage": "نسبة المشاعر",
    "loadingTrendData": "جاري تحميل بيانات الاتجاهات...",
    "noTrendDataAvailable": "لا تتوفر بيانات اتجاهات",
    "mentionsOverTime": "الإشارات بمرور الوقت",
    "shareOfVoice": "حصة الصوت",
    "widgetSettings": "إعدادات العنصر",
    "showOneItem": "عرض عنصر واحد",
    "showTwoItems": "عرض عنصرين",
    "showFourItems": "عرض أربعة عناصر",
    "expandedView": "عرض موسع",
    "compactView": "عرض مضغوط",
    "hideViewAllLink": "إخفاء رابط 'عرض الكل'",
    "showViewAllLink": "إظهار رابط 'عرض الكل'",
    "removeWidget": "إزالة العنصر",
    "themeExplorer": {
      "title": "مستكشف المواضيع التفاعلي",
      "description": "استخراج وتصور المواضيع الرئيسية مع مشاعرها العاطفية من أي محتوى.",
      "contentAnalysis": "محتوى لتحليل الموضوع",
      "fillSample": "ملء نموذج",
      "placeholder": "أدخل منشورات وسائل التواصل الاجتماعي أو المقالات الإخبارية أو أي نص لتحليله...",
      "analyzing": "جاري التحليل...",
      "extractThemes": "استخراج المواضيع",
      "extractedThemes": "المواضيع المستخرجة",
      "customThemes": "مواضيع مخصصة",
      "clear": "مسح",
      "occurrences": "التكرارات",
      "themeText": "نص الموضوع",
      "customThemePlaceholder": "أدخل موضوعًا مخصصًا...",
      "add": "إضافة",
      "sentiment": "المشاعر",
      "positive": "إيجابي",
      "neutral": "محايد",
      "negative": "سلبي",
      "yourCustomThemes": "المواضيع المخصصة الخاصة بك",
      "noThemesExtracted": "لم يتم استخراج أي مواضيع بعد. أدخل المحتوى وانقر فوق 'استخراج المواضيع' للتحليل.",
      "noContentToAnalyze": "لا يوجد محتوى للتحليل",
      "enterContentToExtract": "الرجاء إدخال بعض المحتوى لاستخراج المواضيع منه",
      "themesExtracted": "تم استخراج المواضيع",
      "themesExtractedMsg": "تم استخراج {{count}} موضوع من المحتوى الخاص بك",
      "noThemesFound": "لم يتم العثور على مواضيع",
      "noThemesFoundMsg": "لم نتمكن من استخراج أي مواضيع من هذا المحتوى",
      "errorExtractingThemes": "خطأ في استخراج المواضيع",
      "errorExtractingThemesMsg": "كانت هناك مشكلة في تحليل المحتوى الخاص بك",
      "themeTextRequired": "نص الموضوع مطلوب",
      "enterThemeText": "الرجاء إدخال نص للموضوع المخصص الخاص بك"
    },
    "widgets": {
      "unknownType": "نوع الأداة غير معروف",
      "errorRendering": "خطأ في عرض الأداة",
      "displayError": "تعذر عرض الأداة", 
      "errorMessage": "حدث خطأ ما في هذه الأداة",
      "settings": "إعدادات الأداة",
      "remove": "إزالة الأداة",
      "addWidgets": "إضافة أدوات",
      "sentimentAnalysis": {
        "title": "تحليل المشاعر",
        "positive": "إيجابي",
        "neutral": "محايد",
        "negative": "سلبي",
        "allEntities": "جميع الكيانات",
        "entityId": "معرف الكيان",
        "trendOverTime": "يعرض الرسم البياني الخطي الاتجاه على مدار الوقت",
        "overallSentiment": "الشعور العام هو بشكل رئيسي",
        "predominantlyPositive": "إيجابي",
        "predominantlyNegative": "سلبي",
        "predominantlyNeutral": "محايد",
        "timeRanges": {
          "day": "آخر 24 ساعة",
          "week": "آخر 7 أيام",
          "month": "آخر 30 يوماً",
          "quarter": "آخر 90 يوماً"
        },
        "weekdays": {
          "mon": "الإثنين",
          "tue": "الثلاثاء",
          "wed": "الأربعاء",
          "thu": "الخميس",
          "fri": "الجمعة",
          "sat": "السبت",
          "sun": "الأحد"
        }
      },
      "mediaMentions": "إشارات وسائل الإعلام",
      "keywordTrends": "اتجاهات الكلمات المفتاحية",
      "entityComparison": "مقارنة الكيانات",
      "socialMediaStats": "إحصائيات وسائل التواصل الاجتماعي",
      "recentReports": "التقارير الأخيرة",
      "kpiOverview": "نظرة عامة على مؤشرات الأداء",
      "customContent": "محتوى مخصص",
      "socialEngagement": "التفاعل الاجتماعي",
      "pressReleases": "البيانات الصحفية",
      "journalistDirectory": "دليل الصحفيين",
      "mediaSources": "مصادر الإعلام",
      "osintMonitoring": "مراقبة المصادر المفتوحة",
      "quickActions": "إجراءات سريعة",
      "socialMediaTrends": "اتجاهات وسائل التواصل الاجتماعي",
      "entityMentions": "إشارات الكيانات"
    },
    "kpi_overview": {
      "title": "نظرة عامة على مؤشرات الأداء",
      "description": "نظرة عامة على مؤشرات الأداء الرئيسية",
      "target": "الهدف"
    },
    "entity_comparison": {
      "title": "مقارنة الكيانات",
      "description": "مقارنة المؤشرات الرئيسية عبر مختلف الكيانات",
      "add_entity": "إضافة كيان",
      "remove_entity": "إزالة كيان",
      "select_metrics": "اختر المقاييس",
      "select_timeframe": "اختر الإطار الزمني",
      "comparing": "مقارنة {{count}} كيانات",
      "metric": "المقياس",
      "sentimentScore": "مقياس المشاعر",
      "totalMentions": "إجمالي الإشارات",
      "engagementRate": "معدل التفاعل",
      "value": "القيمة",
      "percentSymbol": "%",
      "noEntitiesSelected": "لم يتم اختيار أي كيانات للمقارنة",
      "highestSentiment": "{{name}} لديه أعلى مقياس للمشاعر عند {{score}}%",
      "mostMentions": "{{name}} لديه أكثر الإشارات عند {{count}}",
      "highestEngagement": "{{name}} لديه أعلى معدل تفاعل عند {{count}}"
    },
    "keyword_trends": {
      "title": "اتجاهات الكلمات المفتاحية",
      "description": "تتبع الكلمات المفتاحية الرائجة حسب الفئة والفترة الزمنية",
      "select_category": "اختر الفئة",
      "select_period": "اختر الفترة",
      "no_data": "لا توجد بيانات للكلمات المفتاحية متاحة للفترة المحددة",
      "mentions": "الإشارات",
      "trending_keywords": "الكلمات المفتاحية الرائجة",
      "volume": "الحجم"
    },
    "media_monitoring": {
      "title": "مراقبة وسائل الإعلام",
      "description": "مراقبة إشارات وسائل الإعلام عبر المنصات",
      "last_update": "آخر تحديث",
      "view_all": "عرض الكل",
      "by_type": "حسب النوع",
      "by_source": "حسب المصدر",
      "mentions": "الإشارات"
    },
    "news_feed": {
      "title": "موجز الأخبار",
      "description": "آخر الأخبار والتحديثات",
      "all_news": "كل الأخبار",
      "no_news": "لا توجد أخبار متاحة",
      "relevance": "الصلة",
      "read_more": "قراءة المزيد"
    },
    "recent_activity": {
      "title": "النشاط الأخير",
      "description": "أنشطة المنصة الأخيرة وإجراءات المستخدم",
      "no_activity": "لا يوجد نشاط حديث"
    },
    "sentiment_analysis": {
      "title": "تحليل المشاعر",
      "description": "تحليل المشاعر عبر مصادر الإعلام",
      "positive": "إيجابي",
      "neutral": "محايد",
      "negative": "سلبي",
      "overall": "المشاعر العامة",
      "line_chart": "مخطط خطي",
      "area_chart": "مخطط مساحي"
    },
    "social_media_activity": {
      "title": "نشاط وسائل التواصل الاجتماعي",
      "description": "نشاط وسائل التواصل الاجتماعي الأخير عبر المنصات",
      "posts": "المنشورات"
    }
  },
  "socialMedia": {
    "viewOriginalPost": "عرض المنشور الأصلي",
    "noPosts": "لا توجد منشورات متاحة",
    "connectedAccounts": "الحسابات المتصلة",
    "manageYourAccounts": "إدارة حسابات وسائل التواصل الاجتماعي",
    "manage": "إدارة",
    "connectNew": "ربط حساب جديد",
    "addAccount": "إضافة حساب جديد",
    "connect": "ربط",
    "createPost": "إنشاء منشور",
    "shareAcrossPlatforms": "شارك المحتوى عبر المنصات",
    "whatToShare": "ماذا تريد أن تشارك؟",
    "addImage": "إضافة صورة",
    "addVideo": "إضافة فيديو",
    "addDocument": "إضافة وثيقة",
    "mention": "إشارة",
    "hashtag": "هاشتاج",
    "schedule": "جدولة",
    "publishButton": "نشر",
    "schedulePost": "جدولة المنشور",
    "date": "التاريخ",
    "archive": "أرشفة",
    "flag": "تعليم",
    "user": "مستخدم",
    "defaultUsername": "مستخدم123"
  },
  "aiAssistant": {
    "title": "المساعد الذكي",
    "welcomeMessage": "مرحباً! أنا مساعدك الذكي لاستخبارات الإعلام. كيف يمكنني مساعدتك اليوم؟",
    "openAssistant": "فتح المساعد الذكي",
    "minimize": "تصغير",
    "maximize": "تكبير",
    "close": "إغلاق",
    "helpfulTips": "نصائح مفيدة",
    "dismissTip": "تجاهل النصيحة",
    "helpful": "مفيد",
    "notHelpful": "غير مفيد",
    "askPlaceholder": "اسألني أي شيء...",
    "sendMessage": "إرسال رسالة",
    "send": "إرسال",
    "feedbackReceived": "تم استلام التعليق",
    "positiveFeedbackThanks": "شكراً على تعليقك الإيجابي.",
    "negativeFeedbackThanks": "شكراً على تعليقك السلبي.",
    "errorResponse": "غير قادر على الحصول على استجابة. يرجى المحاولة مرة أخرى لاحقاً.",
    "errorMessage": "آسف، لم أتمكن من معالجة طلبك في الوقت الحالي. يرجى المحاولة مرة أخرى لاحقاً.",
    "defaultResponses": {
      "monitoring": "أفهم سؤالك حول مراقبة وسائل الإعلام. دعني أساعدك في التعرف على ميزات التحليلات لدينا.",
      "sentiment": "هذا سؤال رائع حول تحليل المشاعر. تستخدم منصتنا الذكاء الاصطناعي المتقدم لتتبع المشاعر عبر قنوات متعددة.",
      "entities": "أرى أنك مهتم بتتبع الكيانات. يمكنك إعداد تنبيهات لكيانات حكومية محددة باستخدام لوحة المعلومات.",
      "content": "لإدارة المحتوى، حاول استخدام أدوات الجدولة المدمجة لدينا لتخطيط استراتيجيتك الإعلامية.",
      "reports": "تتيح ميزات التقارير لدينا تصدير الرؤى بتنسيقات متعددة. هل ترغب في أن أريك كيف؟"
    }
  },
  "settings": {
    "title": "الإعدادات",
    "bioPlaceholder": "أخبرنا قليلاً عن نفسك",
    "keyNamePlaceholder": "أدخل اسم المفتاح",
    "webhookNamePlaceholder": "أدخل اسم الويب هوك",
    "langManagement": "إدارة اللغات",
    "langManagementDescription": "إضافة أو تعديل أو إزالة خيارات اللغة للمنصة",
    "availableLanguages": "اللغات المتاحة",
    "addLanguage": "إضافة لغة جديدة",
    "addLangTitle": "إضافة لغة جديدة",
    "addLangDescription": "املأ معلومات اللغة أدناه لإضافتها إلى المنصة.",
    "editLang": "تعديل اللغة",
    "editLangDescription": "تعديل معلومات اللغة أدناه.",
    "languageCode": "رمز اللغة",
    "langCodeExample": "ar",
    "langNameEnglish": "اسم اللغة (بالإنجليزية)",
    "langNameEnglishExample": "Arabic",
    "langNameNative": "اسم اللغة (باللغة الأصلية)",
    "langNameNativeExample": "العربية",
    "textDirection": "اتجاه النص",
    "rtl": "من اليمين إلى اليسار (RTL)",
    "ltr": "من اليسار إلى اليمين (LTR)",
    "activeStatus": "حالة التفعيل",
    "languageIsActive": "ستكون هذه اللغة متاحة للمستخدمين",
    "languageIsInactive": "سيتم إخفاء هذه اللغة عن المستخدمين",
    "cancel": "إلغاء",
    "update": "تحديث",
    "create": "إنشاء",
    "importLangFile": "استيراد ملف اللغة",
    "uploadLangFile": "تحميل ملف الترجمة",
    "langFileFormat": "مطلوب تنسيق JSON",
    "selectLanguage": "اختر اللغة",
    "selectFile": "اختر الملف",
    "fileUploadDescription": "قم بتحميل ملف ترجمة JSON. الحجم الأقصى: 2 ميجابايت.",
    "upload": "تحميل",
    "languageTableAriaLabel": "اللغات المتاحة",
    "languageTableCaption": "جدول اللغات المتاحة يعرض الاسم والرمز واكتمال الترجمة والاتجاه وأزرار الإجراءات",
    "languageSelector": "اللغة",
    "completeness": "اكتمال الترجمة",
    "actions": "الإجراءات",
    "defaultLang": "الافتراضية",
    "completenessValue": "اكتمال الترجمة: {{value}}%",
    "makeDefaultAriaLabel": "جعل {{language}} اللغة الافتراضية",
    "makeDefault": "تعيين كافتراضية",
    "editLanguageAriaLabel": "تعديل اللغة: {{language}}",
    "edit": "تعديل",
    "deleteLanguageAriaLabel": "حذف اللغة: {{language}}",
    "delete": "حذف",
    "deleteLanguage": "حذف اللغة",
    "deleteLanguageConfirmation": "هل أنت متأكد من رغبتك في حذف هذه اللغة؟ لا يمكن التراجع عن هذا الإجراء.",
    "currentLanguages": "اللغات الحالية",
    "translationUploaded": "تم تحميل ملف الترجمة",
    "webhookUrlPlaceholder": "https://example.com/webhook",
    "translationUploadSuccess": "تم تحميل ملف الترجمة بنجاح وستتم معالجته.",
    "uploadFailed": "فشل التحميل",
    "invalidJson": "ملف JSON غير صالح. يرجى تحميل ملف JSON صالح.",
    "languageAdded": "تمت إضافة اللغة",
    "languageAddSuccess": "تمت إضافة اللغة الجديدة بنجاح. يرجى تحميل ملفات الترجمة لإكمال الإعداد.",
    "languageUpdated": "تم تحديث اللغة",
    "languageUpdateSuccess": "تم تحديث اللغة بنجاح.",
    "languageStatusChanged": "تم تغيير حالة اللغة",
    "languageStatusChangeSuccess": "تم تحديث حالة تفعيل اللغة بنجاح.",
    "defaultLanguageChanged": "تم تغيير اللغة الافتراضية",
    "defaultLanguageChangeSuccess": "تم تحديث اللغة الافتراضية بنجاح.",
    "error": "خطأ"
  }
}