module.exports = {
  "testPages": {
    "connectionTest": {
      "title": "Connection Test Page",
      "description": "This is a minimal test page to verify connectivity",
      "testing": "Testing connection...",
      "error": "Error:",
      "refreshTest": "Refresh Test",
      "connectionSuccess": "API connection successful!"
    },
    "aiTest": {
      "title": "AI Assistant Test Page",
      "description": "This page demonstrates the AI Assistant functionality.",
      "platformTitle": "Media Intelligence Platform",
      "featuresTitle": "Features",
      "features": {
        "monitoring": "Comprehensive social media monitoring",
        "sentiment": "Sentiment analysis for UAE government entities",
        "analytics": "Advanced analytics and reporting",
        "alerts": "Real-time alerts for keywords and entities",
        "contentManagement": "Content management for media assets"
      },
      "assistantTip": "Click the AI Assistant button in the bottom right to ask questions about these features."
    },
    "sentimentTest": {
      "title": "OpenAI Sentiment Analysis Test"
    }
  },
  "auth": {
    "login": "Login",
    "logout": "Logout",
    "username": "Username",
    "password": "Password",
    "forgotPassword": "Forgot Password?",
    "rememberMe": "Remember Me",
    "loginButton": "Login",
    "loginTitle": "Sign in to your account",
    "loginDescription": "Welcome back! Enter your credentials to access the system.",
    "loginError": "Invalid username or password",
    "loginSuccess": "Login successful",
    "logoutSuccess": "Logout successful"
  },
  "notifications": {
    "title": "Notifications",
    "count": "{{count}} notifications",
    "keywordAlert": "New keyword alert detected",
    "negativeReaction": "Negative reaction on recent post",
    "newReport": "New weekly report available",
    "minutesAgo": "{{minutes}}m ago",
    "hoursAgo": "{{hours}}h ago",
    "daysAgo": "{{days}}d ago",
    "noNotifications": "No notifications",
    "markAllAsRead": "Mark all as read",
    "viewAll": "View all"
  },
  "app": {
    "title": "Ajman Police Media Intelligence",
    "description": "Comprehensive media monitoring and analytics"
  },
  "cookieTest": {
    "title": "HTTPS and Cookie Security Test",
    "tabs": {
      "manageCookies": "Manage Cookies",
      "debugInfo": "Debug Information"
    },
    "setCookie": {
      "title": "Set Cookie",
      "description": "Use this form to set a test cookie with secure flags",
      "cookieName": "Cookie Name",
      "cookieValue": "Cookie Value",
      "setButton": "Set Cookie",
      "clearButton": "Clear Cookie"
    },
    "currentCookies": {
      "title": "Current Cookies",
      "description": "These are the cookies currently available to the application",
      "noCookies": "No cookies found",
      "refreshButton": "Refresh Cookies"
    },
    "debug": {
      "title": "Debug Information",
      "description": "View HTTP/HTTPS details for your current connection",
      "loadButton": "Load Debug Info"
    },
    "status": {
      "success": "Success",
      "error": "Error"
    }
  },
  "dialog": {
    "demo": {
      "title": "Dialog Component Demo",
      "subtitle": "Showcasing various dialog implementations and patterns",
      "basic": {
        "title": "Basic Dialog",
        "description": "A simple dialog with title, description and actions.",
        "buttonText": "Open Basic Dialog",
        "dialogTitle": "Basic Dialog Example",
        "dialogDescription": "This is a simple dialog with title, description and actions.",
        "content": "Dialog content goes here. You can put any content inside a dialog.",
        "cancel": "Cancel",
        "save": "Save Changes"
      },
      "form": {
        "title": "Form Dialog",
        "description": "A dialog containing a form with validation.",
        "buttonText": "Open Form Dialog",
        "dialogTitle": "Edit Profile",
        "dialogDescription": "Make changes to your profile settings here.",
        "name": "Name",
        "namePlaceholder": "Enter your name",
        "email": "Email",
        "emailPlaceholder": "Enter your email",
        "notifications": "Enable notifications",
        "cancel": "Cancel",
        "save": "Save Changes",
        "submitted": "Form Submitted"
      },
      "custom": {
        "title": "Custom Dialog",
        "description": "A dialog with custom styling and animations.",
        "buttonText": "Open Custom Dialog",
        "dialogTitle": "Custom Dialog Example",
        "badge": "Custom Style",
        "content": "This dialog has a custom styled header and footer.",
        "note": "Note:",
        "noteContent": "You can customize any part of the dialog with regular CSS or Tailwind classes.",
        "cancel": "Cancel",
        "apply": "Apply Changes"
      },
      "success": {
        "title": "Success Dialog",
        "description": "A dialog that shows success confirmation.",
        "buttonText": "Open Success Dialog",
        "dialogTitle": "Success!",
        "dialogContent": "Your changes have been saved successfully.",
        "continue": "Continue"
      },
      "implementation": {
        "title": "Implementation Details",
        "description": "These dialogs use the useDialog hook and the enhanced Dialog component with proper focus management and accessibility attributes.",
        "code": {
          "trigger": "Open Dialog",
          "title": "Dialog Title",
          "description": "This is a dialog.",
          "content": "Content goes here",
          "cancel": "Cancel",
          "submit": "Submit"
        }
      }
    }
  },
  "common": {
    "cancel": "Cancel",
    "creating": "Creating...",
    "create": "Create",
    "loading": "Loading...",
    "error": "Error",
    "actions": "Actions",
    "edit": "Edit",
    "delete": "Delete",
    "deletingAction": "Deleting...",
    "deleteAction": "Delete",
    "processingRequest": "Processing request...",
    "deleting": "Deleting...",
    "save": "Save",
    "saving": "Saving...",
    "confirm": "Confirm",
    "close": "Close",
    "back": "Back",
    "next": "Next",
    "submit": "Submit",
    "search": "Search",
    "filter": "Filter",
    "refresh": "Refresh",
    "view": "View",
    "details": "Details",
    "more": "More",
    "less": "Less",
    "notFound": "Not Found",
    "noData": "No data available",
    "success": "Success",
    "warning": "Warning",
    "info": "Information",
    "language": "Language",
    "english": "English",
    "arabic": "Arabic",
    "theme": "Theme",
    "light": "Light",
    "dark": "Dark",
    "system": "System",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "admin": "Admin",
    "user": "User",
    "editor": "Editor",
    "userMenu": "User menu",
    "logout": "Logout",
    "login": "Login",
    "profile": "Profile",
    "minutes_ago": "{{count}} minutes ago",
    "minutes_ago_one": "1 minute ago",
    "hours_ago": "{{count}} hours ago",
    "hours_ago_one": "1 hour ago",
    "days_ago": "{{count}} days ago",
    "days_ago_one": "1 day ago",
    "connection_status": {
      "connected": "Connected",
      "disconnected": "Disconnected"
    }
  },
  "reports": {
    "textExportDesc": "Report exported as text successfully",
    "comingSoon": "Coming Soon", 
    "formatNotSupported": "This export format is not yet supported",
    "exportReady": "Export is ready",
    "preparingExport": "Preparing export",
    "exportFullReport": "Export Full Report",
    "preparingPrint": "Preparing print version",
    "viewingDetailedReport": "Viewing detailed report"
  },
  "media": {
    "type": {
      "image": "Image",
      "video": "Video",
      "document": "Document"
    },
    "mediaCenter": {
      "title": "Media Center",
      "viewAll": "View All",
      "image": "Image",
      "video": "Video"
    }
  },
  "excellence": {
    "title": "Institutional Excellence Indicators",
    "description": "Track and analyze KPIs for institutional excellence across strategic axes",
    "dateRange": "Date Range",
    "pickDates": "Select dates",
    "strategicAxis": "Strategic Axis",
    "allAxes": "All Axes",
    "communication": "Communication",
    "innovation": "Innovation",
    "smartTransformation": "Smart Transformation",
    "dataManagement": "Data Management",
    "mainIndicators": "Main Indicators",
    "subIndicators": "Sub-Indicators",
    "refresh": "Refresh Data",
    "exportCSV": "Export CSV",
    "exportPDF": "Export PDF",
    "exportExcel": "Export Excel",
    "exportFullReport": "Export Full Report",
    "exportOptions": "Export Options",
    "exportSuccess": "Export Successful",
    "exportError": "Export Error",
    "noDataToExport": "No data available to export",
    "reportExported": "Report has been exported successfully",
    "current": "Current Value",
    "target": "Target Value",
    "status": "Status",
    "progress": "Progress",
    "metricDetails": "Metric Details",
    "noData": "No data available for the selected period",
    "loadingData": "Loading indicators data...",
    "filterResults": "Filter Results",
    "applyFilters": "Apply Filters",
    "resetFilters": "Reset",
    "knowledgeScoreImproved": "Knowledge score improved by {{percent}}%",
    "innovationMetricsUpdated": "Innovation metrics updated",
    "pillarComparison": "Pillar Comparison",
    "digitalPillar": "Digital Pillar",
    "yearlyTrends": "Yearly Trends",
    "subindicatorsDistribution": "Subindicators Distribution",
    "excellent": "Excellent",
    "veryGood": "Very Good",
    "good": "Good",
    "average": "Average",
    "needsImprovement": "Needs Improvement",
    "subindicatorsCount": "Subindicators Count",
    "pillarContribution": "Pillar Contribution",
    "indicatorsDescription": "Comprehensive overview of the institutional excellence indicators across all pillars",
    "reportDescription": "Download the full excellence indicators report with detailed analysis and insights",
    "coverageVolume": "Media Coverage Volume",
    "positiveCoverageRate": "Positive Coverage Rate",
    "mediaSentimentIndex": "Media Sentiment Index",
    "socialEngagementRate": "Social Engagement Rate",
    "responseTime": "Response Time",
    "shareOfVoice": "Share of Voice",
    "implementedInnovations": "Implemented Innovations",
    "ideaImplementationRate": "Idea Implementation Rate",
    "employeeInnovationRate": "Employee Innovation Rate",
    "innovationAwards": "Innovation Awards",
    "operationalEfficiency": "Operational Efficiency",
    "innovationMediaCoverage": "Innovation Media Coverage",
    "digitalServicesPercent": "Digital Services Percentage",
    "digitalServicesAdoptionRate": "Digital Services Adoption Rate",
    "smartServicesUserSatisfaction": "Smart Services User Satisfaction",
    "internalProcessesAutomation": "Internal Processes Automation",
    "smartInitiativesImplemented": "Smart Initiatives Implemented",
    "knowledgeSharingSessions": "Knowledge Sharing Sessions",
    "avgTrainingHours": "Average Training Hours",
    "coreDataAccuracyRate": "Core Data Accuracy Rate",
    "statisticalReportsPublished": "Statistical Reports Published",
    "dataDrivenDecisionIndex": "Data-Driven Decision Index"
  },
  "entity": {
    "metrics": {
      "none": "None",
      "activePlatform": "Most Active Platform",
      "ofAllMentions": "of all mentions",
      "totalMentions": "Total Mentions",
      "avgSentiment": "Average Sentiment",
      "sentimentBreakdown": "Sentiment Breakdown"
    },
    "tabs": {
      "posts": "Posts",
      "trends": "Trends",
      "analytics": "Analytics"
    },
    "posts": {
      "noMentions": "No mentions found"
    },
    "trends": {
      "sentimentTrend": "Sentiment Trend",
      "sentimentOverTime": "Sentiment Over Time", 
      "sentimentScore": "Sentiment Score",
      "date": "Date",
      "notEnoughData": "Not enough data to display trends",
      "mentionsByPlatform": "Mentions by Platform",
      "distributionAcrossPlatforms": "Distribution Across Platforms",
      "noPlatformData": "No platform data available"
    },
    "analytics": {
      "sentimentAnalysis": "Sentiment Analysis",
      "breakdownDescription": "Sentiment breakdown across platforms",
      "numberOfMentions": "Number of Mentions",
      "noSentimentData": "No sentiment data available"
    },
    "error": {
      "invalidPost": "Invalid post data"
    },
    "post": {
      "author": "Author",
      "unknownAuthor": "Unknown Author",
      "unknownDate": "Unknown Date",
      "unknownPlatform": "Unknown Platform",
      "noContent": "No content available",
      "viewOriginal": "View Original"
    },
    "normalView": "Normal View",
    "debugView": "Debug View",
    "monitoring": "Government Entity Monitoring",
    "enableDebugMode": "Enable Debug Mode",
    "disableDebugMode": "Disable Debug Mode"
  },
  "calendar": {
    "title": "Calendar",
    "pickDate": "Pick a date",
    "today": "Today",
    "selected": "Selected",
    "previousMonth": "Previous month",
    "nextMonth": "Next month",
    "eventsForDate": "Events for {{date}}",
    "noEvents": "No events for this date",
    "addEvent": "Add event"
  },
  "users": {
    "languages": {
      "arabic": "Arabic",
      "english": "English"
    },
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "usersDirectory": "Users Directory",
    "manageAccounts": "Manage Accounts",
    "user": "User",
    "resetPassword": "Reset Password",
    "noUsersFound": "No users found",
    "confirmDelete": "Confirm Delete",
    "confirmDeleteDescription": "Are you sure you want to delete this user?",
    "deleteSuccess": "User deleted successfully",
    "userDeleted": "User has been deleted",
    "deleteError": "Error deleting user",
    "deleteErrorMessage": "Failed to delete user. Please try again."
  },
  "mediaCenter": {
    "image": "Image",
    "video": "Video",
    "document": "Document",
    "projects": "Projects",
    "events": "Events",
    "reports": "Reports",
    "news": "News",
    "weeks": "weeks",
    "days": "days",
    "title": "Media Center",
    "upload": "Upload",
    "uaeNewsSources": "UAE News Sources",
    "integratedPlatforms": "Integrated news platforms and official government sources",
    "sourcePlatforms": "Source Platforms",
    "ajmanGovPressReleases": "Ajman Government Press Releases",
    "ajmanPoliceNews": "Ajman Police News",
    "wamNewsAgency": "WAM News Agency",
    "ajmanGovDescription": "Access press releases, news, and official announcements from Ajman Government",
    "ajmanPoliceDescription": "Access security updates, community news, and safety information from Ajman Police",
    "wamDescription": "Access Emirates News Agency (WAM) for comprehensive UAE news coverage and updates",
    "browse": "Browse",
    "visitWebsite": "Visit Website",
    "visitOfficialWebsite": "Visit Official Website",
    "mediaDirectory": "Media Directory",
    "mediaDirectoryDesc": "Journalists directory, media sources, and press releases",
    "journalists": "Journalists",
    "mediaSources": "Media Sources",
    "pressReleases": "Press Releases",
    "noDate": "No date available"
  },
  "analysis": {
    "positive": "Positive",
    "neutral": "Neutral",
    "negative": "Negative",
    "positiveSentiment": "Positive Sentiment",
    "negativeSentiment": "Negative Sentiment",
    "sentimentImprovement": "Sentiment improvement from previous period",
    "sentimentDecrease": "Sentiment decrease from previous period",
    "sentimentDistribution": "Sentiment Distribution",
    "sentimentBreakdown": "Sentiment Breakdown",
    "sentimentFilters": "Sentiment Filters",
    "filterDescription": "Filter content by platform and sentiment"
  },
  "monitoring": {
    "title": "Content Monitoring",
    "mediaMonitoring": "Media Monitoring",
    "keywords": "Keywords",
    "keywordAlerts": "Keyword Alerts",
    "alertSettings": "Alert Settings",
    "addKeyword": "Add a keyword",
    "viewAlerts": "View Alerts",
    "searchMentions": "Search mentions",
    "clearAll": "Clear All",
    "downloadReport": "Download Report",
    "all": "All",
    "twitter": "Twitter",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "news": "News",
    "noResults": "No results found for your search",
    "noMentions": "No mentions found",
    "twitterContent": "Twitter content will appear here",
    "facebookContent": "Facebook content will appear here",
    "instagramContent": "Instagram content will appear here",
    "newsContent": "News content will appear here",
    "hoursAgo": "{{hours}}h ago",
    "defaultUser": "User",
    "defaultUsername": "username",
    "defaultAvatar": "https://randomuser.me/api/portraits/women/68.jpg",
    "testEmailSent": "Test Email Sent",
    "testEmailSentDesc": "The test email has been sent successfully.",
    "emailRequired": "Email address is required",
    "testEmailFailed": "Failed to send test email",
    "activeAlerts": "Active Alerts",
    "negativeRise": "Negative sentiment rise for Ajman Police content",
    "keywordTrends": "Trending keywords related to crime",
    "threshold": "Threshold",
    "mentions": "mentions",
    "testEmailNotifications": "Test Email Notifications",
    "testEmailDesc": "Send a test email to verify notification delivery",
    "enterEmail": "Enter your email address",
    "sendTest": "Send Test",
    "sources": "Sources",
    "newsWebsites": "News Websites",
    "blogs": "Blogs",
    "manageSourcesButton": "Manage Sources & Filters"
  },
  "navigation": {
    "dashboard": "Dashboard", 
    "personalizedDashboard": "Personalized Dashboard",
    "mediaCenter": "Media Center",
    "socialMediaManagement": "Social Media Management",
    "socialMedia": "Social Media",
    "socialPublishing": "Social Publishing",
    "monitoring": "Monitoring",
    "entityMonitoring": "Entity Monitoring",
    "reports": "Reports",
    "smartReports": "Smart Reports",
    "excellenceIndicators": "Excellence Indicators",
    "reportingDashboard": "Reporting Dashboard",
    "tutorials": "Tutorials",
    "settings": "Settings",
    "users": "Users",
    "support": "Support",
    "help": "Help & Support",
    "sidebarLabel": "Main Navigation"
  },
  "dashboard": {
    "alertMessages": {
      "negativeSentimentSpike": "Spike in negative sentiment detected for your organization",
      "vipMention": "VIP mention detected in social media",
      "trendingKeyword": "New trending keyword related to your brand",
      "unusualActivity": "Unusual activity detected on your social media accounts"
    },
    "connection_status": {
      "tooltip": {
        "title": "Connection Status",
        "description": "Indicates the connection status to the Ajman Police Media Intelligence server.",
        "polling": "Data is refreshed every {{seconds}} seconds."
      }
    },
    "today": "Today",
    "last7Days": "Last 7 Days",
    "last30Days": "Last 30 Days",
    "last90Days": "Last 90 Days",
    "custom": "Custom",
    "downloadReport": "Download Report",
    "saveSuccess": "Dashboard saved",
    "media_mentions": {
      "title": "Media Mentions",
      "allSources": "All Sources",
      "newsSources": "News Sources",
      "socialMedia": "Social Media",
      "blogs": "Blogs",
      "otherSources": "Other Sources",
      "news": "News",
      "social": "Social",
      "blog": "Blog",
      "other": "Other",
      "noMentionsData": "No mentions data available",
      "noMentionsFound": "No mentions found for the selected criteria",
      "showingMentions": "Showing {{shown}} of {{total}} total mentions",
      "sentimentLabel": "Sentiment: {{sentiment}}"
    },
    "saveSuccessDescription": "Your dashboard preferences have been saved successfully",
    "saveFailed": "Failed to save dashboard",
    "title": "Dashboard",
    "saveChanges": "Save Changes",
    "cancel": "Cancel",
    "customizeDashboard": "Customize Dashboard",
    "loading": "Loading dashboard...",
    "viewAllKPIs": "View All KPIs",
    "mentions": "Mentions",
    "mentionsTotal": "Total Mentions",
    "comparedTo": "compared to",
    "inPreviousPeriod": "in previous period",
    "marketShareIncrease": "Market share increase over competitors",
    "analyticsOverview": "Analytics Overview",
    "realtimeSentimentTrends": "Realtime Sentiment Trends",
    "trackSentimentChanges": "Track sentiment changes across platforms over time",
    "sentimentTrend": "Sentiment Trend",
    "sentimentTrendVisualization": "Sentiment trend visualization",
    "sentimentChartDescription": "Chart showing positive, neutral, and negative sentiment percentages over time",
    "timePeriod": "Time Period",
    "sentimentPercentage": "Sentiment Percentage",
    "loadingTrendData": "Loading trend data...",
    "noTrendDataAvailable": "No trend data available",
    "mentionsOverTime": "Mentions Over Time",
    "shareOfVoice": "Share of Voice", 
    "widgetSettings": "Widget Settings",
    "showOneItem": "Show 1 item",
    "showTwoItems": "Show 2 items",
    "showFourItems": "Show 4 items",
    "expandedView": "Expanded View",
    "compactView": "Compact View",
    "hideViewAllLink": "Hide 'View All' link",
    "showViewAllLink": "Show 'View All' link",
    "removeWidget": "Remove Widget",
    "themeExplorer": {
      "title": "Interactive Theme Explorer",
      "description": "Extract and visualize key themes with their emotional sentiment from any content.",
      "contentAnalysis": "Content for Theme Analysis",
      "fillSample": "Fill Sample",
      "placeholder": "Enter social media posts, news articles, or any text to analyze...",
      "analyzing": "Analyzing...",
      "extractThemes": "Extract Themes",
      "extractedThemes": "Extracted Themes",
      "customThemes": "Custom Themes",
      "clear": "Clear",
      "occurrences": "Occurrences",
      "themeText": "Theme Text",
      "customThemePlaceholder": "Enter a custom theme...",
      "add": "Add",
      "sentiment": "Sentiment",
      "positive": "Positive",
      "neutral": "Neutral",
      "negative": "Negative",
      "yourCustomThemes": "Your Custom Themes",
      "noThemesExtracted": "No themes extracted yet. Enter content and click 'Extract Themes' to analyze.",
      "noContentToAnalyze": "No content to analyze",
      "enterContentToExtract": "Please enter some content to extract themes from",
      "themesExtracted": "Themes extracted",
      "themesExtractedMsg": "{{count}} themes were extracted from your content",
      "noThemesFound": "No themes found",
      "noThemesFoundMsg": "We couldn't extract any themes from this content",
      "errorExtractingThemes": "Error extracting themes",
      "errorExtractingThemesMsg": "There was a problem analyzing your content",
      "themeTextRequired": "Theme text required",
      "enterThemeText": "Please enter text for your custom theme"
    },
    "widgets": {
      "unknownType": "Unknown widget type",
      "errorRendering": "Error rendering widget",
      "displayError": "Widget could not be displayed", 
      "errorMessage": "Something went wrong with this widget",
      "settings": "Widget Settings",
      "remove": "Remove Widget",
      "addWidgets": "Add Widgets",
      "sentimentAnalysis": {
        "title": "Sentiment Analysis",
        "positive": "Positive",
        "neutral": "Neutral",
        "negative": "Negative",
        "allEntities": "All Entities",
        "entityId": "Entity ID",
        "trendOverTime": "Line chart would display trend over time",
        "overallSentiment": "Overall sentiment is predominantly",
        "predominantlyPositive": "positive",
        "predominantlyNegative": "negative",
        "predominantlyNeutral": "neutral",
        "timeRanges": {
          "day": "Last 24 Hours",
          "week": "Last 7 Days",
          "month": "Last 30 Days",
          "quarter": "Last 90 Days"
        },
        "weekdays": {
          "mon": "Mon",
          "tue": "Tue",
          "wed": "Wed",
          "thu": "Thu",
          "fri": "Fri",
          "sat": "Sat",
          "sun": "Sun"
        }
      },
      "mediaMentions": "Media Mentions",
      "keywordTrends": "Keyword Trends",
      "entityComparison": "Entity Comparison",
      "socialMediaStats": "Social Media Stats",
      "recentReports": "Recent Reports",
      "kpiOverview": "KPI Overview",
      "customContent": "Custom Content",
      "socialEngagement": "Social Engagement",
      "pressReleases": "Press Releases",
      "journalistDirectory": "Journalist Directory",
      "mediaSources": "Media Sources",
      "osintMonitoring": "OSINT Monitoring",
      "quickActions": "Quick Actions",
      "socialMediaTrends": "Social Media Trends",
      "entityMentions": "Entity Mentions"
    },
    "kpi_overview": {
      "title": "KPI Overview",
      "description": "Key performance indicators overview",
      "target": "Target"
    },
    "entity_comparison": {
      "title": "Entity Comparison",
      "description": "Compare key metrics across different entities",
      "add_entity": "Add Entity",
      "remove_entity": "Remove Entity",
      "select_metrics": "Select Metrics",
      "select_timeframe": "Select Timeframe",
      "comparing": "Comparing {{count}} entities",
      "metric": "Metric",
      "sentimentScore": "Sentiment Score",
      "totalMentions": "Total Mentions",
      "engagementRate": "Engagement Rate",
      "value": "Value",
      "percentSymbol": "%",
      "noEntitiesSelected": "No entities selected for comparison",
      "highestSentiment": "{{name}} has the highest sentiment score at {{score}}%",
      "mostMentions": "{{name}} has the most mentions at {{count}}",
      "highestEngagement": "{{name}} has the highest engagement at {{count}}"
    },
    "keyword_trends": {
      "title": "Keyword Trends",
      "description": "Track trending keywords by category and time period",
      "select_category": "Select Category",
      "select_period": "Select Period",
      "no_data": "No keyword data available for the selected period",
      "mentions": "Mentions",
      "trending_keywords": "Trending Keywords",
      "volume": "Volume"
    },
    "media_monitoring": {
      "title": "Media Monitoring",
      "description": "Monitor media mentions across platforms",
      "last_update": "Last Update",
      "view_all": "View All",
      "by_type": "By Type",
      "by_source": "By Source",
      "mentions": "Mentions"
    },
    "news_feed": {
      "title": "News Feed",
      "description": "Latest news and updates",
      "all_news": "All News",
      "no_news": "No news available",
      "relevance": "Relevance",
      "read_more": "Read More"
    },
    "recent_activity": {
      "title": "Recent Activity",
      "description": "Recent platform activities and user actions",
      "no_activity": "No recent activity"
    },
    "sentiment_analysis": {
      "title": "Sentiment Analysis",
      "description": "Analysis of sentiment across media sources",
      "positive": "Positive",
      "neutral": "Neutral",
      "negative": "Negative",
      "overall": "Overall Sentiment",
      "line_chart": "Line Chart",
      "area_chart": "Area Chart"
    },
    "social_media_activity": {
      "title": "Social Media Activity",
      "description": "Recent social media activity across platforms",
      "posts": "Posts"
    }
  },
  "socialMedia": {
    "viewOriginalPost": "View Original Post",
    "noPosts": "No posts available",
    "connectedAccounts": "Connected Accounts",
    "manageYourAccounts": "Manage your social media accounts",
    "manage": "Manage",
    "connectNew": "Connect New Account",
    "addAccount": "Add a new social account",
    "connect": "Connect",
    "createPost": "Create Post",
    "shareAcrossPlatforms": "Share your content across platforms",
    "whatToShare": "What would you like to share?",
    "addImage": "Add Image",
    "addVideo": "Add Video",
    "addDocument": "Add Document",
    "mention": "Mention",
    "hashtag": "Hashtag",
    "schedule": "Schedule",
    "publishButton": "Publish",
    "schedulePost": "Schedule Post",
    "date": "Date",
    "archive": "Archive",
    "flag": "Flag",
    "user": "User",
    "defaultUsername": "user123"
  },
  "aiAssistant": {
    "title": "AI Assistant",
    "welcomeMessage": "Hello! I'm your media intelligence assistant. How can I help you today?",
    "openAssistant": "Open AI Assistant",
    "minimize": "Minimize",
    "maximize": "Maximize",
    "close": "Close",
    "helpfulTips": "Helpful Tips",
    "dismissTip": "Dismiss tip",
    "helpful": "Helpful",
    "notHelpful": "Not helpful",
    "askPlaceholder": "Ask me anything...",
    "sendMessage": "Send message",
    "send": "Send",
    "feedbackReceived": "Feedback Received",
    "positiveFeedbackThanks": "Thank you for your positive feedback.",
    "negativeFeedbackThanks": "Thank you for your negative feedback.",
    "errorResponse": "Unable to get a response. Please try again later.",
    "errorMessage": "I'm sorry, I couldn't process your request at the moment. Please try again later.",
    "defaultResponses": {
      "monitoring": "I understand your question about media monitoring. Let me help guide you through our analytics features.",
      "sentiment": "That's a great question about sentiment analysis. Our platform uses advanced AI to track sentiment across multiple channels.",
      "entities": "I see you're interested in entity tracking. You can set up alerts for specific government entities using the dashboard.",
      "content": "For content management, try using our built-in scheduling tools to plan your media strategy.",
      "reports": "Our reporting features allow you to export insights in multiple formats. Would you like me to show you how?"
    }
  },
  "settings": {
    "title": "Settings",
    "bioPlaceholder": "Tell us a bit about yourself",
    "keyNamePlaceholder": "Enter key name",
    "webhookNamePlaceholder": "Enter webhook name",
    "langManagement": "Language Management",
    "langManagementDescription": "Add, edit or remove language options for the platform",
    "availableLanguages": "Available Languages",
    "addLanguage": "Add New Language",
    "addLangTitle": "Add New Language",
    "addLangDescription": "Fill in the language information below to add it to the platform.",
    "editLang": "Edit Language",
    "editLangDescription": "Edit the language information below.",
    "languageCode": "Language Code",
    "langCodeExample": "en",
    "langNameEnglish": "Language Name (English)",
    "langNameEnglishExample": "English",
    "langNameNative": "Language Name (Native)",
    "langNameNativeExample": "English",
    "textDirection": "Text Direction",
    "rtl": "Right to Left (RTL)",
    "ltr": "Left to Right (LTR)",
    "activeStatus": "Active Status",
    "languageIsActive": "This language will be available for users",
    "languageIsInactive": "This language will be hidden from users",
    "cancel": "Cancel",
    "update": "Update",
    "create": "Create",
    "importLangFile": "Import Language File",
    "uploadLangFile": "Upload Translation File",
    "langFileFormat": "JSON format required",
    "selectLanguage": "Select Language",
    "selectFile": "Select File",
    "fileUploadDescription": "Upload a JSON translation file. Maximum size: 2MB.",
    "upload": "Upload",
    "languageTableAriaLabel": "Available languages",
    "languageTableCaption": "Table of available languages showing name, code, completeness, direction and action buttons",
    "languageSelector": "Language",
    "completeness": "Completeness",
    "actions": "Actions",
    "defaultLang": "Default",
    "completenessValue": "Translation completeness: {{value}}%",
    "makeDefaultAriaLabel": "Make {{language}} the default language",
    "makeDefault": "Make Default",
    "editLanguageAriaLabel": "Edit language: {{language}}",
    "edit": "Edit",
    "deleteLanguageAriaLabel": "Delete language: {{language}}",
    "delete": "Delete",
    "deleteLanguage": "Delete Language",
    "deleteLanguageConfirmation": "Are you sure you want to delete this language? This action cannot be undone.",
    "currentLanguages": "Current Languages",
    "translationUploaded": "Translation file uploaded",
    "webhookUrlPlaceholder": "https://example.com/webhook",
    "translationUploadSuccess": "The translation file was successfully uploaded and will be processed.",
    "uploadFailed": "Upload failed",
    "invalidJson": "Invalid JSON file. Please upload a valid JSON file.",
    "languageAdded": "Language added",
    "languageAddSuccess": "The new language was successfully added. Please upload translation files to complete the setup.",
    "languageUpdated": "Language updated",
    "languageUpdateSuccess": "The language was successfully updated.",
    "languageStatusChanged": "Language status changed",
    "languageStatusChangeSuccess": "The language active status was updated successfully.",
    "defaultLanguageChanged": "Default language changed",
    "defaultLanguageChangeSuccess": "The default language was updated successfully.",
    "error": "Error"
  }
}