// Comprehensive Arabic translations for Ajman Police Media Intelligence Platform

const arTranslations = {
  "testPages": {
    "connectionTest": {
      "title": "صفحة اختبار الاتصال",
      "description": "هذه صفحة اختبار بسيطة للتحقق من الاتصال",
      "testing": "جاري اختبار الاتصال...",
      "error": "خطأ:",
      "refreshTest": "تحديث الاختبار",
      "connectionSuccess": "تم الاتصال بنجاح!"
    },
    "testPage": {
      "title": "صفحة اختبار ميزات النظام",
      "description": "هذه الصفحة تعرض وظائف المنصة الأساسية.",
      "platformTitle": "منصة ذكاء وسائل الإعلام",
      "featuresTitle": "الميزات",
      "features": {
        "monitoring": "مراقبة شاملة لوسائل التواصل الاجتماعي",
        "sentiment": "تحليل المشاعر لهيئات الحكومة الإماراتية",
        "analytics": "تحليلات متقدمة وإعداد التقارير",
        "alerts": "تنبيهات فورية للكلمات الرئيسية والكيانات",
        "contentManagement": "إدارة المحتوى للأصول الإعلامية"
      }
    },
    "sentimentTest": {
      "title": "اختبار تحليل المشاعر"
    }
  },
  "auth": {
    "login": "تسجيل الدخول",
    "logout": "تسجيل الخروج",
    "username": "اسم المستخدم",
    "password": "كلمة المرور",
    "forgotPassword": "نسيت كلمة المرور؟",
    "rememberMe": "تذكرني",
    "loginButton": "تسجيل الدخول",
    "loginTitle": "تسجيل الدخول إلى حسابك",
    "loginDescription": "مرحبًا بعودتك! أدخل بيانات اعتمادك للوصول إلى النظام.",
    "loginError": "اسم المستخدم أو كلمة المرور غير صحيحة",
    "loginSuccess": "تم تسجيل الدخول بنجاح",
    "logoutSuccess": "تم تسجيل الخروج بنجاح"
  },
  "notifications": {
    "title": "الإشعارات",
    "count": "{{count}} إشعارات",
    "keywordAlert": "تم اكتشاف تنبيه كلمة رئيسية جديدة",
    "negativeReaction": "رد فعل سلبي على المنشور الأخير",
    "newReport": "تقرير أسبوعي جديد متاح",
    "minutesAgo": "منذ {{minutes}} دقيقة",
    "hoursAgo": "منذ {{hours}} ساعة",
    "daysAgo": "منذ {{days}} يوم",
    "noNotifications": "لا توجد إشعارات",
    "markAllAsRead": "تحديد الكل كمقروء",
    "viewAll": "عرض الكل"
  },
  "app": {
    "title": "ذكاء وسائل الإعلام لشرطة عجمان",
    "description": "مراقبة وتحليل شامل لوسائل الإعلام"
  },
  "cookieTest": {
    "title": "اختبار HTTPS وأمان ملفات تعريف الارتباط",
    "tabs": {
      "manageCookies": "إدارة ملفات تعريف الارتباط",
      "debugInfo": "معلومات التصحيح"
    },
    "setCookie": {
      "title": "تعيين ملف تعريف ارتباط",
      "description": "استخدم هذا النموذج لتعيين ملف تعريف ارتباط اختباري بعلامات آمنة",
      "cookieName": "اسم ملف تعريف الارتباط",
      "cookieValue": "قيمة ملف تعريف الارتباط",
      "setButton": "تعيين ملف تعريف الارتباط",
      "clearButton": "مسح ملف تعريف الارتباط"
    },
    "currentCookies": {
      "title": "ملفات تعريف الارتباط الحالية",
      "description": "هذه هي ملفات تعريف الارتباط المتاحة حاليًا للتطبيق",
      "noCookies": "لم يتم العثور على ملفات تعريف ارتباط",
      "refreshButton": "تحديث ملفات تعريف الارتباط"
    },
    "debug": {
      "title": "معلومات التصحيح",
      "description": "عرض تفاصيل HTTP/HTTPS لاتصالك الحالي",
      "loadButton": "تحميل معلومات التصحيح"
    },
    "status": {
      "success": "نجاح",
      "error": "خطأ"
    }
  },
  "dialog": {
    "demo": {
      "title": "عرض توضيحي لمكون الحوار",
      "subtitle": "عرض تطبيقات وأنماط الحوار المختلفة",
      "basic": {
        "title": "حوار أساسي",
        "description": "حوار بسيط مع عنوان ووصف وإجراءات.",
        "buttonText": "فتح الحوار الأساسي",
        "dialogTitle": "مثال على الحوار الأساسي",
        "dialogDescription": "هذا حوار بسيط مع عنوان ووصف وإجراءات.",
        "content": "محتوى الحوار يذهب هنا. يمكنك وضع أي محتوى داخل الحوار.",
        "cancel": "إلغاء",
        "save": "حفظ التغييرات"
      },
      "form": {
        "title": "حوار النموذج",
        "description": "حوار يحتوي على نموذج مع التحقق من الصحة.",
        "buttonText": "فتح حوار النموذج",
        "dialogTitle": "تعديل الملف الشخصي",
        "dialogDescription": "قم بإجراء تغييرات على إعدادات ملفك الشخصي هنا.",
        "name": "الاسم",
        "namePlaceholder": "أدخل اسمك",
        "email": "البريد الإلكتروني",
        "emailPlaceholder": "أدخل بريدك الإلكتروني",
        "notifications": "تمكين الإشعارات",
        "cancel": "إلغاء",
        "save": "حفظ التغييرات",
        "submitted": "تم إرسال النموذج"
      },
      "custom": {
        "title": "حوار مخصص",
        "description": "حوار بتنسيق وحركات مخصصة.",
        "buttonText": "فتح الحوار المخصص",
        "dialogTitle": "مثال على الحوار المخصص",
        "badge": "نمط مخصص",
        "content": "هذا الحوار له رأس وتذييل بنمط مخصص.",
        "note": "ملاحظة:",
        "noteContent": "يمكنك تخصيص أي جزء من الحوار باستخدام CSS العادي أو فئات Tailwind.",
        "cancel": "إلغاء",
        "apply": "تطبيق التغييرات"
      },
      "success": {
        "title": "حوار النجاح",
        "description": "حوار يعرض تأكيد النجاح.",
        "buttonText": "فتح حوار النجاح",
        "dialogTitle": "نجاح!",
        "dialogContent": "تم حفظ التغييرات بنجاح.",
        "continue": "استمرار"
      },
      "implementation": {
        "title": "تفاصيل التنفيذ",
        "description": "تستخدم هذه الحوارات خطاف useDialog ومكون Dialog المحسن مع إدارة التركيز المناسبة وسمات إمكانية الوصول.",
        "code": {
          "trigger": "فتح الحوار",
          "title": "عنوان الحوار",
          "description": "هذا حوار.",
          "content": "المحتوى يذهب هنا",
          "cancel": "إلغاء",
          "submit": "إرسال"
        }
      }
    }
  },
  "common": {
    "cancel": "إلغاء",
    "creating": "جاري الإنشاء...",
    "create": "إنشاء",
    "loading": "جاري التحميل...",
    "error": "خطأ",
    "actions": "إجراءات",
    "edit": "تعديل",
    "delete": "حذف",
    "deletingAction": "جاري الحذف...",
    "deleteAction": "حذف",
    "processingRequest": "جاري معالجة الطلب...",
    "deleting": "جاري الحذف...",
    "save": "حفظ",
    "saving": "جاري الحفظ...",
    "confirm": "تأكيد",
    "close": "إغلاق",
    "back": "رجوع",
    "next": "التالي",
    "submit": "إرسال",
    "search": "بحث",
    "filter": "تصفية",
    "refresh": "تحديث",
    "view": "عرض",
    "details": "التفاصيل",
    "more": "المزيد",
    "less": "أقل",
    "notFound": "غير موجود",
    "noData": "لا توجد بيانات متاحة",
    "success": "نجاح",
    "warning": "تحذير",
    "info": "معلومات",
    "language": "اللغة",
    "english": "الإنجليزية",
    "arabic": "العربية",
    "theme": "المظهر",
    "light": "فاتح",
    "dark": "داكن",
    "system": "النظام",
    "high": "عالي",
    "medium": "متوسط",
    "low": "منخفض",
    "admin": "مدير",
    "user": "مستخدم",
    "editor": "محرر",
    "userMenu": "قائمة المستخدم",
    "logout": "تسجيل الخروج",
    "login": "تسجيل الدخول",
    "profile": "الملف الشخصي",
    "minutes_ago": "منذ {{count}} دقيقة",
    "minutes_ago_one": "منذ دقيقة واحدة",
    "hours_ago": "منذ {{count}} ساعة",
    "hours_ago_one": "منذ ساعة واحدة",
    "days_ago": "منذ {{count}} يوم",
    "days_ago_one": "منذ يوم واحد",
    "connection_status": {
      "connected": "متصل",
      "disconnected": "غير متصل"
    }
  },
  "reports": {
    "textExportDesc": "تم تصدير التقرير كنص بنجاح",
    "comingSoon": "قريبًا", 
    "formatNotSupported": "هذا التنسيق للتصدير غير مدعوم حاليًا",
    "exportReady": "التصدير جاهز",
    "preparingExport": "جاري تحضير التصدير",
    "exportFullReport": "تصدير التقرير الكامل",
    "preparingPrint": "جاري تحضير نسخة للطباعة",
    "viewingDetailedReport": "عرض تقرير مفصل"
  },
  "media": {
    "type": {
      "image": "صورة",
      "video": "فيديو",
      "document": "مستند"
    },
    "mediaCenter": {
      "title": "المركز الإعلامي",
      "viewAll": "عرض الكل",
      "image": "صورة",
      "video": "فيديو"
    }
  },
  "excellence": {
    "title": "مؤشرات التميز المؤسسي",
    "description": "تتبع وتحليل مؤشرات الأداء الرئيسية للتميز المؤسسي عبر المحاور الاستراتيجية",
    "dateRange": "النطاق الزمني",
    "pickDates": "اختر التواريخ",
    "strategicAxis": "المحور الاستراتيجي",
    "allAxes": "جميع المحاور",
    "communication": "التواصل",
    "innovation": "الابتكار",
    "smartTransformation": "التحول الذكي",
    "dataManagement": "إدارة البيانات",
    "mainIndicators": "المؤشرات الرئيسية",
    "subIndicators": "المؤشرات الفرعية",
    "refresh": "تحديث البيانات",
    "exportCSV": "تصدير CSV",
    "exportPDF": "تصدير PDF",
    "exportExcel": "تصدير Excel",
    "exportFullReport": "تصدير التقرير الكامل",
    "exportOptions": "خيارات التصدير",
    "exportSuccess": "تم التصدير بنجاح",
    "exportError": "خطأ في التصدير",
    "noDataToExport": "لا توجد بيانات متاحة للتصدير",
    "reportExported": "تم تصدير التقرير بنجاح",
    "current": "القيمة الحالية",
    "target": "القيمة المستهدفة",
    "status": "الحالة",
    "progress": "التقدم",
    "metricDetails": "تفاصيل المقياس",
    "noData": "لا توجد بيانات متاحة للفترة المحددة",
    "loadingData": "جاري تحميل بيانات المؤشرات...",
    "filterResults": "تصفية النتائج",
    "applyFilters": "تطبيق التصفية",
    "resetFilters": "إعادة تعيين",
    "knowledgeScoreImproved": "تحسنت درجة المعرفة بنسبة {{percent}}%",
    "innovationMetricsUpdated": "تم تحديث مقاييس الابتكار",
    "pillarComparison": "مقارنة الركائز",
    "digitalPillar": "الركيزة الرقمية",
    "yearlyTrends": "اتجاهات سنوية",
    "subindicatorsDistribution": "توزيع المؤشرات الفرعية",
    "excellent": "ممتاز",
    "veryGood": "جيد جدًا",
    "good": "جيد",
    "average": "متوسط",
    "needsImprovement": "يحتاج إلى تحسين",
    "subindicatorsCount": "عدد المؤشرات الفرعية",
    "pillarContribution": "مساهمة الركيزة",
    "indicatorsDescription": "نظرة شاملة على مؤشرات التميز المؤسسي عبر جميع الركائز",
    "reportDescription": "تنزيل تقرير مؤشرات التميز الكامل مع تحليل ورؤى مفصلة",
    "coverageVolume": "حجم التغطية الإعلامية",
    "positiveCoverageRate": "معدل التغطية الإيجابية",
    "mediaSentimentIndex": "مؤشر المشاعر الإعلامية",
    "socialEngagementRate": "معدل التفاعل الاجتماعي",
    "responseTime": "وقت الاستجابة",
    "shareOfVoice": "حصة الصوت",
    "implementedInnovations": "الابتكارات المنفذة",
    "ideaImplementationRate": "معدل تنفيذ الأفكار",
    "employeeInnovationRate": "معدل ابتكار الموظفين",
    "innovationAwards": "جوائز الابتكار",
    "operationalEfficiency": "الكفاءة التشغيلية",
    "innovationMediaCoverage": "التغطية الإعلامية للابتكار",
    "digitalServicesPercent": "نسبة الخدمات الرقمية",
    "digitalServicesAdoptionRate": "معدل تبني الخدمات الرقمية",
    "smartServicesUserSatisfaction": "رضا المستخدم عن الخدمات الذكية",
    "internalProcessesAutomation": "أتمتة العمليات الداخلية",
    "smartInitiativesImplemented": "المبادرات الذكية المنفذة",
    "knowledgeSharingSessions": "جلسات مشاركة المعرفة",
    "avgTrainingHours": "متوسط ساعات التدريب",
    "coreDataAccuracyRate": "معدل دقة البيانات الأساسية",
    "statisticalReportsPublished": "التقارير الإحصائية المنشورة",
    "dataDrivenDecisionIndex": "مؤشر القرارات المستندة إلى البيانات"
  },
  "entity": {
    "metrics": {
      "none": "لا شيء",
      "activePlatform": "المنصة الأكثر نشاطًا",
      "ofAllMentions": "من جميع الإشارات",
      "totalMentions": "إجمالي الإشارات",
      "avgSentiment": "متوسط المشاعر",
      "sentimentBreakdown": "تفصيل المشاعر"
    },
    "tabs": {
      "posts": "المنشورات",
      "trends": "الاتجاهات",
      "analytics": "التحليلات"
    },
    "posts": {
      "noMentions": "لم يتم العثور على إشارات"
    },
    "trends": {
      "sentimentTrend": "اتجاه المشاعر",
      "sentimentOverTime": "المشاعر على مر الزمن", 
      "sentimentScore": "درجة المشاعر",
      "date": "التاريخ",
      "notEnoughData": "لا توجد بيانات كافية لعرض الاتجاهات",
      "mentionsByPlatform": "الإشارات حسب المنصة",
      "distributionAcrossPlatforms": "التوزيع عبر المنصات",
      "noPlatformData": "لا توجد بيانات منصة متاحة"
    },
    "analytics": {
      "sentimentAnalysis": "تحليل المشاعر",
      "breakdownDescription": "تفصيل المشاعر عبر المنصات",
      "numberOfMentions": "عدد الإشارات",
      "noSentimentData": "لا توجد بيانات مشاعر متاحة"
    },
    "error": {
      "invalidPost": "بيانات المنشور غير صالحة"
    },
    "post": {
      "author": "المؤلف",
      "unknownAuthor": "مؤلف غير معروف",
      "unknownDate": "تاريخ غير معروف",
      "unknownPlatform": "منصة غير معروفة",
      "noContent": "لا يوجد محتوى متاح",
      "viewOriginal": "عرض الأصلي"
    },
    "normalView": "العرض العادي",
    "debugView": "عرض التصحيح",
    "monitoring": "مراقبة الهيئات الحكومية",
    "enableDebugMode": "تمكين وضع التصحيح",
    "disableDebugMode": "تعطيل وضع التصحيح"
  },
  "calendar": {
    "title": "التقويم",
    "pickDate": "اختر تاريخًا",
    "today": "اليوم",
    "selected": "محدد",
    "previousMonth": "الشهر السابق",
    "nextMonth": "الشهر التالي",
    "eventsForDate": "أحداث {{date}}",
    "noEvents": "لا توجد أحداث لهذا التاريخ",
    "addEvent": "إضافة حدث"
  },
  "users": {
    "languages": {
      "arabic": "العربية",
      "english": "الإنجليزية"
    },
    "password": "كلمة المرور",
    "confirmPassword": "تأكيد كلمة المرور",
    "usersDirectory": "دليل المستخدمين",
    "manageAccounts": "إدارة الحسابات",
    "user": "المستخدم",
    "resetPassword": "إعادة تعيين كلمة المرور",
    "noUsersFound": "لم يتم العثور على مستخدمين",
    "confirmDelete": "تأكيد الحذف",
    "confirmDeleteDescription": "هل أنت متأكد من أنك تريد حذف هذا المستخدم؟",
    "deleteSuccess": "تم حذف المستخدم بنجاح",
    "userDeleted": "تم حذف المستخدم",
    "deleteError": "خطأ في حذف المستخدم",
    "deleteErrorMessage": "فشل حذف المستخدم. يرجى المحاولة مرة أخرى."
  },
  "mediaCenter": {
    "image": "صورة",
    "video": "فيديو",
    "document": "مستند",
    "projects": "المشاريع",
    "events": "الأحداث",
    "reports": "التقارير",
    "news": "الأخبار",
    "weeks": "أسابيع",
    "days": "أيام",
    "title": "المركز الإعلامي",
    "upload": "رفع",
    "uaeNewsSources": "مصادر أخبار الإمارات",
    "integratedPlatforms": "منصات إخبارية متكاملة ومصادر حكومية رسمية",
    "sourcePlatforms": "منصات المصدر",
    "ajmanGovPressReleases": "البيانات الصحفية لحكومة عجمان",
    "ajmanPoliceNews": "أخبار شرطة عجمان",
    "wamNewsAgency": "وكالة أنباء الإمارات (وام)",
    "ajmanGovDescription": "الوصول إلى البيانات الصحفية والأخبار والإعلانات الرسمية من حكومة عجمان",
    "ajmanPoliceDescription": "الوصول إلى تحديثات الأمن وأخبار المجتمع ومعلومات السلامة من شرطة عجمان",
    "wamDescription": "الوصول إلى وكالة أنباء الإمارات (وام) للحصول على تغطية شاملة لأخبار الإمارات والتحديثات",
    "browse": "تصفح",
    "visitWebsite": "زيارة الموقع",
    "visitOfficialWebsite": "زيارة الموقع الرسمي",
    "mediaDirectory": "دليل وسائل الإعلام",
    "mediaDirectoryDesc": "دليل الصحفيين، ومصادر وسائل الإعلام، والبيانات الصحفية",
    "journalists": "الصحفيون",
    "mediaSources": "مصادر وسائل الإعلام",
    "pressReleases": "البيانات الصحفية",
    "noDate": "لا يوجد تاريخ متاح"
  },
  "analysis": {
    "positive": "إيجابي",
    "neutral": "محايد",
    "negative": "سلبي",
    "positiveSentiment": "المشاعر الإيجابية",
    "negativeSentiment": "المشاعر السلبية",
    "sentimentImprovement": "تحسن المشاعر من الفترة السابقة",
    "sentimentDecrease": "انخفاض المشاعر من الفترة السابقة",
    "sentimentDistribution": "توزيع المشاعر",
    "sentimentBreakdown": "تفصيل المشاعر",
    "sentimentFilters": "تصفية المشاعر",
    "filterDescription": "تصفية المحتوى حسب المنصة والمشاعر"
  },
  "monitoring": {
    "title": "مراقبة المحتوى",
    "mediaMonitoring": "مراقبة وسائل الإعلام",
    "keywords": "الكلمات الرئيسية",
    "keywordList": "قائمة الكلمات الرئيسية",
    "entityMonitoring": "مراقبة الكيانات",
    "setupAlerts": "إعداد التنبيهات",
    "alertHistory": "سجل التنبيهات",
    "alertSettings": "إعدادات التنبيهات",
    "addKeyword": "إضافة كلمة رئيسية",
    "categoryFilter": "تصفية الفئة",
    "platformSelector": "محدد المنصة",
    "contentFilter": "تصفية المحتوى",
    "dateRange": "النطاق الزمني",
    "filter": "تصفية",
    "reset": "إعادة تعيين",
    "saveSearch": "حفظ البحث",
    "exportResults": "تصدير النتائج",
    "showHistory": "عرض السجل",
    "savedSearches": "عمليات البحث المحفوظة",
    "manageSavedSearches": "إدارة عمليات البحث المحفوظة",
    "noSavedSearches": "لم يتم العثور على عمليات بحث محفوظة",
    "confirmDelete": "تأكيد الحذف",
    "deleteSearchConfirm": "هل أنت متأكد من أنك تريد حذف عملية البحث المحفوظة هذه؟",
    "keywordAlerts": "تنبيهات الكلمات الرئيسية",
    "entityAlerts": "تنبيهات الكيانات",
    "alertFrequency": "تكرار التنبيه",
    "alertChannel": "قناة التنبيه",
    "alertThreshold": "حد التنبيه",
    "createAlert": "إنشاء تنبيه",
    "updateAlert": "تحديث التنبيه",
    "deleteAlert": "حذف التنبيه",
    "confirmDeleteAlert": "هل أنت متأكد من أنك تريد حذف هذا التنبيه؟",
    "noAlerts": "لم يتم العثور على تنبيهات",
    "alertTypes": {
      "keyword": "تنبيه الكلمات الرئيسية",
      "entity": "تنبيه الكيانات",
      "sentiment": "تنبيه المشاعر",
      "mention": "تنبيه الإشارة"
    },
    "frequencies": {
      "realtime": "في الوقت الحقيقي",
      "hourly": "كل ساعة",
      "daily": "يوميًا",
      "weekly": "أسبوعيًا"
    },
    "channels": {
      "dashboard": "لوحة التحكم",
      "email": "البريد الإلكتروني",
      "sms": "الرسائل القصيرة"
    },
    "thresholds": {
      "all": "جميع المطابقات",
      "high": "الأولوية العالية فقط",
      "critical": "الحرجة فقط"
    }
  },
  "navigation": {
    "dashboard": "لوحة التحكم",
    "personalizedDashboard": "لوحة التحكم الشخصية",
    "mediaCenter": "المركز الإعلامي",
    "socialMediaManagement": "إدارة وسائل التواصل الاجتماعي",
    "socialMedia": "وسائل التواصل الاجتماعي",
    "socialPublishing": "النشر الاجتماعي",
    "monitoring": "المراقبة",
    "entityMonitoring": "مراقبة الكيانات",
    "reports": "التقارير",
    "smartReports": "التقارير الذكية",
    "excellenceIndicators": "مؤشرات التميز",
    "reportingDashboard": "لوحة تحكم التقارير",
    "tutorials": "البرامج التعليمية",
    "settings": "الإعدادات",
    "users": "المستخدمين",
    "support": "الدعم",
    "help": "المساعدة والدعم",
    "sidebarLabel": "القائمة الرئيسية"
  },
  "settings": {
    "title": "الإعدادات",
    "appearance": "المظهر",
    "language": "اللغة",
    "theme": "السمة",
    "notifications": "الإشعارات",
    "account": "الحساب",
    "security": "الأمان",
    "api": "واجهة برمجة التطبيقات",
    "integrations": "التكاملات",
    "general": "الإعدادات العامة",
    "preferences": "التفضيلات",
    "colorMode": "وضع الألوان",
    "fontPreferences": "تفضيلات الخط",
    "interfaceDensity": "كثافة الواجهة",
    "animations": "الرسوم المتحركة",
    "enableAnimations": "تمكين الرسوم المتحركة",
    "notificationPreferences": "تفضيلات الإشعارات",
    "emailNotifications": "إشعارات البريد الإلكتروني",
    "appNotifications": "إشعارات التطبيق",
    "notifyForAlerts": "التنبيه للتنبيهات",
    "notifyForReports": "التنبيه للتقارير الجديدة",
    "notifyForSystemUpdates": "التنبيه لتحديثات النظام",
    "notifyForMentions": "التنبيه للإشارات",
    "accountInformation": "معلومات الحساب",
    "changePassword": "تغيير كلمة المرور",
    "twoFactorAuthentication": "المصادقة الثنائية",
    "enableTwoFactor": "تمكين المصادقة الثنائية",
    "apiKeys": "مفاتيح واجهة برمجة التطبيقات",
    "generateNewKey": "إنشاء مفتاح واجهة برمجة تطبيقات جديد",
    "regenerateKey": "إعادة إنشاء المفتاح",
    "copyKey": "نسخ المفتاح",
    "deleteKey": "حذف المفتاح",
    "noApiKeysFound": "لم يتم العثور على مفاتيح واجهة برمجة تطبيقات",
    "availableIntegrations": "التكاملات المتاحة",
    "connectedIntegrations": "التكاملات المتصلة",
    "connect": "اتصال",
    "disconnect": "قطع الاتصال",
    "connectService": "الاتصال بـ {{service}}",
    "disconnectService": "قطع الاتصال بـ {{service}}",
    "saveChanges": "حفظ التغييرات",
    "cancelChanges": "إلغاء التغييرات",
    "resetToDefaults": "إعادة التعيين إلى الافتراضي",
    "defaultLanguage": "اللغة الافتراضية",
    "defaultLanguageChange": "تغيير اللغة الافتراضية",
    "defaultLanguageChangeMessage": "سيتم تغيير اللغة الافتراضية إلى {{language}}. سيرى مستخدمو المنصة الذين لم يحددوا تفضيل اللغة الخاص بهم هذه اللغة بشكل افتراضي.",
    "defaultLanguageChangeButton": "تغيير اللغة الافتراضية",
    "defaultLanguageChangeSuccess": "تم تحديث اللغة الافتراضية بنجاح.",
    "error": "خطأ"
  },
  "supportCenter": {
    "title": "مركز المساعدة والدعم",
    "subtitle": "ابحث عن الإجابات والموارد والدعم لأسئلتك",
    "tabs": {
      "overview": "نظرة عامة",
      "resources": "الموارد",
      "help": "الحصول على المساعدة"
    },
    "faq": {
      "title": "الأسئلة الشائعة",
      "description": "إجابات سريعة للأسئلة الشائعة",
      "content": "تصفح الأسئلة الشائعة للحصول على إجابات للأسئلة الشائعة حول ميزات المنصة واستخدامها واستكشاف الأخطاء وإصلاحها.",
      "browseButton": "تصفح الأسئلة الشائعة"
    },
    "knowledgeBase": {
      "title": "قاعدة المعرفة",
      "description": "أدلة ومقالات مفصلة",
      "content": "ابحث عن مقالات وأدلة متعمقة حول استخدام المنصة وأفضل الممارسات والميزات المتقدمة.",
      "browseButton": "تصفح قاعدة المعرفة"
    },
    "supportTickets": {
      "title": "تذاكر الدعم",
      "description": "احصل على مساعدة شخصية من فريقنا",
      "content": "قم بإنشاء تذاكر دعم للحصول على مساعدة مباشرة من فريقنا. تتبع حالة تذاكرك.",
      "browseButton": "عرض التذاكر"
    },
    "getHelp": {
      "title": "هل تحتاج إلى مزيد من المساعدة؟",
      "description": "فريق الدعم لدينا موجود لمساعدتك في أي مشكلات أو أسئلة",
      "createTicketButton": "إنشاء تذكرة دعم",
      "tutorialsButton": "مشاهدة البرامج التعليمية"
    },
    "resources": {
      "title": "موارد التعلم",
      "description": "استكشف مواد التعلم الشاملة لدينا",
      "documentation": "الوثائق",
      "documentationDescription": "وثائق تقنية مفصلة لميزات المنصة وواجهات برمجة التطبيقات",
      "documentationButton": "عرض الوثائق",
      "guides": "أدلة المستخدم",
      "guidesDescription": "أدلة خطوة بخطوة لمساعدتك على استخدام ميزات المنصة بفعالية",
      "guidesButton": "عرض الأدلة",
      "tutorials": "فيديوهات تعليمية",
      "tutorialsDescription": "شاهد الفيديوهات التعليمية لتتعلم كيفية استخدام المنصة",
      "tutorialsButton": "مشاهدة الفيديوهات التعليمية"
    },
    "help": {
      "title": "الحصول على دعم مباشر",
      "description": "اتصل بفريق الدعم لدينا للحصول على مساعدة شخصية",
      "content": "إذا لم تتمكن من العثور على الإجابات في قاعدة المعرفة أو البرامج التعليمية، قم بإنشاء تذكرة دعم للحصول على مساعدة مباشرة.",
      "createTicketButton": "إنشاء تذكرة دعم",
      "faqButton": "تحقق من الأسئلة الشائعة أولاً"
    },
    "yourTickets": {
      "title": "تذاكر الدعم الخاصة بك",
      "description": "عرض وإدارة تذاكر الدعم الحالية",
      "viewButton": "عرض تذاكرك"
    },
    "contactUs": {
      "title": "اتصل بنا",
      "description": "تواصل مع فريق الدعم لدينا مباشرة",
      "content": "هل لديك سؤال أو تحتاج إلى مساعدة؟ اتصل بفريق الدعم لدينا مباشرة من خلال نموذج الاتصال.",
      "button": "اتصل بنا"
    }
  },
  "faq": {
    "title": "الأسئلة الشائعة",
    "subtitle": "ابحث عن إجابات سريعة للأسئلة الشائعة حول استخدام المنصة",
    "backToSupport": "العودة إلى الدعم",
    "searchPlaceholder": "البحث في الأسئلة...",
    "categoryFilterPlaceholder": "تصفية حسب الفئة",
    "allCategories": "جميع الفئات",
    "frequentlyAskedQuestions": "الأسئلة المتكررة",
    "frequentlyAskedQuestionsDescription": "تصفح أسئلتنا الشائعة للعثور على إجابات سريعة",
    "filteredResults": "{{count}} نتيجة",
    "filteredDescription": "عرض الأسئلة المصفاة بناءً على بحثك",
    "errorLoading": "خطأ في تحميل الأسئلة الشائعة. يرجى المحاولة مرة أخرى.",
    "noResultsFound": "لم يتم العثور على أسئلة شائعة تطابق معايير البحث الخاصة بك.",
    "clearFilters": "مسح التصفية",
    "needMoreHelp": {
      "title": "هل لا تزال لديك أسئلة؟",
      "description": "إذا لم تتمكن من العثور على ما كنت تبحث عنه، فنحن هنا للمساعدة",
      "createTicket": "إنشاء تذكرة دعم",
      "browseKnowledgeBase": "تصفح قاعدة المعرفة"
    }
  },
  "contextHints": {
    "language_context_hints": "تلميحات السياق اللغوي",
    "ai_powered_language_improvement_tool": "أداة مدعومة بالذكاء الاصطناعي لتحسين جودة اللغة",
    "context_hint_generator": "مولد تلميحات السياق",
    "enter_text_for_language_analysis": "أدخل النص لتلقي اقتراحات تحسين اللغة",
    "analyzing_text": "جاري تحليل النص",
    "generating_language_hints": "جاري إنشاء تلميحات السياق اللغوي...",
    "no_hints_available": "لا توجد تلميحات لغوية متاحة",
    "no_suggestions_found": "لم يتم العثور على اقتراحات لهذا النص",
    "minimum_text_required": "أدخل 5 أحرف على الأقل للتحليل",
    "analyze_text": "تحليل النص",
    "analyzing": "جاري التحليل...",
    "select_language": "اختر اللغة",
    "enter_text_here": "أدخل النص هنا...",
    "copied": "تم النسخ",
    "text_copied_to_clipboard": "تم نسخ النص إلى الحافظة",
    "applied": "تم التطبيق",
    "suggestion_applied": "تم تطبيق الاقتراح على النص",
    "original_text": "النص الأصلي",
    "suggested_replacement": "الاستبدال المقترح",
    "explanation": "التفسير",
    "source": "المصدر",
    "confidence": "الثقة",
    "copy": "نسخ",
    "apply": "تطبيق",
    "expand": "توسيع",
    "collapse": "طي",
    "view_details": "عرض تفاصيل الاقتراح",
    "collapse_details": "إخفاء تفاصيل الاقتراح",
    "powered_by_ai": "مدعوم بواسطة Anthropic Claude و OpenAI",
    "about_context_hints": "حول تلميحات السياق",
    "how_context_hints_work": "كيف تعمل اقتراحات اللغة بالذكاء الاصطناعي",
    "context_hints_description": "يستخدم مولد تلميحات السياق اللغوي الذكاء الاصطناعي المتقدم لتحسين جودة الكتابة. يحلل النص لتحديد مشكلات القواعد، وتحسينات الوضوح، وتعديلات النبرة، والحساسيات الثقافية، وتصحيحات الرسمية.",
    "supported_hint_types": "أنواع التلميحات المدعومة",
    "grammar": "القواعد",
    "grammar_description": "تصحيحات للإملاء وعلامات الترقيم والأخطاء النحوية",
    "clarity": "الوضوح",
    "clarity_description": "اقتراحات لجعل النص أكثر وضوحًا وسهولة في الفهم",
    "tone": "النبرة",
    "tone_description": "تعديلات لتحسين النبرة والتأثير العاطفي",
    "cultural": "الثقافي",
    "cultural_description": "اعتبارات للصلة الثقافية والحساسية",
    "formality": "الرسمية",
    "formality_description": "تعديلات لتتناسب مع المستوى المناسب من الرسمية",
    "suggestion": "اقتراح",
    "suggestions": "اقتراحات",
    "example_texts": "نصوص مثالية",
    "try_with_these_examples": "جرب تحليل هذه الأمثلة"
  },
  "socialMedia": {
    "title": "إدارة منصات التواصل الاجتماعي",
    "dashboard": "لوحة التحكم",
    "accounts": "الحسابات الرسمية",
    "publish": "نشر المحتوى",
    "analytics": "التحليلات",
    "realTimeUpdates": "تحديثات المراقبة المباشرة",
    "offlineMode": "وضع عدم الاتصال",
    "posts": "منشورات",
    "engagement": "التفاعل",
    "reach": "الوصول",
    "connectedPlatforms": "المنصات الرسمية لشرطة عجمان",
    "engagementOverview": "نظرة عامة على التفاعل",
    "lastThirtyDays": "آخر 30 يوم",
    "trendingTopics": "المواضيع الشائعة",
    "realTimeMonitoring": "مراقبة المواضيع والهاشتاجات الشائعة",
    "audienceDemographics": "البيانات الديموغرافية للجمهور",
    "sentimentAnalysis": "تحليل المشاعر",
    "selectTimeframe": "اختر الإطار الزمني",
    "timeframe": {
      "day": "يوم",
      "week": "أسبوع",
      "month": "شهر",
      "quarter": "ربع سنة"
    },
    "sentimentTrend": "اتجاه المشاعر",
    "sentimentTrendDescription": "تحليل تطور المشاعر العامة مع مرور الوقت",
    "currentSentiment": "المشاعر الحالية",
    "sentiment": {
      "positive": "إيجابي",
      "neutral": "محايد",
      "negative": "سلبي"
    },
    "recentPosts": "أحدث المنشورات",
    "noPosts": "لا توجد منشورات متاحة",
    "connectedAccounts": "الحسابات المتصلة",
    "manageYourAccounts": "إدارة حسابات شرطة عجمان على وسائل التواصل الاجتماعي",
    "connected": "متصل",
    "manage": "إدارة",
    "connectNew": "ربط حساب جديد",
    "addAccount": "إضافة حساب وسائل التواصل الاجتماعي الرسمي",
    "connect": "ربط",
    "createPost": "إنشاء منشور",
    "shareAcrossPlatforms": "شارك المحتوى عبر منصات التواصل الاجتماعي",
    "whatToShare": "ماذا تريد أن تشارك؟",
    "addImage": "إضافة صورة",
    "addVideo": "إضافة فيديو",
    "addDocument": "إضافة مستند",
    "mention": "إشارة",
    "hashtag": "هاشتاج",
    "schedule": "جدولة",
    "publishButton": "نشر",
    "scheduledPosts": "المنشورات المجدولة",
    "noScheduledPosts": "لا توجد منشورات مجدولة",
    "scheduleMessage": "جدولة منشوراتك لتنشر تلقائيًا في أوقات محددة",
    "detailedAnalytics": "التحليلات التفصيلية",
    "performanceInsights": "رؤى الأداء لحسابات شرطة عجمان",
    "totalEngagement": "إجمالي التفاعل",
    "topPerformingPosts": "أفضل المنشورات أداءً",
    "audienceGrowth": "نمو الجمهور",
    "followers": "المتابعون",
    "likes": "الإعجابات",
    "comments": "التعليقات",
    "shares": "المشاركات",
    "osintMonitoring": "مراقبة المعلومات المفتوحة المصدر",
    "contentArchive": "أرشيف المحتوى",
    "archiveDescription": "أرشيف البحث عن المحتوى والحسابات ذات الصلة",
    "searchKeywords": "كلمات البحث",
    "searchAccounts": "البحث عن الحسابات",
    "saveToArchive": "حفظ في الأرشيف",
    "archivedContent": "المحتوى المؤرشف",
    "threatLevel": "مستوى التهديد",
    "relevanceScore": "درجة الصلة",
    "informationValue": "قيمة المعلومات",
    "actionNeeded": "إجراء مطلوب",
    "monitorOnly": "مراقبة فقط",
    "escalate": "تصعيد",
    "investigate": "تحقيق",
    "monitorHash": "مراقبة هاشتاج",
    "keywordAlert": "تنبيه الكلمات الرئيسية",
    "addFlaggedAccount": "إضافة حساب محدد",
    "exportOsintReport": "تصدير تقرير OSINT",
    "flaggedAccounts": "الحسابات المحددة",
    "flaggedContent": "المحتوى المحدد",
    "searchHistory": "سجل البحث",
    "savedSearches": "عمليات البحث المحفوظة"
  },
  "performance": {
    "title": "عرض الأداء",
    "description": "تحليل بصري لأداء المنصات الإعلامية والتواجد الرقمي",
    "pageDescription": "عرض مؤشرات الأداء الرئيسية وتحليل المشاعر وإحصاءات التفاعل",
    "cardDescription": "الوصول إلى لوحة التحكم المتقدمة للتصور مع رسوم بيانية تفاعلية ومقاييس الأداء",
    "timeRange": "النطاق الزمني",
    "oneMonth": "شهر واحد",
    "threeMonths": "3 أشهر",
    "sixMonths": "6 أشهر",
    "oneYear": "سنة",
    "export": "تصدير",
    "dataUpdated": "تم تحديث البيانات",
    "dataUpdateSuccess": "تم تحديث جميع بيانات الأداء بنجاح.",
    "dataUpdateError": "خطأ في تحديث البيانات",
    "dataUpdateErrorDescription": "حدث خطأ أثناء تحديث بيانات الأداء. يرجى المحاولة مرة أخرى.",
    "overviewTab": "نظرة عامة",
    "sentimentTab": "التحليل العاطفي",
    "engagementTab": "التفاعل",
    "performanceTab": "أداء المؤسسة",
    "change": "التغيير",
    "mediaVisibility": "الظهور الإعلامي",
    "mediaVisibilityTrend": "تطور معدل الظهور عبر المنصات الإعلامية خلال",
    "mediaVisibilityIndex": "مؤشر الظهور",
    "updatedEvery": "تحديث كل",
    "hours": "ساعات",
    "hour": "ساعة",
    "engagementByPlatform": "التفاعل حسب المنصة",
    "engagementCount": "عدد التفاعلات على مختلف المنصات الاجتماعية",
    "engagement": "التفاعل",
    "totalEngagement": "إجمالي التفاعل",
    "sentimentDistribution": "توزيع المشاعر",
    "sentimentAnalysis": "تحليل المشاعر السائدة في المحتوى الرقمي",
    "sentimentTrends": "تطور المشاعر",
    "sentimentOverTime": "تغير المشاعر مع مرور الوقت",
    "positive": "إيجابي",
    "neutral": "محايد",
    "negative": "سلبي",
    "positiveChange": "تغير في المشاعر الإيجابية",
    "detailedEngagement": "تحليل التفاعل المفصل",
    "dataShownFor": "هذه البيانات تعرض خلال",
    "loading": "جاري تحميل بيانات الأداء المؤسسي...",
    "keyPerformanceIndicators": "مؤشرات الأداء الرئيسية",
    "measurePerformance": "قياس أداء المؤسسة مقارنة بالأهداف الاستراتيجية",
    "filterResults": "تصفية النتائج",
    "target": "الهدف",
    "dataUpdatedOn": "تم تحديث البيانات في"
  }
};

export default arTranslations;