// Arabic translations
export const arTranslations = {
  app: {
    title: 'ذكاء الإعلام - شرطة عجمان',
  },
  calendar: {
    title: 'التقويم',
    pickDate: 'اختر تاريخًا',
    today: 'اليوم',
    selected: 'محدد',
    previousMonth: 'الشهر السابق',
    nextMonth: 'الشهر التالي',
    eventsForDate: 'الأحداث في {{date}}',
    noEvents: 'لا توجد أحداث لهذا التاريخ',
    addEvent: 'إضافة حدث',
    eventTypes: {
      default: 'حدث',
      important: 'مهم',
      reminder: 'تذكير'
    }
  },
  clock: {
    title: 'الساعة',
    currentTime: 'الوقت الحالي',
    timeZone: 'المنطقة الزمنية'
  },
  connection: {
    connected: 'متصل',
    connecting: 'جاري الاتصال',
    disconnected: 'غير متصل',
    error: 'خطأ في الاتصال',
    reconnect: 'إعادة الاتصال',
    connected_tooltip: 'التحديثات المباشرة نشطة',
    connecting_tooltip: 'جاري إنشاء الاتصال...',
    disconnected_tooltip: 'التحديثات المباشرة غير متوفرة',
    error_tooltip: 'تعذر الاتصال بالخادم',
    click_to_reconnect: 'انقر لإعادة الاتصال',
  },
  // Social Media Management for Ajman Police
  socialMedia: {
    title: 'إدارة منصات التواصل الاجتماعي',
    dashboard: 'لوحة التحكم',
    accounts: 'الحسابات الرسمية',
    publish: 'نشر المحتوى',
    analytics: 'التحليلات',
    realTimeUpdates: 'تحديثات المراقبة المباشرة',
    offlineMode: 'وضع عدم الاتصال',
    posts: 'منشورات',
    engagement: 'التفاعل',
    reach: 'الوصول',
    connectedPlatforms: 'المنصات الرسمية لشرطة عجمان',
    engagementOverview: 'نظرة عامة على التفاعل',
    lastThirtyDays: 'آخر 30 يوم',
    trendingTopics: 'المواضيع الشائعة',
    realTimeMonitoring: 'مراقبة المواضيع والهاشتاجات الشائعة',
    audienceDemographics: 'البيانات الديموغرافية للجمهور',
    sentimentAnalysis: 'تحليل المشاعر',
    selectTimeframe: 'اختر الإطار الزمني',
    timeframe: {
      day: 'يوم',
      week: 'أسبوع',
      month: 'شهر',
      quarter: 'ربع سنة'
    },
    sentimentTrend: 'اتجاه المشاعر',
    sentimentTrendDescription: 'تحليل تطور المشاعر العامة مع مرور الوقت',
    currentSentiment: 'المشاعر الحالية',
    sentiment: {
      positive: 'إيجابي',
      neutral: 'محايد',
      negative: 'سلبي'
    },
    recentPosts: 'أحدث المنشورات',
    noPosts: 'لا توجد منشورات متاحة',
    connectedAccounts: 'الحسابات المتصلة',
    manageYourAccounts: 'إدارة حسابات شرطة عجمان على وسائل التواصل الاجتماعي',
    connected: 'متصل',
    manage: 'إدارة',
    connectNew: 'ربط حساب جديد',
    addAccount: 'إضافة حساب وسائل التواصل الاجتماعي الرسمي',
    connect: 'ربط',
    createPost: 'إنشاء منشور',
    shareAcrossPlatforms: 'شارك المحتوى عبر منصات التواصل الاجتماعي',
    whatToShare: 'ماذا تريد أن تشارك؟',
    addImage: 'إضافة صورة',
    addVideo: 'إضافة فيديو',
    addDocument: 'إضافة مستند',
    mention: 'إشارة',
    hashtag: 'هاشتاج',
    schedule: 'جدولة',
    publishButton: 'نشر',
    scheduledPosts: 'المنشورات المجدولة',
    noScheduledPosts: 'لا توجد منشورات مجدولة',
    scheduleMessage: 'جدولة منشوراتك لتنشر تلقائيًا في أوقات محددة',
    detailedAnalytics: 'التحليلات التفصيلية',
    performanceInsights: 'رؤى الأداء لحسابات شرطة عجمان',
    totalEngagement: 'إجمالي التفاعل',
    topPerformingPosts: 'أفضل المنشورات أداءً',
    audienceGrowth: 'نمو الجمهور',
    followers: 'المتابعون',
    likes: 'الإعجابات',
    comments: 'التعليقات',
    shares: 'المشاركات',
    // OSINT related translations
    osintMonitoring: 'مراقبة المعلومات المفتوحة المصدر',
    contentArchive: 'أرشيف المحتوى',
    archiveDescription: 'أرشيف البحث عن المحتوى والحسابات ذات الصلة',
    searchKeywords: 'كلمات البحث',
    searchAccounts: 'البحث عن الحسابات',
    saveToArchive: 'حفظ في الأرشيف',
    archivedContent: 'المحتوى المؤرشف',
    threatLevel: 'مستوى التهديد',
    relevanceScore: 'درجة الصلة',
    informationValue: 'قيمة المعلومات',
    actionNeeded: 'إجراء مطلوب',
    monitorOnly: 'مراقبة فقط',
    escalate: 'تصعيد',
    investigate: 'تحقيق',
    monitorHash: 'مراقبة هاشتاج',
    keywordAlert: 'تنبيه الكلمات الرئيسية',
    addFlaggedAccount: 'إضافة حساب محدد',
    exportOsintReport: 'تصدير تقرير OSINT',
    flaggedAccounts: 'الحسابات المحددة',
    flaggedContent: 'المحتوى المحدد',
    searchHistory: 'سجل البحث',
    savedSearches: 'عمليات البحث المحفوظة',
  },
  
  // Context Hints System translations
  contextHints: {
    language_context_hints: 'تلميحات السياق اللغوي',
    ai_powered_language_improvement_tool: 'أداة مدعومة بالذكاء الاصطناعي لتحسين جودة اللغة',
    context_hint_generator: 'مولد تلميحات السياق',
    enter_text_for_language_analysis: 'أدخل النص لتلقي اقتراحات تحسين اللغة',
    analyzing_text: 'جاري تحليل النص',
    generating_language_hints: 'جاري إنشاء تلميحات السياق اللغوي...',
    no_hints_available: 'لا توجد تلميحات لغوية متاحة',
    no_suggestions_found: 'لم يتم العثور على اقتراحات لهذا النص',
    minimum_text_required: 'أدخل 5 أحرف على الأقل للتحليل',
    analyze_text: 'تحليل النص',
    analyzing: 'جاري التحليل...',
    select_language: 'اختر اللغة',
    enter_text_here: 'أدخل النص هنا...',
    copied: 'تم النسخ',
    text_copied_to_clipboard: 'تم نسخ النص إلى الحافظة',
    applied: 'تم التطبيق',
    suggestion_applied: 'تم تطبيق الاقتراح على النص',
    original_text: 'النص الأصلي',
    suggested_replacement: 'الاستبدال المقترح',
    explanation: 'التفسير',
    source: 'المصدر',
    confidence: 'الثقة',
    copy: 'نسخ',
    apply: 'تطبيق',
    expand: 'توسيع',
    collapse: 'طي',
    view_details: 'عرض تفاصيل الاقتراح',
    collapse_details: 'إخفاء تفاصيل الاقتراح',
    powered_by_ai: 'مدعوم بواسطة Anthropic Claude و OpenAI',
    about_context_hints: 'حول تلميحات السياق',
    how_context_hints_work: 'كيف تعمل اقتراحات اللغة بالذكاء الاصطناعي',
    context_hints_description: 'يستخدم مولد تلميحات السياق اللغوي الذكاء الاصطناعي المتقدم لتحسين جودة الكتابة. يحلل النص لتحديد مشكلات القواعد، وتحسينات الوضوح، وتعديلات النبرة، والحساسيات الثقافية، وتصحيحات الرسمية.',
    supported_hint_types: 'أنواع التلميحات المدعومة',
    grammar: 'القواعد',
    grammar_description: 'تصحيحات للإملاء وعلامات الترقيم والأخطاء النحوية',
    clarity: 'الوضوح',
    clarity_description: 'اقتراحات لجعل النص أكثر وضوحًا وسهولة في الفهم',
    tone: 'النبرة',
    tone_description: 'تعديلات لتحسين النبرة والتأثير العاطفي',
    cultural: 'الثقافي',
    cultural_description: 'اعتبارات للصلة الثقافية والحساسية',
    formality: 'الرسمية',
    formality_description: 'تعديلات لتتناسب مع المستوى المناسب من الرسمية',
    suggestion: 'اقتراح',
    suggestions: 'اقتراحات',
    example_texts: 'نصوص مثالية',
    try_with_these_examples: 'جرب تحليل هذه الأمثلة',
  },
  performance: {
    title: 'عرض الأداء',
    description: 'تحليل بصري لأداء المنصات الإعلامية والتواجد الرقمي',
    pageDescription: 'عرض مؤشرات الأداء الرئيسية وتحليل المشاعر وإحصاءات التفاعل',
    cardDescription: 'الوصول إلى لوحة التحكم المتقدمة للتصور مع رسوم بيانية تفاعلية ومقاييس الأداء',
    timeRange: 'النطاق الزمني',
    oneMonth: 'شهر واحد',
    threeMonths: '3 أشهر',
    sixMonths: '6 أشهر',
    oneYear: 'سنة',
    export: 'تصدير',
    dataUpdated: 'تم تحديث البيانات',
    dataUpdateSuccess: 'تم تحديث جميع بيانات الأداء بنجاح.',
    dataUpdateError: 'خطأ في تحديث البيانات',
    dataUpdateErrorDescription: 'حدث خطأ أثناء تحديث بيانات الأداء. يرجى المحاولة مرة أخرى.',
    overviewTab: 'نظرة عامة',
    sentimentTab: 'التحليل العاطفي',
    engagementTab: 'التفاعل',
    performanceTab: 'أداء المؤسسة',
    change: 'التغيير',
    mediaVisibility: 'الظهور الإعلامي',
    mediaVisibilityTrend: 'تطور معدل الظهور عبر المنصات الإعلامية خلال',
    mediaVisibilityIndex: 'مؤشر الظهور',
    updatedEvery: 'تحديث كل',
    hours: 'ساعات',
    hour: 'ساعة',
    engagementByPlatform: 'التفاعل حسب المنصة',
    engagementCount: 'عدد التفاعلات على مختلف المنصات الاجتماعية',
    engagement: 'التفاعل',
    totalEngagement: 'إجمالي التفاعل',
    sentimentDistribution: 'توزيع المشاعر',
    sentimentAnalysis: 'تحليل المشاعر السائدة في المحتوى الرقمي',
    sentimentTrends: 'تطور المشاعر',
    sentimentOverTime: 'تغير المشاعر مع مرور الوقت',
    positive: 'إيجابي',
    neutral: 'محايد',
    negative: 'سلبي',
    positiveChange: 'تغير في المشاعر الإيجابية',
    detailedEngagement: 'تحليل التفاعل المفصل',
    dataShownFor: 'هذه البيانات تعرض خلال',
    loading: 'جاري تحميل بيانات الأداء المؤسسي...',
    keyPerformanceIndicators: 'مؤشرات الأداء الرئيسية',
    measurePerformance: 'قياس أداء المؤسسة مقارنة بالأهداف الاستراتيجية',
    filterResults: 'تصفية النتائج',
    target: 'الهدف',
    dataUpdatedOn: 'تم تحديث البيانات في',
  },
  reports: {
    title: 'التقارير',
    overview: 'نظرة عامة',
    overviewDescription: 'نظرة شاملة على مؤشرات الأداء الرئيسية لـ GEM 2.0',
    performanceTrends: 'اتجاهات الأداء',
    trendsDescription: 'مراقبة اتجاهات الأداء بمرور الوقت',
    responseTimeAnalysis: 'تحليل وقت الاستجابة',
    responseTimeDescription: 'تحليل أوقات الاستجابة عبر القنوات المختلفة',
    keyPerformanceIndicators: 'مؤشرات الأداء الرئيسية',
    kpiDescription: 'تحليل مفصل لمؤشرات الأداء الرئيسية',
    latestAlerts: 'أحدث التنبيهات',
    alertsDescription: 'إشعارات حديثة حول الجهات التي تتم متابعتها',
    sentimentImprovement: 'تحسن في المشاعر',
    minutesAgo: 'دقيقة مضت',
    negativeEngagementAlert: 'تنبيه: تفاعل سلبي يتطلب الانتباه',
    socialMediaReport: 'تقرير وسائل التواصل الاجتماعي',
    socialMediaReportDescription: 'تحليل مفصل لأداء وسائل التواصل الاجتماعي',
    socialMediaReportTitle: 'إنشاء تقرير وسائل التواصل الاجتماعي',
    socialMediaReportMessage: 'إنشاء تقرير شامل عن أداء وسائل التواصل الاجتماعي ومقاييس المشاركة وتحليل المشاعر عبر المنصات.',
    socialMediaEngagement: 'التفاعل على وسائل التواصل الاجتماعي',
    engagementTrendsDescription: 'اتجاهات التفاعل على مدار الأشهر الستة الماضية',
    topPerformingContent: 'المحتوى الأعلى أداءً',
    contentWithHighestEngagement: 'المحتوى ذو أعلى معدل تفاعل عبر المنصات',
    audienceDemographics: 'التركيبة السكانية للجمهور',
    audienceInsights: 'رؤى ديموغرافية للجمهور',
    audiencePercentage: 'نسبة الجمهور',
    geographicDistribution: 'التوزيع الجغرافي',
    audienceLocation: 'موقع الجمهور حسب المنطقة',
    sentimentByPlatformDescription: 'توزيع المشاعر عبر جميع المنصات',
    printReport: 'طباعة التقرير',
    shareReport: 'مشاركة التقرير',
    sentimentReport: 'تقرير المشاعر',
    sentimentAnalysis: 'تحليل المشاعر',
    sentimentAnalysisDescription: 'تحليل مفصل للمشاعر عبر المنصات',
    sentimentDistribution: 'توزيع المشاعر',
    keyInsights: 'الرؤى الرئيسية',
    positiveSentiment: 'المشاعر الإيجابية',
    positiveSentimentDesc: 'المحتوى الذي تلقى في المقام الأول مشاركة وردود فعل إيجابية.',
    neutralSentiment: 'المشاعر المحايدة',
    neutralSentimentDesc: 'المحتوى الذي تلقى في المقام الأول ردود فعل محايدة أو إعلامية.',
    negativeSentiment: 'المشاعر السلبية',
    negativeSentimentDesc: 'المحتوى الذي تلقى ردود فعل سلبية كبيرة أو انتقادات.',
    customReport: 'تقرير مخصص',
    customReportDescription: 'إنشاء تقارير مخصصة بناءً على معايير محددة',
    customReportTitle: 'إنشاء تقرير مخصص',
    customReportMessage: 'تحديد المعلمات المخصصة ونطاقات التاريخ والمقاييس لإنشاء تقرير مصمم خصيصًا لاحتياجاتك التحليلية.',
    exportData: 'تصدير البيانات',
    viewDetailedReport: 'عرض تقرير مفصل',
    generateReport: 'إنشاء تقرير',
    createCustomReport: 'إنشاء تقرير مخصص',
    minutes: 'دقائق',
    improvement: 'تحسن',
    slower: 'أبطأ',
    digitalResponsiveness: 'الاستجابة الرقمية',
    negativeResponseTime: 'وقت الاستجابة السلبية',
    positiveEngagement: 'المشاركة الإيجابية',
    innovationIndex: 'مؤشر الابتكار',
    osintMaturity: 'نضج OSINT',
    futureReadiness: 'الجاهزية للمستقبل',
    strategicForesight: 'الرؤية الاستراتيجية',
    sentimentAnalytics: 'تحليلات المشاعر',
    performanceScore: 'درجة الأداء',
    positiveResponse: 'الاستجابة الإيجابية',
    negativeResponse: 'الاستجابة السلبية',
    
    // Smart Reports
    smartReportsTitle: 'التقارير الذكية',
    smartReportsDescription: 'تجميع جوانب مختلفة في تقارير شاملة',
    createSmartReport: 'إنشاء تقرير ذكي',
    smartReportName: 'اسم التقرير',
    smartReportNamePlaceholder: 'أدخل اسمًا للتقرير الخاص بك',
    reportComponents: 'مكونات التقرير',
    selectComponents: 'حدد مكونات التقرير',
    excellenceComponent: 'مؤشرات التميز',
    socialMediaComponent: 'تحليل وسائل التواصل الاجتماعي',
    sentimentComponent: 'تحليل المشاعر',
    entitiesComponent: 'الجهات الحكومية',
    mediaComponent: 'التغطية الإعلامية',
    includeCharts: 'تضمين الرسوم البيانية',
    includeRawData: 'تضمين البيانات الخام',
    includeSummary: 'تضمين ملخص',
    compileReport: 'تجميع التقرير',
    savedReports: 'التقارير المحفوظة',
    noSavedReports: 'لا توجد تقارير محفوظة حتى الآن',
    generatingReport: 'جاري إنشاء التقرير...',
    reportHistory: 'سجل التقارير',
    latestReports: 'أحدث التقارير',
    scheduledReports: 'التقارير المجدولة',
    scheduleReport: 'جدولة التقرير',
    frequency: 'التكرار',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    recipients: 'المستلمين',
    addRecipient: 'إضافة مستلم',
    reportCompiledSuccess: 'تم تجميع التقرير بنجاح',
    reportScheduledSuccess: 'تم جدولة التقرير بنجاح',
    compareReports: 'مقارنة التقارير',
    reportTemplates: 'قوالب التقارير',
    useTemplate: 'استخدام القالب',
    saveAsTemplate: 'حفظ كقالب',
    editTemplate: 'تعديل القالب',
    deleteTemplate: 'حذف القالب',
    confirmDeleteTemplate: 'هل أنت متأكد أنك تريد حذف هذا القالب؟',
  },
  navigation: {
    home: 'الرئيسية',
    reports: 'تقارير',
    dashboard: 'لوحة التحكم',
    personalizedDashboard: 'لوحة التحكم المخصصة',
    mediaCenter: 'مركز الإعلام',
    socialMediaManagement: 'إدارة وسائل التواصل الاجتماعي',
    monitoring: 'مراقبة وسائل الإعلام',
    entityMonitoring: 'مراقبة الجهات الحكومية',
    pressRelease: 'نشر بيان صحفي',
    smartReports: 'التقارير الذكية',
    excellenceIndicators: 'مؤشرات التميز المؤسسي',
    performanceVisualization: 'عرض الأداء',
    contextHints: 'تلميحات السياق اللغوي',
    viewPerformanceVisualization: 'عرض تصور الأداء',
    users: 'إدارة المستخدمين',
    tutorials: 'دروس تعليمية',
    settings: 'الإعدادات',
    help: 'المساعدة',
    sidebarLabel: 'التنقل الرئيسي',
  },
  gem: {
    title: 'مؤشرات منظومة التميز المؤسسي',
    kpiTitle: 'مؤشر منظومة التميز المؤسسي',
  },
  emojiReactions: {
    // Positive messages
    exceptional: 'أداء استثنائي!',
    excellent: 'إنجاز ممتاز!',
    onTrack: 'على المسار الصحيح للوصول إلى الهدف',
    // Neutral messages
    progressing: 'يحرز تقدمًا',
    needsAttention: 'يحتاج إلى بعض الاهتمام',
    // Negative messages
    belowTarget: 'أقل من المستهدف',
    significantGap: 'فجوة كبيرة للوصول إلى الهدف',
    critical: 'يتطلب اهتمامًا عاجلًا',
    // Values
    currentValue: 'القيمة الحالية',
    targetValue: 'القيمة المستهدفة'
  },
  excellence: {
    title: 'مؤشرات التميز المؤسسي',
    description: 'تتبع وتحليل مؤشرات الأداء الرئيسية للتميز المؤسسي عبر المحاور الاستراتيجية',
    dateRange: 'الفترة الزمنية',
    pickDates: 'اختر التواريخ',
    strategicAxis: 'المحور الاستراتيجي',
    allAxes: 'جميع المحاور',
    communication: 'التواصل',
    innovation: 'الابتكار',
    smartTransformation: 'التحول الذكي',
    dataManagement: 'البيانات والمعرفة',
    mainIndicators: 'المؤشرات الرئيسية',
    subIndicators: 'المؤشرات الفرعية',
    refresh: 'تحديث البيانات',
    exportCSV: 'تصدير CSV',
    exportPDF: 'تصدير PDF',
    current: 'القيمة الحالية',
    target: 'القيمة المستهدفة',
    status: 'الحالة',
    progress: 'التقدم',
    metricDetails: 'تفاصيل المقياس',
    noData: 'لا توجد بيانات متاحة للفترة المحددة',
    noDataForAxis: 'لا توجد بيانات متاحة لهذا المحور الاستراتيجي في الفترة المحددة',
    loadingData: 'جاري تحميل بيانات المؤشرات...',
    filterResults: 'تصفية النتائج',
    applyFilters: 'تطبيق الفلاتر',
    resetFilters: 'إعادة تعيين',
    dataNotAvailable: 'البيانات غير متوفرة',
    
    // Report Page Excellence Tab
    economicPillar: 'الركيزة الاقتصادية',
    socialPillar: 'الركيزة الاجتماعية',
    knowledgePillar: 'ركيزة المعرفة',
    innovationPillar: 'ركيزة الابتكار',
    digitalPillar: 'الركيزة الرقمية',
    indicatorsDescription: 'نظرة شاملة على مؤشرات التميز المؤسسي عبر جميع الركائز',
    reportDescription: 'تنزيل تقرير مؤشرات التميز الكامل مع تحليلات وأفكار مفصلة',
    knowledgeScoreImproved: 'تحسن درجة مؤشر المعرفة',
    innovationMetricsUpdated: 'تم تحديث مقاييس الابتكار',
    pillarComparison: 'مقارنة ركائز التميز',
    pillarComparisonDescription: 'مقارنة أداء ركائز التميز',
    yearlyTrends: 'الاتجاهات السنوية',
    yearlyTrendsDescription: 'اتجاهات الأداء على مدار العام الماضي',
    subindicatorsDistribution: 'توزيع المؤشرات الفرعية',
    subindicatorsDistributionDescription: 'توزيع المؤشرات الفرعية حسب مستوى الأداء',
    excellent: 'ممتاز',
    veryGood: 'جيد جداً',
    good: 'جيد',
    average: 'متوسط',
    needsImprovement: 'يحتاج إلى تحسين',
    subindicatorsCount: 'عدد المؤشرات الفرعية',
    pillarContribution: 'مساهمة الركائز',
    pillarContributionDescription: 'مساهمة كل ركيزة في درجة التميز الإجمالية',
    downloadFullReport: 'تنزيل التقرير الكامل',
    
    // Communication KPIs
    coverageVolume: 'حجم التغطية الإعلامية',
    positiveCoverageRate: 'معدل التغطية الإيجابية',
    mediaSentimentIndex: 'مؤشر المشاعر الإعلامية',
    socialEngagementRate: 'معدل التفاعل على وسائل التواصل الاجتماعي',
    responseTime: 'وقت الاستجابة',
    shareOfVoice: 'حصة الصوت',
    
    // Innovation KPIs
    implementedInnovations: 'الابتكارات المنفذة',
    ideaImplementationRate: 'معدل تنفيذ الأفكار',
    employeeInnovationRate: 'مشاركة الموظفين في الابتكار',
    innovationAwards: 'جوائز الابتكار والتقدير',
    operationalEfficiency: 'تحسين الكفاءة التشغيلية',
    innovationMediaCoverage: 'التغطية الإعلامية للابتكار',
    
    // Smart Transformation KPIs
    digitalServicesPercent: 'نسبة الخدمات الرقمية',
    digitalServicesAdoptionRate: 'معدل اعتماد الخدمات الرقمية',
    smartServicesUserSatisfaction: 'رضا المستخدمين عن الخدمات الذكية',
    internalProcessesAutomation: 'أتمتة العمليات الداخلية',
    smartInitiativesImplemented: 'المبادرات الذكية المنفذة',
    
    // Data & Knowledge KPIs
    knowledgeSharingSessions: 'جلسات مشاركة المعرفة',
    avgTrainingHours: 'متوسط ساعات التدريب',
    coreDataAccuracyRate: 'معدل دقة البيانات الأساسية',
    statisticalReportsPublished: 'التقارير الإحصائية المنشورة',
    dataDrivenDecisionIndex: 'مؤشر القرارات المدعومة بالبيانات',
    
    // Overview Charts
    overviewCharts: 'مخططات نظرة عامة على مؤشرات الأداء',
    axesOverview: 'نظرة عامة على المحاور الاستراتيجية',
    progressByAxis: 'مقارنة التقدم حسب المحور الاستراتيجي',
    percentProgress: 'نسبة التقدم',
    kpiProgress: 'مخطط تقدم مؤشرات الأداء',
    keyIndicatorsRating: 'تقييم إنجاز المؤشرات الرئيسية',
    achievement: 'معدل الإنجاز',
    refreshData: 'تحديث البيانات',
    
    // Export functionality
    exportFullReport: 'تنزيل التقرير الكامل',
    exportOptions: 'خيارات التصدير',
    exportExcel: 'تصدير إكسل',
    exportError: 'خطأ في التصدير',
    noDataToExport: 'لا توجد بيانات متاحة للتصدير',
    exportSuccess: 'تم التصدير بنجاح',
    reportExported: 'تم تصدير التقرير بنجاح'
  },
  charts: {
    months: {
      jan: 'يناير',
      feb: 'فبراير',
      mar: 'مارس',
      apr: 'أبريل',
      may: 'مايو',
      jun: 'يونيو',
      jul: 'يوليو',
      aug: 'أغسطس',
      sep: 'سبتمبر',
      oct: 'أكتوبر',
      nov: 'نوفمبر',
      dec: 'ديسمبر'
    },
    week: 'أسبوع',
    digitalResponsiveness: 'الاستجابة الرقمية',
    negativeFeedbackResponse: 'الاستجابة للتعليقات السلبية',
    positiveEngagement: 'المشاركة الإيجابية',
    osintMaturity: 'نضج OSINT',
    futureReadiness: 'الجاهزية للمستقبل',
    strategicForesight: 'الرؤية الاستراتيجية',
    sentimentAnalytics: 'تحليلات المشاعر',
    innovationIndex: 'مؤشر الابتكار',
  },
  dashboard: {
    mainTitle: 'لوحة التحكم الرئيسية',
    timeFilter: 'آخر 30 يوم',
    downloadReport: 'تنزيل التقرير',
    timeAndCalendar: 'الوقت والتقويم',
    search: 'بحث في لوحة التحكم',
    searchKeywords: 'بحث عن الكلمات الرئيسية أو المحتوى',
    searchResults: 'نتائج البحث',
    noSearchResults: 'لم يتم العثور على منشورات مطابقة',
    filter: 'التصفية',
    applyFilters: 'تطبيق التصفية',
    realtimeSentimentTrends: 'اتجاهات المشاعر في الوقت الحقيقي',
    trackSentimentChanges: 'تتبع تغيرات المشاعر بمرور الوقت مع تصور متحرك للخطوط',
    sentimentTrend: 'اتجاهات المشاعر',
    selectPlatform: 'اختيار المنصة',
    selectTimeRange: 'اختيار الفترة الزمنية',
    allPlatforms: 'جميع المنصات',
    last7Days: 'آخر 7 أيام',
    last14Days: 'آخر 14 يوم',
    last30Days: 'آخر 30 يوم',
    refresh: 'تحديث',
    loadingTrendData: 'جاري تحميل بيانات الاتجاهات...',
    noTrendDataAvailable: 'لا توجد بيانات اتجاهات متاحة',
    timePeriod: 'الفترة الزمنية',
    sentimentPercentage: 'نسبة المشاعر',
    positive: 'إيجابي',
    neutral: 'محايد',
    negative: 'سلبي',
    positiveIncreasing: 'المشاعر الإيجابية في ازدياد',
    positiveDecreasing: 'المشاعر الإيجابية في انخفاض',
    negativeIncreasing: 'المشاعر السلبية في ازدياد (مقلق)',
    negativeDecreasing: 'المشاعر السلبية في انخفاض (جيد)',
    newsSource: 'مصادر الأخبار',
    refreshAriaLabel: 'تحديث بيانات الاتجاهات',
    sentimentTrendVisualization: 'التصور البياني لاتجاهات المشاعر',
    sentimentChartDescription: 'يوضح هذا الرسم البياني اتجاهات المشاعر بمرور الوقت، مع خطوط منفصلة للنسب المئوية للمشاعر الإيجابية والمحايدة والسلبية.',
    sentimentDistributionLabel: 'توزيع المشاعر: {{positive}}% إيجابي، {{neutral}}% محايد، {{negative}}% سلبي',
    offline: 'غير متصل',
    live: 'مباشر',
    topSources: 'المصادر الرئيسية',
    topKeywords: 'الكلمات الرئيسية',
    realTimeAlerts: 'تنبيهات في الوقت الحقيقي',
    alertsDisabled: 'التنبيهات معطلة',
    enableAlerts: 'تفعيل التنبيهات',
    marketShareIncrease: 'لوحة معلومات زيادة حصة السوق',
    mentionsOverTime: 'الاشارات بمرور الوقت',
    alertTypes: {
      sentiment: 'المشاعر',
      mention: 'الذكر',
      keyword: 'الكلمة المفتاحية',
      volume: 'حجم النشاط'
    },
    alertMessages: {
      negativeSentimentSpike: 'تم رصد ارتفاع في المشاعر السلبية على تويتر',
      vipMention: 'ذكر من صحفي بارز',
      trendingKeyword: 'تم اكتشاف الكلمة الرئيسية الرائجة "جودة الخدمة"',
      unusualActivity: 'حجم نشاط غير عادي على انستغرام'
    },
    alertSeverity: {
      high: 'عالي',
      medium: 'متوسط',
      low: 'منخفض'
    },
    keyInsights: 'الرؤى الرئيسية',
    shareOfVoice: 'حصة الصوت',
    analyticsOverview: 'نظرة عامة على التحليلات',
    exportData: 'تصدير البيانات',
    viewAllReports: 'عرض جميع التقارير',
    viewAllMedia: 'عرض كل الوسائط',
    viewAll: 'عرض الكل',
    viewAllTutorials: 'عرض كل الدروس التعليمية',
    testSentimentAnalysis: 'اختبار تحليل المشاعر',
    kpiOverview: 'نظرة عامة على مؤشرات الأداء',
    mediaMonitoring: 'مراقبة وسائل الإعلام',
    mediaCenter: 'مركز الوسائط',
    tutorials: 'الدروس التعليمية',
    themeExplorer: 'مستكشف السمات',
    customizeThemes: 'تخصيص السمات',
    sentiment: 'المشاعر',
    trends: 'الإتجاهات',
    social: 'التواصل الاجتماعي',
    news: 'الأخبار',
    sentimentScore: 'درجة المشاعر',
    mediaPresence: 'التواجد الإعلامي',
    engagementRate: 'معدل المشاركة',
    sentimentAnalysis: 'تحليل المشاعر',
    realTimeTrends: 'اتجاهات المشاعر في الوقت الفعلي',
    realTrends: 'الاتجاهات في الوقت الفعلي',
    realTimeSentimentTrends: 'اتجاهات المشاعر في الوقت الفعلي',
    newsAnalyzer: 'محلل الأخبار',
    today: 'اليوم',
    thisMonth: 'هذا الشهر',
    thisQuarter: 'هذا الربع',
    thisYear: 'هذه السنة',
    custom: 'مخصص',
    mentionsTotal: 'إجمالي الذكر',
    sentimentAverage: 'متوسط المشاعر',
    responseTime: 'سرعة الاستجابة',
    innovationIndex: 'مؤشر الابتكار',
    comparedTo: 'مقارنة بـ',
    inPreviousPeriod: 'في الفترة السابقة',
    minutes: 'دقيقة',
    relativelyStable: 'مستقر نسبيًا مقارنة بالفترة السابقة',
    averageResponseTime: 'متوسط وقت الاستجابة للتعليقات السلبية',
    notableImprovement: 'تحسن ملحوظ في العام الماضي',
    dashboardTitle: 'لوحة التحكم',
    dashboardDescription: 'اختر بين واجهة قياسية أو مخصصة لعرض البيانات',
    standardDashboard: 'لوحة التحكم القياسية',
    personalizedDashboard: 'لوحة التحكم المخصصة',
    widgetSettings: 'إعدادات الأداة',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    customizeDashboard: 'تخصيص لوحة التحكم',
    addWidgets: 'إضافة أدوات',
    loading: 'جاري تحميل لوحة التحكم...',
    title: 'لوحة التحكم',
    saveSuccess: 'تم حفظ لوحة التحكم',
    saveSuccessDescription: 'تم حفظ تخطيط لوحة التحكم الخاصة بك بنجاح',
    saveFailed: 'فشل الحفظ',
  },
  analysis: {
    sentimentAnalysis: 'تحليل المشاعر',
    platforms: 'منصات التواصل',
    mainTopics: 'المواضيع الرئيسية',
    demographics: 'التركيبة السكانية',
    sentimentOverTime: 'تحليل المشاعر عبر الوقت',
    sentimentChart: 'رسم بياني لتحليل المشاعر عبر الوقت',
    trendDisplay: 'يعرض اتجاهات المشاعر الإيجابية والسلبية والمحايدة',
    sentimentDistribution: 'توزيع المشاعر',
    positive: 'إيجابي',
    neutral: 'محايد',
    negative: 'سلبي',
    overallSentiment: 'المشاعر العامة',
    influentialKeywords: 'الكلمات المؤثرة',
    sourceBreakdown: 'ترتيب المصادر',
    sentimentFilters: 'فلتر التحليل العاطفي',
    positiveSentiment: 'تحليل المشاعر الإيجابية',
    negativeSentiment: 'تحليل المشاعر السلبية',
    sentimentImprovement: 'تحليل تحسين المشاعر',
    sentimentDecrease: 'تحليل انخفاض المشاعر',
    sentimentByPlatform: 'تحليل المشاعر حسب المنصة',
    trackSentimentChanges: 'تتبع تغييرات المشاعر بمرور الوقت باستخدام التصور البياني المتحرك',
  },
  monitoring: {
    title: 'مراقبة وسائل الإعلام',
    all: 'الكل',
    allPlatforms: 'جميع المنصات',
    twitter: 'تويتر',
    facebook: 'فيسبوك',
    instagram: 'انستغرام',
    news: 'المواقع الإخبارية',
    clearAll: 'تصفية الكل',
    downloadReport: 'تنزيل التقرير',
    alertSettings: 'إعدادات التنبيه',
    hoursAgo: 'منذ {{hours}} ساعة',
    keywords: 'الكلمات المفتاحية',
    addKeyword: 'إضافة كلمة مفتاحية جديدة',
    activeAlerts: 'تنبيهات نشطة',
    negativeRise: 'ارتفاع في الذكر السلبي',
    threshold: 'الحد',
    keywordTrends: 'كلمات مفتاحية في الاتجاهات',
    mentions: 'ذكر',
    defaultUser: 'مستخدم',
    defaultUsername: 'اسم المستخدم',
    noPosts: 'لم يتم العثور على منشورات',
    twitterContent: 'محتوى تويتر',
    facebookContent: 'محتوى فيسبوك',
    instagramContent: 'محتوى انستغرام',
    newsContent: 'محتوى الأخبار',
    engagement: {
      likes: '{{count}}',
      comments: '{{count}}',
      shares: '{{count}}'
    }
  },
  entity: {
    testPage: 'صفحة اختبار مراقبة الجهات',
    normalView: 'العرض العادي',
    debugView: 'عرض التصحيح',
    monitoring: 'مراقبة الجهات الحكومية',
    enableDebugMode: 'تفعيل وضع التصحيح',
    disableDebugMode: 'إيقاف وضع التصحيح',
    directAccessTest: 'اختبار الوصول المباشر',
    enterEntityId: 'أدخل معرف الجهة',
    entityIdPlaceholder: 'مثال: 1، 2، 3...',
    goToEntityPage: 'انتقل إلى صفحة الجهة',
    availableEntities: 'الجهات المتاحة',
    errorLoadingEntities: 'خطأ في تحميل الجهات',
    error: {
      loading: 'خطأ في التحميل',
      notFound: 'لم يتم العثور على الجهة',
      invalidPost: 'منشور غير صالح'
    },
    metrics: {
      totalMentions: 'إجمالي عدد الذكر',
      acrossPlatforms: 'عبر جميع المنصات',
      avgSentiment: 'متوسط المشاعر',
      sentimentBreakdown: 'تحليل المشاعر',
      activePlatform: 'المنصة الأكثر نشاطًا',
      ofAllMentions: '% من جميع الذكر',
      none: 'لا يوجد'
    },
    sentiment: {
      positive: 'إيجابي',
      neutral: 'محايد',
      negative: 'سلبي',
      veryPositive: 'إيجابي جدًا ({{range}})',
      veryNegative: 'سلبي جدًا ({{range}})'
    },
    tabs: {
      posts: 'المنشورات',
      trends: 'الاتجاهات',
      analytics: 'التحليلات'
    },
    posts: {
      noMentions: 'لم يتم العثور على أي ذكر لهذه الجهة حتى الآن. تحقق مرة أخرى لاحقًا.'
    },
    trends: {
      sentimentTrend: 'اتجاه المشاعر',
      sentimentOverTime: 'تحليل المشاعر عبر الزمن',
      mentionsByPlatform: 'الذكر حسب المنصة',
      distributionAcrossPlatforms: 'التوزيع عبر منصات التواصل الاجتماعي',
      notEnoughData: 'لا توجد بيانات كافية لعرض الاتجاه.',
      noPlatformData: 'لا توجد بيانات متاحة لتوزيع المنصات.',
      sentimentScore: 'درجة المشاعر',
      date: 'التاريخ'
    },
    analytics: {
      sentimentAnalysis: 'تحليل المشاعر',
      breakdownDescription: 'تحليل توزيع المشاعر في الذكر',
      noSentimentData: 'لا توجد بيانات مشاعر متاحة للتحليل.',
      numberOfMentions: 'عدد مرات الذكر'
    },
    post: {
      author: 'الكاتب',
      unknownAuthor: 'كاتب مجهول',
      unknownDate: 'تاريخ غير معروف',
      unknownPlatform: 'منصة غير معروفة',
      noContent: 'لا يوجد محتوى',
      viewOriginal: 'عرض المنشور الأصلي'
    }
  },
  entities: {
    title: 'مراقبة الجهات الحكومية',
    allTypes: 'جميع الأنواع',
    allRegions: 'جميع المناطق',
    activeOnly: 'الجهات النشطة فقط',
    filters: 'التصفية',
    refineEntities: 'تنقية الجهات الحكومية المعروضة أدناه',
    search: 'بحث',
    searchByName: 'بحث حسب الاسم',
    entityType: 'نوع الجهة',
    region: 'المنطقة',
    addEntity: 'إضافة جهة',
    viewDetails: 'عرض التفاصيل',
    totalMentions: 'إجمالي الذكر',
    avgSentiment: 'متوسط المشاعر',
    sentimentBreakdown: 'تقسيم المشاعر',
    mostActivePlatform: 'المنصة الأكثر نشاطًا',
    ofAllMentions: '% من جميع الذكر',
    posts: 'المنشورات',
    trends: 'الاتجاهات',
    analytics: 'التحليلات',
    noMentions: 'لم يتم العثور على ذكر لهذه الجهة بعد. تحقق لاحقًا.',
    sentimentTrend: 'اتجاه المشاعر',
    sentimentOverTime: 'تحليل المشاعر على مدار الوقت',
    mentionsByPlatform: 'الذكر حسب المنصة',
    platformDistribution: 'التوزيع عبر وسائل التواصل الاجتماعي',
    noDataForTrend: 'لا توجد بيانات كافية لعرض الاتجاه.',
    noDataForDistribution: 'لا توجد بيانات متاحة لتوزيع المنصة.',
    sentimentAnalysis: 'تحليل المشاعر',
    sentimentDistribution: 'تقسيم توزيع المشاعر في الذكر',
    noDataForAnalysis: 'لا توجد بيانات مشاعر متاحة للتحليل.',
    positive: 'إيجابي',
    neutral: 'محايد',
    negative: 'سلبي',
    federal: 'اتحادية',
    local: 'محلية',
    ministry: 'وزارة',
    authority: 'هيئة',
    council: 'مجلس',
    active: 'نشط',
    inactive: 'غير نشط',
    edit: 'تعديل الجهة الحكومية',
    add: 'إضافة جهة حكومية',
    editDescription: 'تحديث تفاصيل هذه الجهة الحكومية',
    addDescription: 'إضافة جهة حكومية جديدة إلى نظام المراقبة',
    nameEnglish: 'الاسم (الإنجليزية)',
    nameArabic: 'الاسم (العربية)',
    iconUrl: 'رابط الأيقونة',
    iconUrlDescription: 'رابط لشعار أو أيقونة الجهة',
    websiteUrl: 'رابط الموقع',
    websiteUrlDescription: 'الموقع الرسمي للجهة',
    priority: 'الأولوية',
    priorityDescription: 'الجهات ذات الأولوية العالية تظهر أولاً (0-100)',
    activeStatus: 'نشط',
    inactiveDescription: 'الجهات غير النشطة لن تتم مراقبتها',
    delete: 'حذف',
    deleteEntity: 'حذف الجهة الحكومية',
    deleteConfirmation: 'هل أنت متأكد أنك تريد حذف هذه الجهة؟ لا يمكن التراجع عن هذا الإجراء.',
    cancel: 'إلغاء',
    update: 'تحديث',
    create: 'إنشاء',
    entityCreated: 'تم إنشاء الجهة الحكومية',
    entityUpdated: 'تم تحديث الجهة الحكومية',
    entityDeleted: 'تم حذف الجهة الحكومية',
    createFailed: 'فشل إنشاء الجهة',
    updateFailed: 'فشل تحديث الجهة',
    deleteFailed: 'فشل حذف الجهة',
  },
  mediaCenter: {
    title: 'مركز الإعلام',
    viewAll: 'عرض الكل',
    image: 'صورة',
    video: 'فيديو',
    document: 'مستند',
    updated: 'تم التحديث منذ',
    days: 'يوم',
    weeks: 'أسبوع',
    projects: 'مشاريع',
    events: 'فعاليات',
    reports: 'تقارير',
    news: 'أخبار',
    search: 'بحث',
    filter: 'تصفية',
    date: 'التاريخ',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    lastWeek: 'الأسبوع الماضي',
    upload: 'رفع ملف',
    all: 'الكل',
    uaeNewsSources: 'مصادر الأخبار الإماراتية',
    integratedPlatforms: 'المنصات المحلية ومواقع الحكومة المتكاملة',
    internalMediaLibrary: 'مكتبة الوسائط الداخلية',
    browse: 'تصفح',
    visitWebsite: 'زيارة الموقع',
    visitOfficialWebsite: 'زيارة الموقع الرسمي',
    downloadFile: 'تنزيل الملف',
    shareContent: 'مشاركة المحتوى',
    viewFullArticle: 'عرض المقال كاملا',
    viewFullPressRelease: 'عرض البيان الصحفي كاملا',
    ajmanGovPressReleases: 'البيانات الصحفية لحكومة عجمان',
    ajmanPoliceNews: 'أخبار وتحديثات شرطة عجمان',
    wamNewsAgency: 'وكالة أنباء الإمارات (وام)',
    sourcePlatforms: 'منصات المصادر',
    ajmanGovDescription: 'الوصول إلى البيانات الصحفية والأخبار والإعلانات الرسمية من حكومة عجمان.',
    ajmanPoliceDescription: 'الوصول إلى تحديثات الأمن وأخبار المجتمع ومعلومات السلامة من شرطة عجمان.',
    wamDescription: 'الوصول إلى وكالة أنباء الإمارات (وام) للحصول على تغطية شاملة لأخبار الإمارات والتحديثات.',
  },
  tutorials: {
    title: 'دروس تعليمية',
    viewAll: 'عرض الكل',
    duration: 'مدة الفيديو',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
  },
  auth: {
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    invalidCredentials: 'بيانات الاعتماد غير صالحة',
  },
  notifications: {
    title: 'إشعارات',
    keywordAlert: 'تنبيه: ارتفاع ذكر الكلمة الرئيسية "الابتكار"',
    negativeReaction: 'تنبيه: ردود فعل سلبية على منشور الفيسبوك',
    newReport: 'تنبيه: تقرير جديد جاهز للتحميل',
    minutesAgo: 'منذ {{minutes}} دقائق',
    hoursAgo: 'منذ {{hours}} ساعة',
  },
  common: {
    language: 'اللغة',
    arabic: 'العربية',
    english: 'الإنجليزية',
    id: 'المعرف',
    backToList: 'العودة إلى القائمة',
    admin: 'مدير',
    analyst: 'محلل',
    editor: 'محرر',
    viewer: 'مشاهد',
    official: 'رسمي',
    loading: 'جاري التحميل...',
    processing: 'جاري المعالجة...',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    deleting: 'جاري الحذف...',
    actions: 'إجراءات',
    deleteAction: 'حذف هذا العنصر',
    deletingAction: 'جاري حذف هذا العنصر',
    cancelAction: 'إلغاء هذا الإجراء',
    processingRequest: 'جاري معالجة طلبك...',
    save: 'حفظ',
    add: 'إضافة',
    remove: 'إزالة',
    search: 'بحث',
    filter: 'تصفية',
    close: 'إغلاق',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    submit: 'إرسال',
    reset: 'إعادة تعيين',
    clear: 'مسح',
    show: 'عرض',
    hide: 'إخفاء',
    all: 'الكل',
    none: 'لا شيء',
    enabled: 'مفعل',
    disabled: 'معطل',
    minutes: 'دقائق',
    hours: 'ساعات',
    days: 'أيام',
    minutes_ago: 'منذ {{count}} دقيقة',
    hours_ago: 'منذ {{count}} ساعة',
    days_ago: 'منذ {{count}} يوم',
    ago: 'منذ'
  },
  export: {
    formatPNG: 'PNG',
    formatPDF: 'PDF',
    formatExcel: 'إكسل'
  },
  social: {
    facebook: 'فيسبوك',
    twitter: 'تويتر',
    instagram: 'انستغرام',
    telegram: 'تليغرام',
    linkedin: 'لينكد إن',
    youtube: 'يوتيوب',
    tiktok: 'تيك توك',
    snapchat: 'سناب شات',
    news: 'أخبار'
  },
  settings: {
    title: 'الإعدادات',
    settingsMenu: 'قائمة الإعدادات',
    profileTab: 'الملف الشخصي',
    appearanceTab: 'المظهر',
    notificationsTab: 'الإشعارات',
    securityTab: 'الأمان',
    apiTab: 'API والتكاملات',
    helpTab: 'المساعدة والدعم',
    profileSettings: 'إعدادات الملف الشخصي',
    profileDescription: 'إدارة معلوماتك الشخصية وتفضيلاتك',
    personalDetails: 'التفاصيل الشخصية',
    nameLabel: 'الاسم الكامل',
    namePlaceholder: 'أدخل اسمك',
    emailLabel: 'البريد الإلكتروني',
    emailPlaceholder: 'بريدك@مثال.كوم',
    roleLabel: 'الدور',
    accountType: 'نوع الحساب',
    timeZoneLabel: 'المنطقة الزمنية',
    bioLabel: 'السيرة الذاتية',
    bioPlaceholder: 'اكتب نبذة قصيرة عن نفسك',
    appearanceSettings: 'إعدادات المظهر',
    appearanceDescription: 'تخصيص مظهر ولغة المنصة',
    language: 'اللغة',
    selectLanguage: 'اختر لغة',
    addLanguage: 'إضافة لغة جديدة',
    theme: 'السمة',
    lightTheme: 'الوضع المضيء',
    darkTheme: 'الوضع المظلم',
    systemTheme: 'افتراضي النظام',
    textDirection: 'اتجاه النص',
    rtl: 'من اليمين إلى اليسار',
    ltr: 'من اليسار إلى اليمين',
    notificationSettings: 'إعدادات الإشعارات',
    notificationDescription: 'إدارة كيفية ووقت تلقي الإشعارات',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    dashboardAlerts: 'تنبيهات لوحة التحكم',
    platformStatus: 'تحديثات حالة المنصة',
    negativeMentions: 'ذكر سلبي',
    keywordSpikes: 'ارتفاعات في ذكر الكلمات المفتاحية',
    systemNotifications: 'إشعارات النظام',
    systemTrend: 'المواضيع الرائجة',
    systemNegative: 'تنبيهات المشاعر السلبية',
    systemLogin: 'محاولات تسجيل الدخول',
    securitySettings: 'إعدادات الأمان',
    securityDescription: 'إدارة أمان حسابك وإعدادات الوصول',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    twoFactorAuth: 'المصادقة الثنائية',
    enableTwoFactor: 'تفعيل المصادقة الثنائية',
    securityOptions: 'خيارات الأمان',
    sessionTimeout: 'مهلة الجلسة',
    loginHistory: 'سجل تسجيل الدخول',
    view: 'عرض',
    apiSettings: 'إعدادات API والتكاملات',
    apiDescription: 'إدارة مفاتيح API والتكاملات الخارجية',
    apiKeys: 'مفاتيح API',
    apiUsage: 'استخدام API',
    activeKey: 'نشط',
    noActiveKeys: 'لا توجد مفاتيح API نشطة',
    generateNewKey: 'إنشاء مفتاح جديد',
    dataUsage: 'استخدام البيانات',
    quotaResets: 'تعيين الحصة في',
    webhooks: 'الويب هوك',
    noWebhooks: 'لم يتم تكوين أي ويب هوك',
    addWebhook: 'إضافة ويب هوك',
    helpSupport: 'المساعدة والدعم',
    helpDescription: 'الموارد وخيارات الدعم لمساعدتك في استخدام المنصة',
    documentation: 'الوثائق',
    documentationDesc: 'البحث عن المساعدة والأدلة لاستخدام منصة ذكاء الإعلام',
    viewDocs: 'عرض الوثائق',
    tutorials: 'الدروس التعليمية',
    tutorialsDesc: 'مقاطع فيديو تعليمية وأدلة خطوة بخطوة',
    viewTutorials: 'عرض الدروس التعليمية',
    supportTicket: 'تذكرة الدعم',
    supportTicketDesc: 'إرسال مشكلة أو سؤال إلى فريق الدعم لدينا',
    createTicket: 'إنشاء تذكرة',
    contactUs: 'اتصل بنا',
    contactUsDesc: 'معلومات الاتصال المباشر لفريق الدعم لدينا',
    contactSupport: 'الاتصال بالدعم',
    faq: 'الأسئلة المتكررة',
    faq1: 'كيف أفسر درجات تحليل المشاعر؟',
    faq2: 'هل يمكنني تصدير البيانات إلى تنسيقات أخرى؟',
    faq3: 'كم مرة يتم تحديث بيانات وسائل التواصل الاجتماعي؟',
    saveChanges: 'حفظ التغييرات',
    langManagement: 'إدارة اللغات',
    langManagementDescription: 'إضافة أو تعديل أو إزالة خيارات اللغة للمنصة',
    availableLanguages: 'اللغات المتاحة',
    languageSelector: 'محدد اللغة',
    languageCode: 'رمز اللغة',
    langName: 'اسم اللغة',
    langNameEnglish: 'اسم اللغة (بالإنجليزية)',
    langNameNative: 'اسم اللغة (الأصلية)',
    actions: 'الإجراءات',
    editLang: 'تعديل',
    deleteLang: 'حذف',
    defaultLang: 'افتراضي',
    makeDefault: 'جعلها افتراضية',
    addLangTitle: 'إضافة لغة جديدة',
    importLangFile: 'استيراد ملف اللغة',
    uploadLangFile: 'تحميل ملف الترجمة',
    langFileFormat: 'مطلوب تنسيق JSON',
    completeness: 'الاكتمال',
  },
  contact: {
    title: 'اتصل بنا',
    subtitle: 'تواصل معنا لأي استفسارات أو ملاحظات أو أسئلة.',
    backToHome: 'العودة إلى الرئيسية',
    thankYou: 'تم إرسال الرسالة!',
    responseTime: 'نحن عادة ما نرد خلال 24-48 ساعة عمل.',
    sendAnother: 'إرسال رسالة أخرى',
    successTitle: 'تم إرسال الرسالة',
    successMessage: 'تم تقديم طلب الاتصال الخاص بك بنجاح. سنرد عليك قريبًا.',
    errorTitle: 'خطأ',
    errorMessage: 'حدثت مشكلة أثناء إرسال رسالتك. يرجى المحاولة مرة أخرى.',
    form: {
      name: 'الاسم',
      namePlaceholder: 'أدخل اسمك الكامل',
      email: 'البريد الإلكتروني',
      emailPlaceholder: 'أدخل عنوان بريدك الإلكتروني',
      subject: 'الموضوع',
      subjectPlaceholder: 'ما هو موضوع استفسارك؟',
      department: 'القسم',
      departmentPlaceholder: 'حدد قسمًا',
      departments: {
        support: 'الدعم الفني',
        sales: 'المبيعات والتسعير',
        billing: 'الفواتير والحسابات',
        technical: 'التكامل التقني',
        partnership: 'فرص الشراكة',
        other: 'استفسارات أخرى'
      },
      message: 'الرسالة',
      messagePlaceholder: 'يرجى وصف استفسارك بالتفصيل...',
      submit: 'إرسال الرسالة',
      sending: 'جاري الإرسال...'
    },
    contactInfo: {
      title: 'معلومات الاتصال',
      subtitle: 'إليك كيفية الوصول إلينا مباشرة',
      email: 'راسلنا عبر البريد الإلكتروني',
      phone: 'اتصل بنا',
      address: 'قم بزيارتنا',
      addressLine1: 'المقر الرئيسي لمنصة ذكاء الإعلام',
      addressLine2: 'المنطقة الإعلامية، أبوظبي، الإمارات',
      hours: 'ساعات العمل',
      workdays: 'الأحد - الخميس',
      weekend: 'الجمعة - السبت',
      closed: 'مغلق'
    }
  },
  supportCenter: {
    title: 'مركز المساعدة والدعم',
    subtitle: 'ابحث عن الإجابات والموارد والدعم لأسئلتك',
    tabs: {
      overview: 'نظرة عامة',
      resources: 'الموارد',
      help: 'الحصول على المساعدة'
    },
    faq: {
      title: 'الأسئلة المتكررة',
      description: 'إجابات سريعة للأسئلة الشائعة',
      content: 'تصفح الأسئلة المتكررة للحصول على إجابات للأسئلة الشائعة حول ميزات المنصة واستخدامها واستكشاف الأخطاء وإصلاحها.',
      browseButton: 'تصفح الأسئلة المتكررة'
    },
    knowledgeBase: {
      title: 'قاعدة المعرفة',
      description: 'أدلة ومقالات مفصلة',
      content: 'ابحث عن مقالات وأدلة متعمقة حول استخدام المنصة وأفضل الممارسات والميزات المتقدمة.',
      browseButton: 'تصفح قاعدة المعرفة'
    },
    supportTickets: {
      title: 'تذاكر الدعم',
      description: 'احصل على مساعدة شخصية من فريقنا',
      content: 'إنشاء تذاكر دعم للحصول على مساعدة مباشرة من فريقنا. تتبع حالة تذاكرك.',
      browseButton: 'عرض التذاكر'
    },
    getHelp: {
      title: 'بحاجة إلى مزيد من المساعدة؟',
      description: 'فريق الدعم لدينا موجود لمساعدتك في أي مشاكل أو استفسارات',
      createTicketButton: 'إنشاء تذكرة دعم',
      tutorialsButton: 'عرض البرامج التعليمية'
    },
    resources: {
      title: 'موارد التعلم',
      description: 'استكشف مواد التعلم الشاملة لدينا',
      documentation: 'الوثائق',
      documentationDescription: 'وثائق تقنية مفصلة لميزات المنصة وواجهات برمجة التطبيقات',
      documentationButton: 'عرض الوثائق',
      guides: 'أدلة المستخدم',
      guidesDescription: 'أدلة خطوة بخطوة لمساعدتك على استخدام ميزات المنصة بفعالية',
      guidesButton: 'عرض الأدلة',
      tutorials: 'برامج تعليمية بالفيديو',
      tutorialsDescription: 'شاهد البرامج التعليمية بالفيديو لتتعلم كيفية استخدام المنصة',
      tutorialsButton: 'مشاهدة البرامج التعليمية'
    },
    help: {
      title: 'الحصول على الدعم المباشر',
      description: 'اتصل بفريق الدعم لدينا للحصول على مساعدة شخصية',
      content: 'إذا لم تتمكن من العثور على الإجابات في قاعدة المعرفة لدينا أو البرامج التعليمية، قم بإنشاء تذكرة دعم للحصول على مساعدة مباشرة.',
      createTicketButton: 'إنشاء تذكرة دعم',
      faqButton: 'تحقق من الأسئلة المتكررة أولاً'
    },
    yourTickets: {
      title: 'تذاكر الدعم الخاصة بك',
      description: 'عرض وإدارة تذاكر الدعم الحالية',
      viewButton: 'عرض تذاكرك'
    },
    contactUs: {
      title: 'اتصل بنا',
      description: 'تواصل مع فريق الدعم لدينا مباشرة',
      content: 'هل لديك سؤال أو تحتاج إلى مساعدة؟ اتصل بفريق الدعم لدينا مباشرة من خلال نموذج الاتصال.',
      button: 'اتصل بنا'
    }
  },
  entityType: {
    ministry: 'وزارة',
    authority: 'هيئة',
    department: 'دائرة',
    agency: 'وكالة',
    council: 'مجلس',
    committee: 'لجنة'
  },
  users: {
    title: 'إدارة المستخدمين',
    usersDirectory: 'دليل المستخدمين',
    manageAccounts: 'إدارة حسابات المستخدمين والصلاحيات',
    search: 'بحث عن المستخدمين...',
    addUser: 'إضافة مستخدم',
    addNewUser: 'إضافة مستخدم جديد',
    fillDetails: 'املأ تفاصيل المستخدم لإنشاء حساب جديد',
    user: 'مستخدم',
    username: 'اسم المستخدم',
    usernamePlaceholder: 'أدخل اسم المستخدم',
    email: 'البريد الإلكتروني',
    fullName: 'الاسم الكامل',
    fullNamePlaceholder: 'أدخل الاسم الكامل',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    role: 'الدور',
    roles: {
      admin: 'مدير النظام',
      editor: 'محرر',
      analyst: 'محلل',
      user: 'مستخدم'
    },
    selectRole: 'اختر الدور',
    language: 'اللغة',
    languages: {
      arabic: 'العربية',
      english: 'الإنجليزية'
    },
    selectLanguage: 'اختر اللغة',
    resetPassword: 'إعادة تعيين كلمة المرور',
    createSuccess: 'تم إنشاء المستخدم',
    userCreated: 'تم إنشاء المستخدم {{name}} بنجاح',
    createError: 'خطأ في الإنشاء',
    createErrorMessage: 'حدث خطأ أثناء إنشاء المستخدم',
    confirmDelete: 'تأكيد الحذف',
    confirmDeleteDescription: 'هل أنت متأكد من رغبتك في حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    deleteSuccess: 'تم حذف المستخدم',
    userDeleted: 'تم حذف المستخدم بنجاح',
    deleteError: 'خطأ في الحذف',
    deleteErrorMessage: 'حدث خطأ أثناء حذف المستخدم',
    noUsersFound: 'لم يتم العثور على مستخدمين',
    userActions: 'إجراءات للمستخدم {{name}}',
    editUserAction: 'تعديل المستخدم {{name}}',
    resetPasswordAction: 'إعادة تعيين كلمة المرور للمستخدم {{name}}',
    deleteUserAction: 'حذف المستخدم {{name}}'
  },
  // Voice Assistant translations
  assistant: {
    title: 'مساعد مؤشرات الأداء',
    showAssistant: 'إظهار المساعد الصوتي',
    hideAssistant: 'إخفاء المساعد الصوتي',
    chat: 'المحادثة',
    help: 'المساعدة',
    voiceCommands: 'الأوامر الصوتية',
    error: 'خطأ في المساعد الصوتي',
    microphoneError: 'لا يمكن الوصول إلى الميكروفون. يرجى التحقق من أذونات المتصفح.',
    startError: 'تعذر بدء التعرف الصوتي. يرجى المحاولة مرة أخرى.',
    unsupported: 'متصفح غير مدعوم',
    browserUnsupported: 'متصفحك لا يدعم التعرف الصوتي.',
    listening: 'جاري الاستماع...',
    clickToSpeak: 'انقر على الميكروفون للتحدث',
    navigation: 'التنقل بين الأقسام',
    navExample1: 'أظهر لي مقاييس الاتصال',
    navExample2: 'انتقل إلى قسم إدارة البيانات',
    getHelp: 'الحصول على المساعدة',
    helpExample: 'بماذا يمكنك مساعدتي؟',
    closeAssistant: 'إغلاق المساعد',
    closeExample: 'أغلق المساعد'
  }
};

export default arTranslations;