// English translations
export const enTranslations = {
  app: {
    title: 'Ajman Police Media Intelligence',
  },
  calendar: {
    title: 'Calendar',
    pickDate: 'Pick a date',
    today: 'Today',
    selected: 'Selected',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    eventsForDate: 'Events for {{date}}',
    noEvents: 'No events for this date',
    addEvent: 'Add event',
    eventTypes: {
      default: 'Event',
      important: 'Important',
      reminder: 'Reminder'
    }
  },
  clock: {
    title: 'Clock',
    currentTime: 'Current Time',
    timeZone: 'Time Zone'
  },
  connection: {
    connected: 'Connected',
    connecting: 'Connecting',
    disconnected: 'Disconnected',
    error: 'Connection Error',
    reconnect: 'Reconnect',
    connected_tooltip: 'Real-time updates are active',
    connecting_tooltip: 'Establishing connection...',
    disconnected_tooltip: 'Real-time updates are not available',
    error_tooltip: 'Could not connect to the server',
    click_to_reconnect: 'Click to reconnect',
  },
  // Context Hints System translations
  contextHints: {
    language_context_hints: 'Language Context Hints',
    ai_powered_language_improvement_tool: 'AI-powered tool for enhancing language quality',
    context_hint_generator: 'Context Hint Generator',
    enter_text_for_language_analysis: 'Enter text to receive language improvement suggestions',
    analyzing_text: 'Analyzing Text',
    generating_language_hints: 'Generating language context hints...',
    no_hints_available: 'No language hints available',
    no_suggestions_found: 'No suggestions found for this text',
    minimum_text_required: 'Enter at least 5 characters for analysis',
    analyze_text: 'Analyze Text',
    analyzing: 'Analyzing...',
    select_language: 'Select Language',
    enter_text_here: 'Enter your text here...',
    copied: 'Copied',
    text_copied_to_clipboard: 'Text copied to clipboard',
    applied: 'Applied',
    suggestion_applied: 'Suggestion applied to text',
    original_text: 'Original Text',
    suggested_replacement: 'Suggested Replacement',
    explanation: 'Explanation',
    source: 'Source',
    confidence: 'Confidence',
    copy: 'Copy',
    apply: 'Apply',
    expand: 'Expand',
    collapse: 'Collapse',
    view_details: 'View suggestion details',
    collapse_details: 'Hide suggestion details',
    powered_by_ai: 'Powered by Anthropic Claude and OpenAI',
    about_context_hints: 'About Context Hints',
    how_context_hints_work: 'How the AI language suggestions work',
    context_hints_description: 'The Language Context Hint Generator uses advanced AI to improve your writing quality. It analyzes text to identify grammar issues, clarity improvements, tone adjustments, cultural sensitivities, and formality corrections.',
    supported_hint_types: 'Supported Hint Types',
    grammar: 'Grammar',
    grammar_description: 'Corrections for spelling, punctuation, and grammatical errors',
    clarity: 'Clarity',
    clarity_description: 'Suggestions for making text more clear and easy to understand',
    tone: 'Tone',
    tone_description: 'Adjustments to improve the tone and emotional impact',
    cultural: 'Cultural',
    cultural_description: 'Considerations for cultural relevance and sensitivity',
    formality: 'Formality',
    formality_description: 'Adjustments to match appropriate level of formality',
    suggestion: 'Suggestion',
    suggestions: 'Suggestions',
    example_texts: 'Example Texts',
    try_with_these_examples: 'Try analyzing these examples',
  },
  // Help & Support System translations
  supportCenter: {
    title: 'Help & Support Center',
    subtitle: 'Find answers, resources, and support for your questions',
    tabs: {
      overview: 'Overview',
      resources: 'Resources',
      help: 'Get Help'
    },
    faq: {
      title: 'Frequently Asked Questions',
      description: 'Quick answers to common questions',
      content: 'Browse our FAQ for answers to common questions about the platform features, usage, and troubleshooting.',
      browseButton: 'Browse FAQs'
    },
    knowledgeBase: {
      title: 'Knowledge Base',
      description: 'Detailed guides and articles',
      content: 'Find in-depth articles and guides about using the platform, best practices, and advanced features.',
      browseButton: 'Browse Knowledge Base'
    },
    supportTickets: {
      title: 'Support Tickets',
      description: 'Get personalized help from our team',
      content: 'Create support tickets for direct assistance from our team. Track the status of your tickets.',
      browseButton: 'View Tickets'
    },
    getHelp: {
      title: 'Need more assistance?',
      description: 'Our support team is here to help you with any issues or questions',
      createTicketButton: 'Create Support Ticket',
      tutorialsButton: 'View Tutorials'
    },
    resources: {
      title: 'Learning Resources',
      description: 'Explore our comprehensive learning materials',
      documentation: 'Documentation',
      documentationDescription: 'Detailed technical documentation for the platform features and APIs',
      documentationButton: 'View Documentation',
      guides: 'User Guides',
      guidesDescription: 'Step-by-step guides to help you use platform features effectively',
      guidesButton: 'View Guides',
      tutorials: 'Video Tutorials',
      tutorialsDescription: 'Watch video tutorials to learn how to use the platform',
      tutorialsButton: 'Watch Tutorials'
    },
    help: {
      title: 'Get Direct Support',
      description: 'Contact our support team for personalized assistance',
      content: 'If you cannot find the answers in our knowledge base or tutorials, create a support ticket for direct assistance.',
      createTicketButton: 'Create Support Ticket',
      faqButton: 'Check FAQ First'
    },
    yourTickets: {
      title: 'Your Support Tickets',
      description: 'View and manage your existing support tickets',
      viewButton: 'View Your Tickets'
    },
    contactUs: {
      title: 'Contact Us',
      description: 'Get in touch with our support team directly',
      content: 'Have a question or need assistance? Contact our support team directly through our contact form.',
      button: 'Contact Us'
    }
  },
  faq: {
    title: 'Frequently Asked Questions',
    subtitle: 'Find quick answers to common questions about using the platform',
    backToSupport: 'Back to Support',
    searchPlaceholder: 'Search questions...',
    categoryFilterPlaceholder: 'Filter by category',
    allCategories: 'All Categories',
    frequentlyAskedQuestions: 'Frequently Asked Questions',
    frequentlyAskedQuestionsDescription: 'Browse through our commonly asked questions to find quick answers',
    filteredResults: '{{count}} Results',
    filteredDescription: 'Showing filtered questions based on your search',
    errorLoading: 'Error loading FAQs. Please try again.',
    noResultsFound: 'No FAQs found matching your search criteria.',
    clearFilters: 'Clear filters',
    needMoreHelp: {
      title: 'Still have questions?',
      description: 'If you couldn\'t find what you were looking for, we\'re here to help',
      createTicket: 'Create a Support Ticket',
      browseKnowledgeBase: 'Browse Knowledge Base'
    }
  },
  knowledgeBase: {
    title: 'Knowledge Base',
    subtitle: 'Explore guides, articles, and resources to help you use the platform effectively',
    backToSupport: 'Back to Support',
    searchPlaceholder: 'Search articles...',
    categoryFilterPlaceholder: 'Category',
    tagFilterPlaceholder: 'Tag',
    allCategories: 'All Categories',
    allTags: 'All Tags',
    allArticles: 'All Articles',
    filteredResults: '{{count}} Results',
    errorLoading: 'Error loading articles. Please try again.',
    tryAgain: 'Try Again',
    noResultsFound: 'No articles found matching your search criteria.',
    clearFilters: 'Clear Filters',
    readMore: 'Read More',
    viewAllInCategory: 'View All',
    cantFindAnswer: {
      title: 'Can\'t find what you\'re looking for?',
      description: 'Our support team is ready to assist you with your specific questions',
      createTicket: 'Create a Support Ticket',
      browseFaq: 'Browse FAQs'
    }
  },
  knowledgeArticle: {
    backToSupport: 'Support',
    knowledgeBase: 'Knowledge Base',
    loading: 'Loading article...',
    invalidId: 'Invalid Article ID',
    invalidIdDescription: 'The article ID provided is invalid. Please go back to the knowledge base.',
    backToKnowledgeBase: 'Back to Knowledge Base',
    errorLoading: 'Error loading article. It may have been removed or you may not have permission to view it.',
    publishedOn: 'Published on {{date}}',
    unknownAuthor: 'Team Member',
    helpfulVotes: 'helpful votes',
    share: 'Share',
    print: 'Print',
    wasThisHelpful: 'Was this article helpful?',
    yes: 'Yes',
    no: 'No',
    relatedTopics: 'Related Topics',
    feedbackThankYou: 'Thank you for your feedback',
    feedbackReceived: 'Your feedback helps us improve our knowledge base.',
    feedbackError: 'Error submitting feedback',
    loginRequired: 'Login required',
    loginRequiredDescription: 'Please log in to provide feedback on articles.',
    linkCopied: 'Link copied',
    linkCopiedDescription: 'Article link copied to clipboard',
    thankYouForFeedback: 'Thank you for your feedback',
    needMoreHelp: {
      title: 'Need more help?',
      description: 'If this article didn\'t fully resolve your issue, we\'re here to help',
      createTicket: 'Create a Support Ticket',
      browseFaq: 'Browse FAQs'
    }
  },
  supportTickets: {
    title: 'Support Tickets',
    subtitle: 'View and manage your support requests',
    backToSupport: 'Back to Support',
    newTicket: 'New Ticket',
    allTickets: 'All Tickets',
    allTicketsDescription: 'View all your support tickets',
    tabs: {
      all: 'All',
      open: 'Open',
      inProgress: 'In Progress',
      resolved: 'Resolved',
      closed: 'Closed'
    },
    statusTickets: {
      open: 'Open Tickets',
      'in-progress': 'In Progress Tickets',
      resolved: 'Resolved Tickets',
      closed: 'Closed Tickets'
    },
    statusTicketsDescription: {
      open: 'Newly created tickets awaiting initial response',
      'in-progress': 'Tickets currently being worked on by our support team',
      resolved: 'Tickets that have been resolved by our support team',
      closed: 'Tickets that have been closed'
    },
    status: {
      open: 'Open',
      'in-progress': 'In Progress',
      resolved: 'Resolved',
      closed: 'Closed'
    },
    priority: {
      low: 'Low Priority',
      medium: 'Medium Priority',
      high: 'High Priority'
    },
    viewDetails: 'View Details',
    errorLoading: 'Error loading tickets. Please try again.',
    tryAgain: 'Try Again',
    noTicketsFound: 'You don\'t have any support tickets yet.',
    createFirstTicket: 'Create Your First Ticket',
    adminView: 'Admin View - Showing all tickets',
    loginRequired: {
      title: 'Login Required',
      description: 'You need to be logged in to view your support tickets.',
      loginButton: 'Log In'
    },
    needHelp: {
      title: 'Need help?',
      description: 'Check our FAQs and knowledge base for quick answers to common questions',
      browseFaq: 'Browse FAQs',
      browseKnowledgeBase: 'Browse Knowledge Base'
    }
  },
  ticketDetail: {
    backToSupport: 'Support',
    supportTickets: 'Tickets',
    ticket: 'Ticket',
    loading: 'Loading ticket...',
    invalidId: 'Invalid Ticket ID',
    invalidIdDescription: 'The ticket ID provided is invalid. Please go back to tickets.',
    backToTickets: 'Back to Tickets',
    errorLoading: 'Error loading ticket. It may have been removed or you may not have permission to view it.',
    createdOn: 'Created on {{date}}',
    description: 'Description',
    attachments: 'Attachments',
    attachment: 'Attachment',
    status: {
      label: 'Status',
      selectStatus: 'Select a status',
      open: 'Open',
      'in-progress': 'In Progress',
      resolved: 'Resolved',
      closed: 'Closed'
    },
    priority: {
      low: 'Low',
      medium: 'Medium',
      high: 'High'
    },
    responses: 'Responses',
    noResponses: 'No responses yet.',
    staffResponse: 'Staff',
    supportTeam: 'Support Team',
    you: 'You',
    addResponse: 'Add Response',
    responsePlaceholder: 'Type your message here...',
    attachFilesLabel: 'Attachments (optional)',
    attachFiles: 'Attach Files',
    comingSoon: 'Coming soon',
    sending: 'Sending...',
    sendResponse: 'Send Response',
    closeTicket: 'Close Ticket',
    closing: 'Closing...',
    manageTicket: 'Manage Ticket',
    updateTicketStatus: 'Update Ticket Status',
    updateTicketStatusDescription: 'Change the status of this support ticket',
    updating: 'Updating...',
    updateStatus: 'Update Status',
    responseAdded: 'Response Added',
    responseAddedDescription: 'Your response has been successfully added to the ticket.',
    responseError: 'Error Adding Response',
    statusUpdated: 'Status Updated',
    statusUpdatedDescription: 'The ticket status has been successfully updated.',
    statusUpdateError: 'Status Update Error',
    loginRequired: {
      title: 'Login Required',
      description: 'You need to be logged in to view ticket details.',
      loginButton: 'Log In'
    },
    alerts: {
      resolved: {
        title: 'This ticket has been resolved',
        description: 'If you\'re still experiencing issues, you can add a new response or create a new ticket.'
      },
      closed: {
        title: 'This ticket has been closed',
        description: 'For further assistance, please create a new support ticket.'
      }
    },
    closeTicketDialog: {
      title: 'Close This Ticket?',
      description: 'Are you sure you want to close this ticket? This will mark the issue as resolved and the ticket will be archived.',
      cancel: 'Cancel',
      confirm: 'Yes, Close Ticket'
    },
    ticketInfo: {
      title: 'Ticket Information',
      ticketId: 'Ticket ID',
      status: 'Status',
      category: 'Category',
      priority: 'Priority',
      created: 'Created',
      resolved: 'Resolved'
    },
    backToAllTickets: 'Back to All Tickets',
    createNewTicket: 'Create New Ticket'
  },
  newTicket: {
    title: 'Create Support Ticket',
    subtitle: 'Submit a new support request to our team',
    backToSupport: 'Support',
    supportTickets: 'Tickets',
    ticketCreated: 'Ticket Created',
    ticketCreatedDescription: 'Your support ticket has been successfully created. Our team will respond as soon as possible.',
    ticketCreateError: 'Error Creating Ticket',
    form: {
      subject: 'Subject',
      subjectPlaceholder: 'Brief description of your issue',
      category: 'Category',
      categoryPlaceholder: 'Select a category',
      priority: 'Priority',
      priorityPlaceholder: 'Select priority',
      lowPriority: 'Low - General question or minor issue',
      mediumPriority: 'Medium - Issue affecting workflow',
      highPriority: 'High - Critical issue, blocking work',
      description: 'Description',
      descriptionPlaceholder: 'Please provide a detailed description of your issue including any steps to reproduce, error messages, and what you\'ve already tried...',
      attachments: 'Attachments (Optional)',
      attachFilesButton: 'Attach Files',
      comingSoon: 'File uploads coming soon',
      cancel: 'Cancel',
      submitting: 'Submitting...',
      submitTicket: 'Submit Ticket'
    },
    helpBox: {
      title: 'Tips for faster support',
      tip1: 'Be specific about your issue and include any error messages you see.',
      tip2: 'List any steps you have already taken to try to resolve the issue.',
      tip3: 'Include information about your environment (browser, device) if relevant.',
      viewFaq: 'View FAQs',
      browseKnowledgeBase: 'Browse Knowledge Base'
    },
    loginRequired: {
      title: 'Login Required',
      description: 'You need to be logged in to create a support ticket.',
      loginButton: 'Log In'
    }
  },
  performance: {
    title: 'Performance Visualization',
    description: 'Visual analysis of media platforms performance and digital presence',
    timeRange: 'Time Range',
    oneMonth: 'One Month',
    threeMonths: '3 Months',
    sixMonths: '6 Months',
    oneYear: 'One Year',
    export: 'Export',
    dataUpdated: 'Data Updated',
    dataUpdateSuccess: 'All performance data has been successfully updated.',
    dataUpdateError: 'Data Update Error',
    dataUpdateErrorDescription: 'An error occurred while updating performance data. Please try again.',
    overviewTab: 'Overview',
    sentimentTab: 'Sentiment Analysis',
    engagementTab: 'Engagement',
    performanceTab: 'Institution Performance',
    change: 'Change',
    mediaVisibility: 'Media Visibility',
    mediaVisibilityTrend: 'Evolution of media visibility across platforms during',
    mediaVisibilityIndex: 'Visibility Index',
    updatedEvery: 'Updated every',
    hours: 'hours',
    hour: 'hour',
    engagementByPlatform: 'Engagement by Platform',
    engagementCount: 'Number of engagements across various social platforms',
    engagement: 'Engagement',
    totalEngagement: 'Total Engagement',
    sentimentDistribution: 'Sentiment Distribution',
    sentimentAnalysis: 'Analysis of prevailing sentiments in digital content',
    sentimentTrends: 'Sentiment Trends',
    sentimentOverTime: 'Sentiment changes over time',
    positive: 'Positive',
    neutral: 'Neutral',
    negative: 'Negative',
    positiveChange: 'Change in positive sentiment',
    detailedEngagement: 'Detailed Engagement Analysis',
    dataShownFor: 'This data is shown for',
    loading: 'Loading institutional performance data...',
    keyPerformanceIndicators: 'Key Performance Indicators',
    measurePerformance: 'Measuring institutional performance against strategic goals',
    filterResults: 'Filter Results',
    target: 'Target',
    dataUpdatedOn: 'Data updated on',
  },
  reports: {
    title: 'Reports',
    overview: 'Overview',
    overviewDescription: 'Comprehensive overview of GEM 2.0 key performance indicators',
    performanceTrends: 'Performance Trends',
    trendsDescription: 'Monitor performance trends over time',
    responseTimeAnalysis: 'Response Time Analysis',
    responseTimeDescription: 'Analysis of response times across different channels',
    keyPerformanceIndicators: 'Key Performance Indicators',
    kpiDescription: 'Detailed breakdown of key performance indicators',
    socialMediaReport: 'Social Media Report',
    socialMediaReportDescription: 'Detailed analysis of social media performance',
    socialMediaReportTitle: 'Generate Social Media Report',
    socialMediaReportMessage: 'Generate a comprehensive report on social media performance, engagement metrics, and sentiment analysis across platforms.',
    socialMediaEngagement: 'Social Media Engagement',
    engagementTrendsDescription: 'Engagement trends over the past six months',
    topPerformingContent: 'Top Performing Content',
    contentWithHighestEngagement: 'Content with the highest engagement across platforms',
    audienceDemographics: 'Audience Demographics',
    audienceInsights: 'Demographic insights of your audience',
    audiencePercentage: 'Audience Percentage',
    geographicDistribution: 'Geographic Distribution',
    audienceLocation: 'Audience location by region',
    sentimentByPlatformDescription: 'Sentiment distribution across all platforms',
    printReport: 'Print Report',
    shareReport: 'Share Report',
    sentimentReport: 'Sentiment Report',
    sentimentAnalysis: 'Sentiment Analysis',
    sentimentAnalysisDescription: 'Detailed analysis of sentiment across platforms',
    sentimentDistribution: 'Sentiment Distribution',
    keyInsights: 'Key Insights',
    positiveSentiment: 'Positive Sentiment',
    positiveSentimentDesc: 'Content that primarily received positive engagement and reactions.',
    neutralSentiment: 'Neutral Sentiment',
    neutralSentimentDesc: 'Content that primarily received neutral or informational reactions.',
    negativeSentiment: 'Negative Sentiment',
    negativeSentimentDesc: 'Content that received significant negative reactions or criticism.',
    customReport: 'Custom Report',
    customReportDescription: 'Create custom reports based on specific criteria',
    customReportTitle: 'Create Custom Report',
    customReportMessage: 'Specify custom parameters, date ranges, and metrics to create a report tailored to your analytical needs.',
    exportData: 'Export Data',
    viewDetailedReport: 'View Detailed Report',
    generateReport: 'Generate Report',
    createCustomReport: 'Create Custom Report',
    minutes: 'minutes',
    improvement: 'improvement',
    slower: 'slower',
    digitalResponsiveness: 'Digital Responsiveness',
    negativeResponseTime: 'Negative Response Time',
    positiveEngagement: 'Positive Engagement',
    innovationIndex: 'Innovation Index',
    osintMaturity: 'OSINT Maturity',
    futureReadiness: 'Future Readiness',
    strategicForesight: 'Strategic Foresight',
    sentimentAnalytics: 'Sentiment Analytics',
    performanceScore: 'Performance Score',
    positiveResponse: 'Positive Response',
    negativeResponse: 'Negative Response',
    
    // Smart Reports
    smartReportsTitle: 'Smart Reports',
    smartReportsDescription: 'Compile different aspects into comprehensive reports',
    createSmartReport: 'Create Smart Report',
    smartReportName: 'Report Name',
    smartReportNamePlaceholder: 'Enter a name for your report',
    reportComponents: 'Report Components',
    selectComponents: 'Select report components',
    excellenceComponent: 'Excellence Indicators',
    socialMediaComponent: 'Social Media Analysis',
    sentimentComponent: 'Sentiment Analysis',
    entitiesComponent: 'Government Entities',
    mediaComponent: 'Media Coverage',
    includeCharts: 'Include Charts',
    includeRawData: 'Include Raw Data',
    includeSummary: 'Include Summary',
    compileReport: 'Compile Report',
    savedReports: 'Saved Reports',
    noSavedReports: 'No saved reports yet',
    generatingReport: 'Generating report...',
    reportHistory: 'Report History',
    latestReports: 'Latest Reports',
    scheduledReports: 'Scheduled Reports',
    scheduleReport: 'Schedule Report',
    frequency: 'Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    recipients: 'Recipients',
    addRecipient: 'Add Recipient',
    reportCompiledSuccess: 'Report compiled successfully',
    reportScheduledSuccess: 'Report scheduled successfully',
    compareReports: 'Compare Reports',
    reportTemplates: 'Report Templates',
    useTemplate: 'Use Template',
    saveAsTemplate: 'Save as Template',
    editTemplate: 'Edit Template',
    deleteTemplate: 'Delete Template',
    confirmDeleteTemplate: 'Are you sure you want to delete this template?',
  },
  navigation: {
    home: 'Home',
    reports: 'Reports',
    dashboard: 'Dashboard',
    personalizedDashboard: 'Personalized Dashboard',
    mediaCenter: 'Media Center',
    socialMediaManagement: 'Social Media Management',
    // Social Media Management for Ajman Police
  socialMedia: {
    title: 'Social Media Management',
    dashboard: 'Dashboard',
    accounts: 'Official Accounts',
    publish: 'Publish Content',
    analytics: 'Analytics',
    realTimeUpdates: 'Live Monitoring Updates',
    offlineMode: 'Offline Mode',
    posts: 'Posts',
    engagement: 'Engagement',
    reach: 'Reach',
    connectedPlatforms: 'Ajman Police Official Platforms',
    engagementOverview: 'Engagement Overview',
    lastThirtyDays: 'Last 30 Days',
    trendingTopics: 'Trending Topics',
    realTimeMonitoring: 'Monitor trending topics and hashtags',
    audienceDemographics: 'Audience Demographics',
    sentimentAnalysis: 'Sentiment Analysis',
    selectTimeframe: 'Select Timeframe',
    timeframe: {
      day: 'Day',
      week: 'Week',
      month: 'Month',
      quarter: 'Quarter'
    },
    sentimentTrend: 'Sentiment Trend',
    sentimentTrendDescription: 'Analysis of sentiment evolution over time',
    currentSentiment: 'Current Sentiment',
    sentiment: {
      positive: 'Positive',
      neutral: 'Neutral',
      negative: 'Negative'
    },
    recentPosts: 'Recent Posts',
    noPosts: 'No posts available',
    connectedAccounts: 'Connected Accounts',
    manageYourAccounts: 'Manage Ajman Police social media accounts',
    connected: 'Connected',
    manage: 'Manage',
    connectNew: 'Connect New Account',
    addAccount: 'Add social media official account',
    connect: 'Connect',
    createPost: 'Create Post',
    shareAcrossPlatforms: 'Share content across social platforms',
    whatToShare: 'What would you like to share?',
    addImage: 'Add Image',
    addVideo: 'Add Video',
    addDocument: 'Add Document',
    mention: 'Mention',
    hashtag: 'Hashtag',
    schedule: 'Schedule',
    publishButton: 'Publish',
    scheduledPosts: 'Scheduled Posts',
    noScheduledPosts: 'No scheduled posts',
    scheduleMessage: 'Schedule your posts to publish automatically at specific times',
    detailedAnalytics: 'Detailed Analytics',
    performanceInsights: 'Performance insights for Ajman Police accounts',
    totalEngagement: 'Total Engagement',
    topPerformingPosts: 'Top Performing Posts',
    audienceGrowth: 'Audience Growth',
    followers: 'Followers',
    likes: 'Likes',
    comments: 'Comments',
    shares: 'Shares',
    // OSINT related translations
    osintMonitoring: 'OSINT Monitoring',
    contentArchive: 'Content Archive',
    archiveDescription: 'Archive of search content and related accounts',
    searchKeywords: 'Search Keywords',
    searchAccounts: 'Search Accounts',
    saveToArchive: 'Save to Archive',
    archivedContent: 'Archived Content',
    threatLevel: 'Threat Level',
    relevanceScore: 'Relevance Score',
    informationValue: 'Information Value',
    actionNeeded: 'Action Needed',
    monitorOnly: 'Monitor Only',
    escalate: 'Escalate',
    investigate: 'Investigate',
    monitorHash: 'Monitor Hashtag',
    keywordAlert: 'Keyword Alert',
    addFlaggedAccount: 'Add Flagged Account',
    viewOriginalPost: 'View original post',
    platform: {
      twitter: 'Twitter',
      facebook: 'Facebook',
      instagram: 'Instagram',
      linkedin: 'LinkedIn',
      youtube: 'YouTube',
      tiktok: 'TikTok',
      snapchat: 'Snapchat',
      telegram: 'Telegram'
    },
    exportOsintReport: 'Export OSINT Report',
    flaggedAccounts: 'Flagged Accounts',
    flaggedContent: 'Flagged Content',
    searchHistory: 'Search History',
    savedSearches: 'Saved Searches',
  },
    monitoring: 'Media Monitoring',
    entityMonitoring: 'Government Entity Monitoring',
    pressRelease: 'Press Release',
    smartReports: 'Smart Reports',
    excellenceIndicators: 'Institutional Excellence Indicators',
    performanceVisualization: 'Performance Visualization',
    contextHints: 'Language Context Hints',
    viewPerformanceVisualization: 'View Performance Visualization',
    users: 'User Management',
    tutorials: 'Tutorials',
    settings: 'Settings',
    help: 'Help',
    sidebarLabel: 'Main Navigation',
  },
  gem: {
    title: 'GEM 2.0 Indicators',
    kpiTitle: 'GEM 2.0 Index',
  },
  emojiReactions: {
    // Positive messages
    exceptional: 'Exceptional performance!',
    excellent: 'Excellent achievement!',
    onTrack: 'On track to meet target',
    // Neutral messages
    progressing: 'Making progress',
    needsAttention: 'Needs some attention',
    // Negative messages
    belowTarget: 'Below target',
    significantGap: 'Significant gap to target',
    critical: 'Critical attention required',
    // Values
    currentValue: 'Current value',
    targetValue: 'Target value'
  },
  excellence: {
    title: 'Institutional Excellence Indicators',
    description: 'Track and analyze KPIs for institutional excellence across strategic axes',
    dateRange: 'Date Range',
    pickDates: 'Select dates',
    strategicAxis: 'Strategic Axis',
    allAxes: 'All Axes',
    communication: 'Communication',
    innovation: 'Innovation',
    smartTransformation: 'Smart Transformation',
    dataManagement: 'Data & Knowledge',
    mainIndicators: 'Main Indicators',
    subIndicators: 'Sub-Indicators',
    refresh: 'Refresh Data',
    exportCSV: 'Export CSV',
    exportPDF: 'Export PDF',
    current: 'Current Value',
    target: 'Target Value',
    status: 'Status',
    progress: 'Progress',
    metricDetails: 'Metric Details',
    noData: 'No data available for the selected period',
    noDataForAxis: 'No data available for this strategic axis in the selected period',
    loadingData: 'Loading indicators data...',
    filterResults: 'Filter Results',
    applyFilters: 'Apply Filters',
    resetFilters: 'Reset',
    dataNotAvailable: 'Data not available',
    
    // Communication KPIs
    coverageVolume: 'Media Coverage Volume',
    positiveCoverageRate: 'Positive Coverage Rate',
    mediaSentimentIndex: 'Media Sentiment Index',
    socialEngagementRate: 'Social Media Engagement Rate',
    responseTime: 'Response Time',
    shareOfVoice: 'Share of Voice',
    
    // Innovation KPIs
    implementedInnovations: 'Implemented Innovations',
    ideaImplementationRate: 'Idea Implementation Rate',
    employeeInnovationRate: 'Employee Innovation Participation',
    innovationAwards: 'Innovation Awards & Recognition',
    operationalEfficiency: 'Operational Efficiency Improvement',
    innovationMediaCoverage: 'Innovation Media Coverage',
    
    // Smart Transformation KPIs
    digitalServicesPercent: 'Digital Services Percentage',
    digitalServicesAdoptionRate: 'Digital Services Adoption Rate',
    smartServicesUserSatisfaction: 'Smart Services User Satisfaction',
    internalProcessesAutomation: 'Internal Processes Automation',
    smartInitiativesImplemented: 'Smart Initiatives Implemented',
    
    // Data & Knowledge KPIs
    knowledgeSharingSessions: 'Knowledge Sharing Sessions',
    avgTrainingHours: 'Average Training Hours',
    coreDataAccuracyRate: 'Core Data Accuracy Rate',
    statisticalReportsPublished: 'Statistical Reports Published',
    dataDrivenDecisionIndex: 'Data-Driven Decision Index',
    
    // Overview Charts
    overviewCharts: 'KPI Overview Charts',
    axesOverview: 'Strategic Axes Overview',
    progressByAxis: 'Progress comparison by strategic axis',
    percentProgress: 'Percent Progress',
    kpiProgress: 'KPI Progress Chart',
    keyIndicatorsRating: 'Key indicators achievement rating',
    achievement: 'Achievement Rate',
    refreshData: 'Refresh Data',
    
    // Export functionality
    exportFullReport: 'Download Full Report',
    exportOptions: 'Export Options',
    exportExcel: 'Export Excel',
    exportError: 'Export Error',
    noDataToExport: 'No data available to export',
    exportSuccess: 'Export Successful',
    reportExported: 'Your report has been exported successfully'
  },
  charts: {
    months: {
      jan: 'January',
      feb: 'February',
      mar: 'March',
      apr: 'April',
      may: 'May',
      jun: 'June',
      jul: 'July',
      aug: 'August',
      sep: 'September',
      oct: 'October',
      nov: 'November',
      dec: 'December'
    },
    week: 'Week',
    digitalResponsiveness: 'Digital Responsiveness',
    negativeFeedbackResponse: 'Negative Feedback Response',
    positiveEngagement: 'Positive Engagement',
    osintMaturity: 'OSINT Maturity',
    futureReadiness: 'Future Readiness',
    strategicForesight: 'Strategic Foresight',
    sentimentAnalytics: 'Sentiment Analytics',
    innovationIndex: 'Innovation Index',
  },
  dashboard: {
    mainTitle: 'Main Dashboard',
    timeFilter: 'Last 30 Days',
    downloadReport: 'Download Report',
    timeAndCalendar: 'Time & Calendar',
    search: 'Search dashboard',
    searchKeywords: 'Search keywords or content',
    searchResults: 'Search Results',
    noSearchResults: 'No matching posts found',
    filter: 'Filters',
    applyFilters: 'Apply Filters',
    today: 'Today',
    last7Days: 'Last 7 Days',
    last14Days: 'Last 14 Days',
    last30Days: 'Last 30 Days',
    last90Days: 'Last 90 Days',
    custom: 'Custom',
    mentionsTotal: 'Total Mentions',
    sentimentAverage: 'Average Sentiment',
    responseTime: 'Response Speed',
    innovationIndex: 'Innovation Index',
    comparedTo: 'Compared to',
    realtimeSentimentTrends: 'Real-time Sentiment Trends',
    trackSentimentChanges: 'Track sentiment changes over time with animated sparkline visualization',
    sentimentTrend: 'Sentiment Trend',
    selectPlatform: 'Select Platform',
    selectTimeRange: 'Select Time Range',
    allPlatforms: 'All Platforms',
    refresh: 'Refresh',
    loadingTrendData: 'Loading trend data...',
    noTrendDataAvailable: 'No trend data available',
    timePeriod: 'Time period',
    sentimentPercentage: 'Sentiment percentage',
    positive: 'Positive',
    neutral: 'Neutral',
    negative: 'Negative',
    positiveIncreasing: 'Positive sentiment is increasing',
    positiveDecreasing: 'Positive sentiment is decreasing',
    negativeIncreasing: 'Negative sentiment is increasing (concerning)',
    negativeDecreasing: 'Negative sentiment is decreasing (good)',
    newsSource: 'News Sources',
    refreshAriaLabel: 'Refresh trend data',
    sentimentTrendVisualization: 'Sentiment trend visualization',
    sentimentChartDescription: 'This chart shows sentiment trends over time, with separate lines for positive, neutral, and negative sentiment percentages.',
    sentimentDistributionLabel: 'Sentiment distribution: {{positive}}% positive, {{neutral}}% neutral, {{negative}}% negative',
    offline: 'Offline',
    live: 'Live',
    inPreviousPeriod: 'in previous period',
    minutes: 'minutes',
    relativelyStable: 'Relatively stable compared to previous period',
    averageResponseTime: 'Average response time to negative comments',
    notableImprovement: 'Notable improvement over last year',
    dashboardTitle: 'Dashboard',
    dashboardDescription: 'Choose between standard or personalized interface to view data',
    standardDashboard: 'Standard Dashboard',
    personalizedDashboard: 'Personalized Dashboard',
    widgetSettings: 'Widget Settings',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    customizeDashboard: 'Customize Dashboard',
    addWidgets: 'Add Widgets',
    loading: 'Loading dashboard...',
    title: 'Dashboard',
    saveSuccess: 'Dashboard Saved',
    saveSuccessDescription: 'Your dashboard layout has been saved successfully',
    saveFailed: 'Save Failed',
  },
  analysis: {
    sentimentAnalysis: 'Sentiment Analysis',
    platforms: 'Social Platforms',
    mainTopics: 'Main Topics',
    demographics: 'Demographics',
    sentimentOverTime: 'Sentiment Analysis Over Time',
    sentimentChart: 'Chart for sentiment analysis over time',
    trendDisplay: 'Shows trends for positive, negative, and neutral sentiment',
    sentimentDistribution: 'Sentiment Distribution',
    positive: 'Positive',
    neutral: 'Neutral',
    negative: 'Negative',
    overallSentiment: 'Overall Sentiment',
    influentialKeywords: 'Influential Keywords',
    sourceBreakdown: 'Source Breakdown',
    sentimentFilters: 'Sentiment Filters',
    positiveSentiment: 'Positive Sentiment Analysis',
    negativeSentiment: 'Negative Sentiment Analysis',
    sentimentImprovement: 'Sentiment Improvement Analysis',
    sentimentDecrease: 'Sentiment Decrease Analysis',
    sentimentByPlatform: 'Sentiment Analysis by Platform',
    trackSentimentChanges: 'Track sentiment changes over time with animated sparkline visualization',
  },
  monitoring: {
    title: 'Media Monitoring',
    all: 'All',
    allPlatforms: 'All Platforms',
    twitter: 'Twitter',
    facebook: 'Facebook',
    instagram: 'Instagram',
    news: 'News Sites',
    clearAll: 'Clear All',
    downloadReport: 'Download Report',
    alertSettings: 'Alert Settings',
    hoursAgo: '{{hours}} hours ago',
    keywords: 'Keywords',
    addKeyword: 'Add new keyword',
    activeAlerts: 'Active Alerts',
    negativeRise: 'Rise in negative mentions',
    threshold: 'Threshold',
    keywordTrends: 'Keywords in trends',
    mentions: 'mentions',
    defaultUser: 'User',
    defaultUsername: 'username',
    noPosts: 'No posts found',
    twitterContent: 'Twitter content',
    facebookContent: 'Facebook content',
    instagramContent: 'Instagram content',
    newsContent: 'News content',
    engagement: {
      likes: '{{count}}',
      comments: '{{count}}',
      shares: '{{count}}'
    }
  },
  entity: {
    testPage: 'Entity Monitoring Test Page',
    normalView: 'Normal View',
    debugView: 'Debug View',
    monitoring: 'Government Entity Monitoring',
    enableDebugMode: 'Enable Debug Mode',
    disableDebugMode: 'Disable Debug Mode',
    directAccessTest: 'Direct Access Test',
    enterEntityId: 'Enter Entity ID',
    entityIdPlaceholder: 'e.g., 1, 2, 3...',
    goToEntityPage: 'Go to Entity Page',
    availableEntities: 'Available Entities',
    errorLoadingEntities: 'Error Loading Entities',
  },
  entities: {
    title: 'UAE Government Entities Monitoring',
    allTypes: 'All Types',
    allRegions: 'All Regions',
    activeOnly: 'Active entities only',
    filters: 'Filters',
    refineEntities: 'Refine the government entities displayed below',
    search: 'Search',
    searchByName: 'Search by name',
    entityType: 'Entity Type',
    region: 'Region',
    addEntity: 'Add Entity',
    viewDetails: 'View Details',
    totalMentions: 'Total Mentions',
    avgSentiment: 'Average Sentiment',
    sentimentBreakdown: 'Sentiment Breakdown',
    mostActivePlatform: 'Most Active Platform',
    ofAllMentions: '% of all mentions',
    posts: 'Posts',
    trends: 'Trends',
    analytics: 'Analytics',
    noMentions: 'No mentions found for this entity yet. Check back later.',
    sentimentTrend: 'Sentiment Trend',
    sentimentOverTime: 'Sentiment analysis over time',
    mentionsByPlatform: 'Mentions by Platform',
    platformDistribution: 'Distribution across social media',
    noDataForTrend: 'Not enough data points to display a trend.',
    noDataForDistribution: 'No data available for platform distribution.',
    sentimentAnalysis: 'Sentiment Analysis',
    sentimentDistribution: 'Breakdown of sentiment distribution in mentions',
    noDataForAnalysis: 'No sentiment data available for analysis.',
    positive: 'Positive',
    neutral: 'Neutral',
    negative: 'Negative',
    federal: 'Federal',
    local: 'Local',
    ministry: 'Ministry',
    authority: 'Authority',
    council: 'Council',
    active: 'Active',
    inactive: 'Inactive',
    edit: 'Edit Government Entity',
    add: 'Add Government Entity',
    editDescription: 'Update details of this government entity',
    addDescription: 'Add a new government entity to the monitoring system',
    nameEnglish: 'Name (English)',
    nameArabic: 'Name (Arabic)',
    iconUrl: 'Icon URL',
    iconUrlDescription: 'Link to entity logo or icon',
    websiteUrl: 'Website URL',
    websiteUrlDescription: 'Official website of the entity',
    priority: 'Priority',
    priorityDescription: 'Higher priority entities show first (0-100)',
    activeStatus: 'Active',
    inactiveDescription: 'Inactive entities will not be monitored',
    delete: 'Delete',
    deleteEntity: 'Delete Government Entity',
    deleteConfirmation: 'Are you sure you want to delete this entity? This action cannot be undone.',
    cancel: 'Cancel',
    update: 'Update',
    create: 'Create',
    entityCreated: 'Government Entity Created',
    entityUpdated: 'Government Entity Updated',
    entityDeleted: 'Government Entity Deleted',
    createFailed: 'Entity Creation Failed',
    updateFailed: 'Entity Update Failed',
    deleteFailed: 'Entity Deletion Failed',
  },
  mediaCenter: {
    title: 'Media Center',
    viewAll: 'View All',
    image: 'Image',
    video: 'Video',
    document: 'Document',
    updated: 'Updated',
    days: 'day',
    weeks: 'week',
    projects: 'Projects',
    events: 'Events',
    reports: 'Reports',
    news: 'News',
    search: 'Search',
    filter: 'Filter',
    date: 'Date',
    newest: 'Newest',
    oldest: 'Oldest',
    lastWeek: 'Last Week',
    upload: 'Upload File',
    all: 'All',
    uaeNewsSources: 'UAE News Sources',
    integratedPlatforms: 'Integrated Local & Government Platforms',
    internalMediaLibrary: 'Internal Media Library',
    browse: 'Browse',
    visitWebsite: 'Visit Website',
    visitOfficialWebsite: 'Visit Official Website',
    downloadFile: 'Download File',
    shareContent: 'Share Content',
    viewFullArticle: 'View Full Article',
    viewFullPressRelease: 'View Full Press Release',
    ajmanGovPressReleases: 'Ajman Government Press Releases',
    ajmanPoliceNews: 'Ajman Police News and Updates',
    wamNewsAgency: 'WAM News Agency',
    sourcePlatforms: 'Source Platforms',
    ajmanGovDescription: 'Access to press releases, news, and official announcements from Ajman Government.',
    ajmanPoliceDescription: 'Access to security updates, community news, and safety information from Ajman Police.',
    wamDescription: 'Access to WAM (Emirates News Agency) for comprehensive UAE news and updates.',
  },
  tutorials: {
    title: 'Tutorials',
    viewAll: 'View All',
    duration: 'Video Duration',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    invalidCredentials: 'Invalid credentials',
  },
  notifications: {
    title: 'Notifications',
    keywordAlert: 'Alert: Rise in "Innovation" keyword mentions',
    negativeReaction: 'Alert: Negative reactions to Facebook post',
    newReport: 'Alert: New report ready for download',
    minutesAgo: '{{minutes}} minutes ago',
    hoursAgo: '{{hours}} hours ago',
  },
  common: {
    language: 'Language',
    arabic: 'Arabic',
    english: 'English',
    id: 'ID',
    backToList: 'Back to list',
    admin: 'Admin',
    analyst: 'Analyst',
    editor: 'Editor',
    viewer: 'Viewer',
    official: 'Official',
    loading: 'Loading...',
    processing: 'Processing...',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    create: 'Create',
    creating: 'Creating...',
    deleting: 'Deleting...',
    actions: 'Actions',
    deleteAction: 'Delete this item',
    deletingAction: 'Deleting this item',
    cancelAction: 'Cancel this action',
    processingRequest: 'Processing your request...'
  },
  export: {
    formatPNG: 'PNG',
    formatPDF: 'PDF',
    formatExcel: 'Excel'
  },
  social: {
    facebook: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    telegram: 'Telegram',
    linkedin: 'LinkedIn',
    youtube: 'YouTube',
    tiktok: 'TikTok',
    snapchat: 'Snapchat',
    news: 'News'
  },
  settings: {
    title: 'Settings',
    settingsMenu: 'Settings Menu',
    profileTab: 'Profile',
    appearanceTab: 'Appearance',
    notificationsTab: 'Notifications',
    securityTab: 'Security',
    apiTab: 'API & Integrations',
    helpTab: 'Help & Support',
    profileSettings: 'Profile Settings',
    profileDescription: 'Manage your personal information and preferences',
    personalDetails: 'Personal Details',
    nameLabel: 'Full Name',
    namePlaceholder: 'Enter your name',
    emailLabel: 'Email Address',
    emailPlaceholder: 'your.email@example.com',
    roleLabel: 'Role',
    accountType: 'Account Type',
    timeZoneLabel: 'Time Zone',
    bioLabel: 'Bio',
    bioPlaceholder: 'Write a short bio about yourself',
    appearanceSettings: 'Appearance Settings',
    appearanceDescription: 'Customize the appearance and localization of the platform',
    language: 'Language',
    selectLanguage: 'Select a language',
    addLanguage: 'Add New Language',
    theme: 'Theme',
    lightTheme: 'Light Mode',
    darkTheme: 'Dark Mode',
    systemTheme: 'System Default',
    textDirection: 'Text Direction',
    rtl: 'Right to Left (RTL)',
    ltr: 'Left to Right (LTR)',
    notificationSettings: 'Notification Settings',
    notificationDescription: 'Manage how and when you receive notifications',
    emailNotifications: 'Email Notifications',
    dashboardAlerts: 'Dashboard Alerts',
    platformStatus: 'Platform Status Updates',
    negativeMentions: 'Negative Mentions',
    keywordSpikes: 'Keyword Mention Spikes',
    systemNotifications: 'System Notifications',
    systemTrend: 'Trending Topics',
    systemNegative: 'Negative Sentiment Alerts',
    systemLogin: 'Login Attempts',
    securitySettings: 'Security Settings',
    securityDescription: 'Manage your account security and access settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    twoFactorAuth: 'Two-Factor Authentication',
    enableTwoFactor: 'Enable Two-Factor Authentication',
    securityOptions: 'Security Options',
    sessionTimeout: 'Session Timeout',
    loginHistory: 'Login History',
    view: 'View',
    apiSettings: 'API & Integrations',
    apiDescription: 'Manage API keys and external integrations',
    apiKeys: 'API Keys',
    apiUsage: 'API Usage',
    activeKey: 'Active',
    noActiveKeys: 'No active API keys',
    generateNewKey: 'Generate New Key',
    dataUsage: 'Data Usage',
    quotaResets: 'Quota resets on',
    webhooks: 'Webhooks',
    noWebhooks: 'No webhooks configured',
    addWebhook: 'Add Webhook',
    helpSupport: 'Help & Support',
    helpDescription: 'Resources and support options to help you use the platform',
    documentation: 'Documentation',
    documentationDesc: 'Find help and guides for using the Media Intelligence Platform',
    viewDocs: 'View Documentation',
    tutorials: 'Tutorials',
    tutorialsDesc: 'Video tutorials and step-by-step guides',
    viewTutorials: 'View Tutorials',
    supportTicket: 'Support Ticket',
    supportTicketDesc: 'Submit an issue or question to our support team',
    createTicket: 'Create Ticket',
    contactUs: 'Contact Us',
    contactUsDesc: 'Direct contact information for our support team',
    contactSupport: 'Contact Support',
    faq: 'Frequently Asked Questions',
    faq1: 'How do I interpret the sentiment analysis scores?',
    faq2: 'Can I export data to other formats?',
    faq3: 'How often is social media data updated?',
    saveChanges: 'Save Changes',
    langManagement: 'Language Management',
    langManagementDescription: 'Add, edit or remove language options for the platform',
    availableLanguages: 'Available Languages',
    languageSelector: 'Language Selector',
    languageCode: 'Language Code',
    langName: 'Language Name',
    langNameEnglish: 'Language Name (English)',
    langNameNative: 'Language Name (Native)',
    actions: 'Actions',
    editLang: 'Edit',
    deleteLang: 'Delete',
    defaultLang: 'Default',
    makeDefault: 'Make Default',
    addLangTitle: 'Add New Language',
    importLangFile: 'Import Language File',
    uploadLangFile: 'Upload Translation File',
    langFileFormat: 'JSON format required',
    completeness: 'Completeness',
  },
  contact: {
    title: 'Contact Us',
    subtitle: 'Reach out to us with any questions, feedback, or inquiries.',
    backToHome: 'Back to Home',
    thankYou: 'Message Sent!',
    responseTime: 'We typically respond within 24-48 business hours.',
    sendAnother: 'Send Another Message',
    successTitle: 'Message Sent',
    successMessage: 'Your contact request has been submitted successfully. We\'ll get back to you soon.',
    errorTitle: 'Error',
    errorMessage: 'There was a problem sending your message. Please try again.',
    form: {
      name: 'Name',
      namePlaceholder: 'Enter your full name',
      email: 'Email',
      emailPlaceholder: 'Enter your email address',
      subject: 'Subject',
      subjectPlaceholder: 'What is this regarding?',
      department: 'Department',
      departmentPlaceholder: 'Select a department',
      departments: {
        support: 'Technical Support',
        sales: 'Sales & Pricing',
        billing: 'Billing & Accounts',
        technical: 'Technical Integration',
        partnership: 'Partnership Opportunities',
        other: 'Other Inquiries'
      },
      message: 'Message',
      messagePlaceholder: 'Please describe your inquiry in detail...',
      submit: 'Send Message',
      sending: 'Sending...'
    },
    contactInfo: {
      title: 'Contact Information',
      subtitle: 'Here\'s how you can reach us directly',
      email: 'Email Us',
      phone: 'Call Us',
      address: 'Visit Us',
      addressLine1: 'Media Intelligence Platform HQ',
      addressLine2: 'Abu Dhabi Media Zone, UAE',
      hours: 'Business Hours',
      workdays: 'Sunday - Thursday',
      weekend: 'Friday - Saturday',
      closed: 'Closed'
    }
  },
  entityType: {
    ministry: 'Ministry',
    authority: 'Authority',
    department: 'Department',
    agency: 'Agency',
    council: 'Council',
    committee: 'Committee'
  },
  users: {
    title: 'User Management',
    usersDirectory: 'Users Directory',
    manageAccounts: 'Manage user accounts and permissions',
    search: 'Search users...',
    addUser: 'Add User',
    addNewUser: 'Add New User',
    fillDetails: 'Fill in the user details to create a new account',
    user: 'User',
    username: 'Username',
    usernamePlaceholder: 'Enter username',
    email: 'Email',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter full name',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    role: 'Role',
    roles: {
      admin: 'Administrator',
      editor: 'Editor',
      analyst: 'Analyst',
      user: 'User'
    },
    selectRole: 'Select role',
    language: 'Language',
    languages: {
      arabic: 'Arabic',
      english: 'English'
    },
    selectLanguage: 'Select language',
    resetPassword: 'Reset Password',
    createSuccess: 'User Created',
    userCreated: 'User {{name}} has been created successfully',
    createError: 'Create Error',
    createErrorMessage: 'An error occurred while creating the user',
    confirmDelete: 'Confirm Delete',
    confirmDeleteDescription: 'Are you sure you want to delete this user? This action cannot be undone.',
    deleteSuccess: 'User Deleted',
    userDeleted: 'User has been deleted successfully',
    deleteError: 'Delete Error',
    deleteErrorMessage: 'An error occurred while deleting the user',
    noUsersFound: 'No users found',
    userActions: 'Actions for user {{name}}',
    editUserAction: 'Edit user {{name}}',
    resetPasswordAction: 'Reset password for user {{name}}',
    deleteUserAction: 'Delete user {{name}}'
  },
  // Voice Assistant translations
  assistant: {
    title: 'KPI Assistant',
    showAssistant: 'Show Voice Assistant',
    hideAssistant: 'Hide Voice Assistant',
    chat: 'Chat',
    help: 'Help',
    voiceCommands: 'Voice Commands',
    error: 'Voice Assistant Error',
    microphoneError: 'Could not access microphone. Please check your browser permissions.',
    startError: 'Could not start voice recognition. Please try again.',
    unsupported: 'Unsupported Browser',
    browserUnsupported: 'Your browser does not support voice recognition.',
    listening: 'Listening...',
    clickToSpeak: 'Click microphone to speak',
    navigation: 'Section Navigation',
    navExample1: 'Show me communication metrics',
    navExample2: 'Go to data management section',
    getHelp: 'Getting Help',
    helpExample: 'What can you help me with?',
    closeAssistant: 'Closing Assistant',
    closeExample: 'Close assistant'
  }
};

export default enTranslations;